import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_B: KnowledgeEntry[] = [
  // ── POWER TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'mb-table-saw-blade-height',
    topic: 'Table saw blade height for ripping and dadoing',
    keywords: ['table','saw','blade','height','rip','expose','set','above'],
    answer: 'For ripping, set the blade 1/8"–1/4" above the stock thickness — just enough to clear the top of the board. Higher blades kick back more aggressively; lower blades produce more heat and burning. For dado cuts, set the dado stack to exactly the depth you need and test on scrap. Never expose more blade than necessary — the exposed arc above the work is the kickback zone.',
  },
  {
    id: 'mb-table-saw-fence-setup',
    topic: 'Setting a table saw fence parallel to the blade',
    keywords: ['fence','parallel','blade','table','saw','dial','indicator','toe','in'],
    answer: 'A fence parallel to the blade produces clean rips; a fence that\'s toed in at the back (toward the blade) causes burning and kickback. Measure from a fixed tooth at the front and rear of the blade to the fence — both measurements should be identical. Some woodworkers prefer 1/64" of toe-out (fence slightly farther from blade at rear) to help guide the wood away from the blade. Use a dial indicator for precision on production work.',
  },
  {
    id: 'mb-table-saw-crosscut',
    topic: 'Crosscuts on the table saw with miter gauge',
    keywords: ['crosscut','miter','gauge','table','saw','square','sled','accurate'],
    answer: 'The miter gauge\'s small fence doesn\'t support long boards well — use a crosscut sled for longer pieces. Set the miter gauge or sled to exactly 90° using a reliable square, then test-cut two pieces and check them back to back for gaps. A fence extension screwed to the miter gauge helps support wider panels. Never use the rip fence as a length stop for crosscuts without a stop block that the workpiece clears before reaching the blade — otherwise the offcut can pinch and kick.',
  },
  {
    id: 'mb-dado-stack-setup',
    topic: 'Setting up a dado stack on the table saw',
    keywords: ['dado','stack','chipper','shim','width','flat','bottom','table','saw'],
    answer: 'A dado stack combines outer blades with inner chippers and shims to cut wide, flat-bottomed grooves in one pass. Outside blades set the kerf edges; chipper blades are 1/8" wide each and fill in between. Shims (paper-thin to 1/16") fine-tune the total width. Always test the dado width and depth on scrap first — chippers packed out of balance cause vibration. A sacrificial zero-clearance throat plate prevents tearout on dado edges.',
  },
  {
    id: 'mb-table-saw-zero-clearance',
    topic: 'Zero-clearance insert for the table saw',
    keywords: ['zero','clearance','insert','throat','plate','tearout','support','veneer'],
    answer: 'A zero-clearance insert (ZCI) has the saw blade rise through it, leaving no gap around the blade. It supports the wood fibers right up to the cut, eliminating tearout on the bottom face. Make one from 1/4" MDF or hardboard: lower the blade, set the blank over the blade slot, clamp firmly, and slowly raise the spinning blade through it. Make a new one for each blade angle and dado width you use regularly.',
  },
  {
    id: 'mb-bandsaw-resawing',
    topic: 'Resawing on the bandsaw — blade and technique',
    keywords: ['bandsaw','resaw','blade','fence','TPI','drift','wide','veneer'],
    answer: 'Resawing means cutting a thick board into thinner slabs through its width. Use a 3/4"–1" wide blade with 2–3 TPI (few teeth, large gullets to clear sawdust). Drift — the tendency of the blade to wander from a parallel line — must be accounted for by setting your fence at the drift angle rather than parallel to the table. Feed slowly; forcing the feed causes blade deflection and wavy cuts. A single-point fence (a board clamped to the table at the drift angle) works better than a full fence for resawing.',
  },
  {
    id: 'mb-bandsaw-blade-tension',
    topic: 'Bandsaw blade tension and tracking',
    keywords: ['bandsaw','blade','tension','track','crown','wheel','vibration','flutter'],
    answer: 'Proper tension eliminates blade flutter and produces straight cuts. The "flutter test": spin the blade with power off, tap the flat of the blade — it should ping, not thud. Most manufacturers under-tension — err toward more tension on wide blades. Tracking (blade centering on the wheels) is adjusted with the upper wheel tilt knob; center the blade on the crown of the rubber tire. Blade guides (above and below the table) control side-to-side movement — set them 1/32" from the blade without touching.',
  },
  {
    id: 'mb-jointer-grain-direction',
    topic: 'Jointer grain direction and tearout prevention',
    keywords: ['jointer','grain','direction','tearout','feed','cutter','head','climb'],
    answer: 'Feed the jointer so the cutter head rotates "into" the wood fibers (not lifting them). Look at the board edge — grain lines that slope down from right to left mean feed right to left. If you get tearout despite correct grain direction, try a shallower depth of cut (1/32" instead of 1/16") or take the final pass with a very sharp, freshly honed hand plane instead. Heavily figured or interlocked grain may never plane cleanly on a jointer — alternate the feed direction and use a hand plane for the final surface.',
  },
  {
    id: 'mb-jointer-snipe',
    topic: 'Jointer snipe and how to avoid it',
    keywords: ['jointer','snipe','dip','end','start','infeed','outfeed','table','set'],
    answer: 'Jointer snipe is a deeper cut at the start or end of a board caused by the board tipping into the cutter head before or after it\'s fully supported. Prevent it by supporting the outfeed end of long boards with a roller stand, and applying downward pressure on the outfeed table (not the infeed) as soon as enough of the board has passed the knives. Add an inch to your rough lengths to sacrifice the sniped ends during final crosscutting.',
  },
  {
    id: 'mb-planer-snipe',
    topic: 'Thickness planer snipe prevention',
    keywords: ['planer','snipe','thick','end','feed','roller','lift','prevent'],
    answer: 'Planer snipe is a slightly deeper cut at the very start and end of a board, caused by the feed rollers releasing the board before the second roller engages it. Minimize it: plane boards slightly longer than needed and cut off the sniped ends. Running multiple boards end-to-end through the planer (snipe only happens at the true first and last board). On some planers, slightly lifting the trailing end of a board while it exits reduces snipe on that end.',
  },
  {
    id: 'mb-drill-press-forstner',
    topic: 'Forstner bits on the drill press',
    keywords: ['forstner','bit','drill','press','flat','bottom','hinge','cup','overlay','speed'],
    answer: 'Forstner bits cut flat-bottomed holes with a clean edge, making them ideal for cup hinge holes (35mm Forstner), shelf pin holes, and dowel holes. Run at the correct speed — large Forstner bits need slow speeds: 1/2" at ~1000 RPM, 1" at ~500 RPM, 1-1/2" at ~250 RPM. Let the bit cool between cuts in hard woods. Back up the exit face with scrap to prevent tearout. A drill press is essential — Forstner bits in a hand drill wander dangerously.',
  },
  {
    id: 'mb-lathe-speeds',
    topic: 'Wood lathe speeds for different diameters',
    keywords: ['lathe','speed','rpm','diameter','turn','faceplate','spindle','safe'],
    answer: 'Lathe speed scales inversely with diameter — larger pieces must spin slower for safe surface speeds. Rough rule: 6,000 ÷ diameter in inches = safe max RPM. A 6" bowl should run no faster than ~1000 RPM; a 1" spindle can run up to 3000+. Start every piece at the lowest speed and listen for vibration or imbalance before increasing. An out-of-balance blank at high speed is extremely dangerous — attach it firmly and check balance before powering up.',
  },
  {
    id: 'mb-lathe-tools',
    topic: 'Wood lathe turning tools and when to use them',
    keywords: ['lathe','gouge','skew','parting','scraper','spindle','bowl','turning','tool'],
    answer: 'Spindle work uses gouges and skew chisels to shape between centers. Bowl gouges have a deep flute for aggressive interior cuts and work from the outside in. Parting tools define shoulders and tenons. Scrapers remove fine amounts but need the edge on-center or below on the rest. Learn the spindle roughing gouge first — it\'s forgiving and fast for cylinders. Never use a spindle roughing gouge on a faceplate — it can catch and be flung dangerously.',
  },
  {
    id: 'mb-lathe-faceplate',
    topic: 'Faceplate turning vs between centers',
    keywords: ['faceplate','chuck','lathe','bowl','between','centers','spindle','attach'],
    answer: 'Between-centers (spindle) turning holds the work on the headstock drive spur and tailstock center — used for table legs, chair rungs, tool handles, and long spindles. Faceplate turning mounts work directly on the headstock for bowls, platters, and hollow forms. A 4-jaw scroll chuck is more versatile than a plain faceplate — it grips a tenon turned on the blank and allows the work to be reversed for finishing the bottom.',
  },
  {
    id: 'mb-scroll-saw-technique',
    topic: 'Scroll saw technique for tight curves',
    keywords: ['scroll','saw','blade','tension','speed','curve','fret','inside','cut'],
    answer: 'Scroll saws use thin blades in a reciprocating frame for intricate curves and inside cuts. Blade tension is critical — too loose and the blade bows in curves; too tight and it breaks. Feed rate must match the curve tightness — slow down for tight turns. For inside cuts (like fretwork letters), drill a blade entry hole, thread the blade through, and reconnect. Stack multiple sheets of thin material with tape to cut identical pieces in one pass.',
  },
  {
    id: 'mb-router-climb-cut',
    topic: 'Router climb cutting risks and when to use it',
    keywords: ['router','climb','cut','direction','pullout','control','profile','edge'],
    answer: 'Climb cutting moves the router in the same direction as the bit rotation — the bit self-propels through the cut, pulling the router forward. It can eliminate tearout on certain grain directions. The danger: the router surges forward suddenly and is extremely hard to control, especially with large bits. Only climb cut on light finishing passes (1/16" or less) on the router table, never on a handheld router. Normal cutting direction (against rotation) is always safer.',
  },
  {
    id: 'mb-router-bit-speeds',
    topic: 'Router bit speeds — larger bits slower',
    keywords: ['router','speed','bit','rpm','large','panel','raiser','safe','sfm'],
    answer: 'Larger router bits must run at lower RPM to keep the rim speed (surface footage) safe. A 1/2" straight bit runs fine at 24,000 RPM. A 3" panel-raising bit should run no faster than 10,000–12,000 RPM — the large diameter means very high rim speed even at moderate RPM. Running large bits too fast creates vibration, burning, and risk of bit failure. Most modern variable-speed routers allow dial-down to 10,000 RPM for large profile bits.',
  },
  {
    id: 'mb-router-table-fence',
    topic: 'Router table fence setup and featherboards',
    keywords: ['router','table','fence','featherboard','split','opening','bit','guard'],
    answer: 'The router table fence halves position on either side of the bit, with an opening no wider than necessary. A featherboard upstream of the bit presses the workpiece against the fence for consistent depth. For profiling, the outfeed fence half must be advanced slightly to compensate for the stock removed — just like a jointer outfeed table. The bit guard sits on the fence to deflect chips and protect fingers from the spinning bit above the table.',
  },
  {
    id: 'mb-router-template',
    topic: 'Template routing for repeat parts',
    keywords: ['template','routing','pattern','flush','trim','bearing','guide','repeat'],
    answer: 'Template routing uses a flush-trim or pattern bit with a bearing that rides against a template. The template is the exact shape you want; the bit reproduces it in the workpiece. Attach the template with double-sided tape, carpet tape, or toggle clamps. For inside curves, you need a pin router or to use the top bearing. Always rough-cut the workpiece close to shape first (within 1/8") to reduce the load on the router bit. Spiral upcut bits leave cleaner edges than straight bits on template work.',
  },
  {
    id: 'mb-jigsaw-tearout',
    topic: 'Jigsaw blade selection and tearout control',
    keywords: ['jigsaw','blade','tearout','reverse','TPI','downstroke','veneer','cut'],
    answer: 'Jigsaw tearout happens on the upstroke because the blade cuts on the upstroke in most jigsaws. To get a clean top surface, place the good face down (tearout appears on the top, which becomes the back). Alternatively use reverse-tooth blades that cut on the downstroke, leaving the visible face clean. Fine-tooth blades (10–12 TPI) produce smoother cuts than coarse blades. Score the cut line with a knife before cutting veneered panels to prevent surface splintering.',
  },
  {
    id: 'mb-circular-saw-technique',
    topic: 'Circular saw technique for straight cuts',
    keywords: ['circular','saw','fence','guide','straight','edge','plunge','cut','rip'],
    answer: 'A circular saw with a good fence guide is nearly as accurate as a track saw for ripping sheet goods. Clamp a straight edge (or factory edge of another plywood sheet) as a guide, account for the offset between the blade and saw base, and run the base against the guide. Keep the saw moving at a consistent feed — stopping causes burning. Always support the off-cut side so the sheet doesn\'t collapse onto the blade as the cut finishes.',
  },
  {
    id: 'mb-track-saw-technique',
    topic: 'Track saw for breaking down sheet goods',
    keywords: ['track','saw','guide','rail','splinter','guard','plunge','sheet','plywood'],
    answer: 'Track saws (like Festool TS55) glide along a guide rail and produce table-saw quality rip cuts in sheet goods on the floor or a workbench. The anti-splinter strip on the rail edge eliminates tearout on the top face. Plunge capability lets you start a cut in the middle of a panel (for sink openings). Tracks can be spliced for long cuts. The main limitation vs a table saw: you bring the tool to the stock, not the stock to the tool — awkward for multiple identical rip cuts.',
  },
  {
    id: 'mb-random-orbit-sander',
    topic: 'Random orbit sander technique',
    keywords: ['random','orbit','sander','swirl','pressure','grit','sequence','cross','scratch'],
    answer: 'Random orbit sanders combine spinning and orbiting motion to eliminate cross-grain scratches — but only if you don\'t press too hard (which defeats the random motion) and don\'t skip grits. Move slowly across the surface (1"/second) and keep the sander flat. Start at 80 or 100 grit for stock removal, then 120, 150, and 180 or 220 before finish. Check your work by raking light across the surface — 80-grit scratches are invisible until the finish magnifies them.',
  },
  {
    id: 'mb-belt-sander-use',
    topic: 'Belt sander for aggressive stock removal',
    keywords: ['belt','sander','aggressive','coarse','flatten','direction','grain','scratch'],
    answer: 'Belt sanders remove stock very fast — they can easily sand through a veneer or create low spots. Use them for initial flattening of glued panels, removing mill marks, and final shaping of thick curved parts. Run parallel to the grain to minimize cross-grain scratches. Apply even, light pressure — the machine\'s weight is enough. Cross-grain belt sanding (at 45°) can flatten bowed panels faster but leaves deep scratches that require additional sanding to remove.',
  },
  {
    id: 'mb-cnc-basics',
    topic: 'CNC router basics for woodworkers',
    keywords: ['cnc','router','g-code','toolpath','bit','depth','pass','feed','rate'],
    answer: 'A CNC router moves a spinning bit in X, Y, and Z axes to cut shapes from CAD files. Key parameters: feed rate (how fast the bit moves), plunge rate (how fast it goes down), and depth per pass (how deep each cutting pass goes). For 3/4" plywood, a 1/4" upcut spiral bit at 100 in/min with 1/4" depth-per-pass is a safe starting point. Upcut bits clear chips well but can tearout the top surface — downcut bits leave clean tops but pack chips in the cut.',
  },
  {
    id: 'mb-cnc-spoilboard',
    topic: 'CNC spoilboard and work holding',
    keywords: ['cnc','spoilboard','mdf','vacuum','clamp','holddown','screw','tabbed'],
    answer: 'The CNC spoilboard is a sacrificial MDF layer between the machine bed and your workpiece — the bit can cut slightly into it without damaging the machine. Resurface the spoilboard flat periodically. Work holding options: screws around the perimeter, double-sided tape, T-nuts in the spoilboard, or vacuum hold-down. For through-cuts in panels, leave tabs (small uncut bridges) to keep the workpiece from shifting; break tabs off after machining.',
  },
  {
    id: 'mb-oscillating-tool',
    topic: 'Oscillating multi-tool for flush cuts and demo',
    keywords: ['oscillating','multi','tool','flush','cut','undercut','door','trim','demo'],
    answer: 'Oscillating multi-tools (Fein, Milwaukee, DeWalt) make flush cuts, undercut door casings, remove old caulk, and trim in tight spaces. For flush-cutting dowels or through tenons, the oscillating saw is safer than a chisel and faster than a hand saw. The blades dull quickly on hardwood — keep spares. For undercutting door casings to fit flooring, a long reach blade with a flat base attachment produces a consistent, accurate undercut.',
  },
  {
    id: 'mb-drill-press-mortise',
    topic: 'Drilling out mortises on the drill press',
    keywords: ['drill','press','mortise','forstner','chisel','clean','efficiency','overlap'],
    answer: 'Drill a series of overlapping Forstner bit holes to rough out a mortise quickly — remove most of the waste by drilling before touching a chisel. Mark the mortise on the layout lines, drill the end holes first, then overlap holes between them. The chisel work is then just cleaning the flat bottom and squaring the corners. A mortise attachment for the drill press guides a square chisel around a drill bit, making perfectly clean mortises in one pass.',
  },
  {
    id: 'mb-router-bit-types',
    topic: 'Router bit types and their uses',
    keywords: ['router','bit','straight','spiral','flush','trim','roundover','cove','rabbet','profile'],
    answer: 'Straight bits cut dados and grooves. Spiral upcut bits clear chips out of the cut for deep grooves. Flush-trim bits have a bearing to follow a template. Roundover and chamfer bits profile edges. Cove bits cut a concave profile. Rabbet bits cut stepped edges for cabinet backs. Profile bits (ogee, roman ogee, classical) produce decorative mouldings. Carbide-tipped bits outlast high-speed steel; solid carbide spiral bits last even longer. Always use 1/2" shank bits in 1/2" collet routers — they run truer and safer.',
  },
  {
    id: 'mb-router-depth-setting',
    topic: 'Setting router bit depth accurately',
    keywords: ['router','depth','set','adjust','rule','block','stack','shim','accurate'],
    answer: 'To set router bit depth without a depth gauge: place the router on a flat surface, lower the bit to the surface, set the depth stop, then back it off the desired depth measurement. A stack of feeler gauges or drill bits can serve as a depth block. For a 1/4" deep dado, use a 1/4" drill bit as a spacer under the depth stop. Fine-adjust plunge routers by loosening the micro-adjust nut, turning, and relocking — each mark on the fine-adjust is typically 1/32".',
  },
  {
    id: 'mb-power-miter-saw',
    topic: 'Miter saw angles for polygons and frames',
    keywords: ['miter','saw','angle','polygon','frame','hexagon','octagon','formula','90'],
    answer: 'Each miter on an n-sided polygon is cut at 90° ÷ n. For a 4-sided frame: 90° ÷ 4 = 22.5° each side (45° total corner). Hexagon: 90° ÷ 6 = 15°. Octagon: 90° ÷ 8 = 11.25°. For a picture frame, a 45° miter is exactly half of 90°. To check: add all the miter angles around the perimeter — they must equal 360°. Cut one test piece of each angle, assemble dry, and check for gaps before cutting good material.',
  },
  {
    id: 'mb-compound-miter',
    topic: 'Compound miter for crown moulding and angle joints',
    keywords: ['compound','miter','crown','angle','bevel','tilt','chart','spring'],
    answer: 'Compound miters set both the miter angle and the saw blade tilt simultaneously — used for cutting crown moulding flat on the saw table and for angled joints in frames. Crown moulding compound angles depend on the spring angle of the moulding. A 38° spring angle needs a 33.9° miter and 31.6° bevel. Charts are available for all common spring angles. Alternatively, stand the crown upside-down against the saw fence at its spring angle and cut a simple 45° miter — easier but requires a taller fence.',
  },

  // ── FINISHING ────────────────────────────────────────────────────────────────
  {
    id: 'mb-surface-prep-sequence',
    topic: 'Surface preparation sequence before finishing',
    keywords: ['surface','prep','sand','scrape','raise','grain','grit','sequence'],
    answer: 'Machine-sanded wood: start at 100 or 120 grit to remove machine marks, then 150, 180, 220. Hand-planed wood: start at 150 or 180 — plane marks are finer than machine marks. Stop at 150 for open-grained porous woods that will get an oil finish; stop at 220 for dense woods or film finishes. Always sand with the grain for the final grit. Remove all dust with a vacuum and tack cloth before applying any finish.',
  },
  {
    id: 'mb-raising-grain',
    topic: 'Raising the grain before water-based finishes',
    keywords: ['raise','grain','water','based','whisker','sand','220','between'],
    answer: 'Water raises wood grain — any water-based finish will create a rough surface on the first coat even on well-sanded wood. To prevent this, wet the wood with clean water, let it dry completely, then sand lightly with 220 grit to knock down the raised whiskers. The first coat of finish will then go on and dry smooth. Subsequent coats also need 320-grit scuff sanding between coats to remove dust nibs and maintain a flat surface.',
  },
  {
    id: 'mb-dewaxed-shellac',
    topic: 'Dewaxed vs waxed shellac',
    keywords: ['shellac','dewaxed','waxed','seal','topcoat','compatibility','blonde','amber'],
    answer: 'Shellac contains natural wax. Dewaxed shellac has the wax removed and can be used as a sealer under any topcoat — it bonds to everything and everything bonds to it. Waxed shellac has the wax retained; subsequent coats of oil-based finishes may not adhere well over it. Zinsser SealCoat is a premixed dewaxed shellac. Blonde shellac gives minimal color; orange/amber adds warmth. Mix your own from dry flakes for fresher, longer-lasting finish than pre-mixed products.',
  },
  {
    id: 'mb-shellac-mixing',
    topic: 'Mixing shellac flakes — cut and shelf life',
    keywords: ['shellac','flake','mix','cut','pound','alcohol','ratio','shelf','fresh'],
    answer: 'Shellac cut is the ratio of dry flakes (in pounds) to alcohol (in gallons). A 2-lb cut means 2 lbs of flakes dissolved in 1 gallon of denatured alcohol. For brushing, a 2-lb cut is standard. For wiping on thin coats, a 1-lb cut works better. Mix only what you\'ll use in a few months — shellac in solution has a shelf life of 6 months to 1 year. Old shellac won\'t dry hard. Always check the shellac "sell by" or mix date; fresh shellac dries in 30 minutes.',
  },
  {
    id: 'mb-boiled-linseed-oil',
    topic: 'Boiled linseed oil — properties and safety',
    keywords: ['boiled','linseed','oil','blo','dry','time','rag','fire','penetrating','finish'],
    answer: 'Boiled linseed oil (BLO) penetrates wood fibers and hardens through oxidation, providing some protection and bringing out grain figure. It dries slowly (24–48 hrs per coat) and produces a matte, low-sheen finish. BLO-soaked rags are a serious spontaneous combustion hazard — spread them flat outside to dry completely before disposal. BLO builds finish slowly (6–10 coats for meaningful protection) and produces a softer finish than varnish or poly; it\'s better as a base treatment than a sole finish.',
  },
  {
    id: 'mb-danish-oil-properties',
    topic: 'Danish oil — what is it and best uses',
    keywords: ['danish','oil','wiping','varnish','blend','easy','beginner','penetrating'],
    answer: 'Danish oil is a proprietary blend of oil and varnish — it penetrates like an oil but builds a thin film like varnish. The exact formula varies by brand. It\'s one of the easiest finishes to apply — wipe on, let soak, wipe off excess. 3–4 coats provide moderate protection. It\'s not as durable as polyurethane but is much more forgiving to apply. Danish oil is a good first finish for beginners and is ideal for carved pieces where brush application is difficult.',
  },
  {
    id: 'mb-tung-oil',
    topic: 'Pure tung oil vs tung oil finish products',
    keywords: ['tung','oil','pure','finish','mineral','spirit','diluted','blo','compare'],
    answer: 'Pure tung oil (from the tung nut) is a slow-drying penetrating finish harder than linseed oil when fully cured. Most "tung oil finish" products at the hardware store contain little or no actual tung oil — they\'re diluted alkyd varnish. Pure tung oil requires multiple coats and takes days to cure. It\'s naturally food-safe when cured. For a genuine tung oil look, Waterlox and pure tung oil from specialty suppliers are the real products — read labels carefully.',
  },
  {
    id: 'mb-hardwax-oil',
    topic: 'Hardwax oil finish for floors and furniture',
    keywords: ['hardwax','oil','osmo','rubio','floor','furniture','matte','repair','easy'],
    answer: 'Hardwax oil (brands: Osmo Polyx, Rubio Monocoat) combines penetrating oil with natural waxes — it soaks in and hardens to leave a flat, natural-looking surface. It\'s very popular for floors and modern furniture. Apply thin — a very thin coat is far more effective than a thick one, which stays sticky. One or two coats is sufficient. Spot repairs are possible by reapplying locally without refinishing the whole surface, which is a major advantage over film finishes.',
  },
  {
    id: 'mb-nitro-lacquer',
    topic: 'Nitrocellulose lacquer — pros and cons',
    keywords: ['nitrocellulose','lacquer','spray','guitar','fast','dry','brittle','amber'],
    answer: 'Nitrocellulose lacquer sprays beautifully, dries in minutes, and is the traditional finish for guitars and vintage furniture. It\'s reversible — new coats bond chemically to old ones, making repairs seamless. Downsides: it\'s flammable and requires excellent ventilation, it yellows amber over time, and it\'s not very durable (chips and crazes). Modern CAB-acrylic lacquers are clearer (less amber) and slightly tougher. Both are spray-only for best results — brushing lacquer has retarders added but is still fast.',
  },
  {
    id: 'mb-conversion-varnish',
    topic: 'Conversion varnish for commercial durability',
    keywords: ['conversion','varnish','catalyzed','acid','cure','hardener','durable','spray'],
    answer: 'Conversion varnish (catalyzed varnish) is a two-component finish mixed with an acid catalyst — it cross-links to a very hard film that resists water, solvents, and abrasion far better than oil-based poly. It\'s the standard finish in commercial cabinet shops. You must spray it (brushing rarely works). Pot life is limited (8–48 hours after mixing). The catalyst is hazardous — wear full respirator and gloves. Once cured, conversion varnish is exceptionally durable.',
  },
  {
    id: 'mb-wiping-varnish',
    topic: 'Wiping varnish — easy film finish for amateurs',
    keywords: ['wiping','varnish','diluted','poly','danish','oil','wipe','thin','coat'],
    answer: 'Wiping varnish is oil-based varnish diluted 50% with mineral spirits — thin enough to wipe on and off like an oil but builds a real varnish film over multiple coats. It\'s forgiving: no runs, no brush marks. Apply with a lint-free cloth, wipe off excess after 5 minutes, let cure overnight, sand lightly with 320 grit, and repeat 4–6 times. The result is a thin, satin varnish film with an "in the wood" look. You can make your own by thinning any oil-based poly.',
  },
  {
    id: 'mb-waterbased-poly',
    topic: 'Water-based polyurethane application tips',
    keywords: ['water','based','polyurethane','poly','brush','bubbles','fast','dry','grain'],
    answer: 'Water-based poly dries in 2 hours vs 8 for oil-based, which is convenient — but the fast dry time creates problems. Don\'t overbrush or you\'ll drag up previous coats. Apply with a good synthetic bristle brush in long, even strokes. Bubbles: apply thinner coats, use a foam brush, or add a few drops of Floetrol to extend open time. Water-based poly raises grain on the first coat — sand 220 grit between coats. The finish is very clear (no amber), making it ideal over light woods and stains.',
  },
  {
    id: 'mb-oil-based-poly',
    topic: 'Oil-based polyurethane for durability and warmth',
    keywords: ['oil','based','polyurethane','amber','warm','durable','brush','dry','slow'],
    answer: 'Oil-based polyurethane adds a warm amber glow — enhancing walnut and cherry beautifully — and is more durable than water-based formulas. Dry time is 8–12 hours between coats; full cure takes 30 days. Apply with a good quality natural bristle brush; synthetic brushes streak. Thin the first coat 10–15% with mineral spirits for better penetration. Three coats with 320-grit sanding between produces an excellent surface. Best avoided on very light woods (maple, ash) where amber tinting is unwanted.',
  },
  {
    id: 'mb-spray-finishing',
    topic: 'Spray finishing basics — HVLP vs airless',
    keywords: ['spray','finish','hvlp','airless','gun','pressure','viscosity','tip','atomize'],
    answer: 'HVLP (High Volume, Low Pressure) guns atomize finish at low air pressure, producing fine droplets with minimal overspray — ideal for furniture. Airless sprayers use high pressure with no air — faster for large surfaces but harder to dial in for furniture finishes. Thin the finish to the right viscosity (test with a viscosity cup — water-thin for HVLP, slightly thicker for airless). Hold the gun 6–8" from the surface, move in even passes at 1 ft/sec, 50% overlap between passes.',
  },
  {
    id: 'mb-fisheye-finish',
    topic: 'Fisheye in finish — causes and fix',
    keywords: ['fisheye','finish','silicone','contamination','oil','repel','crater','repair'],
    answer: 'Fisheye appears as craters or circular repelled areas in finish — caused by silicone contamination (from furniture polish, aerosol lubricants, or hand lotion). The finish can\'t wet the contaminated surface. Fix: let dry completely, wash the surface with naphtha or mineral spirits, sand 220, apply a sealer coat with fisheye eliminator additive, then topcoat. Prevention: ban silicone products from your finishing area. Even tiny amounts of silicone in the air can contaminate bare wood.',
  },
  {
    id: 'mb-blush-lacquer',
    topic: 'Blush in lacquer — causes and fix',
    keywords: ['blush','lacquer','milky','humid','white','moisture','trapped','fix'],
    answer: 'Blush is a milky white haze in lacquer caused by moisture trapped in the film as it dries — usually occurs in high humidity. Fix: add retarder (lacquer retarder or slow thinner) to slow the drying, allowing moisture to escape before the film skins over. Alternatively, spray in lower humidity or heat the shop slightly. A mild blush sometimes clears as the lacquer fully cures over days. Severe blush must be sanded off and recoated.',
  },
  {
    id: 'mb-orange-peel-finish',
    topic: 'Orange peel in sprayed finish — causes and fix',
    keywords: ['orange','peel','texture','atomize','spray','pressure','thin','rub','out'],
    answer: 'Orange peel is a dimpled texture in sprayed finish resembling citrus skin — caused by poor atomization (pressure too low), finish too thick (needs thinning), or too-fast drying (gun too close). Fix the application: increase air pressure, thin the finish slightly, or slow the movement. If it\'s already cured, wet-sand with 400–600 grit and rub out with polishing compound. On fine furniture, flatting and buffing out orange peel is a normal step in achieving a glass finish.',
  },
  {
    id: 'mb-runs-drips-finish',
    topic: 'Runs and drips in finish — prevention and repair',
    keywords: ['run','drip','sag','finish','thick','coat','brush','spray','fix','sand'],
    answer: 'Runs happen when too much finish is applied at once — gravity pulls the excess down before it skins over. Prevention: apply thin coats, brush only up-and-down on vertical surfaces, keep edges moving. For fresh runs, brush them out immediately with a dry brush. For cured runs: let the finish fully harden, then sand flat with 400 grit wrapped around a hard block, feather into surrounding finish, and recoat. On brush finishes, keep a wet-edge and never go back over partially dried finish.',
  },
  {
    id: 'mb-dye-stain',
    topic: 'Dyes vs pigment stains for wood color',
    keywords: ['dye','pigment','stain','transparent','pop','figure','opaque','NGR','color'],
    answer: 'Dyes penetrate wood fibers and produce transparent, vivid color — they accentuate figure because the dye goes deeper into the pores. Pigment stains sit on the surface and in the pores, partially obscuring figure while providing more opaque color. Use dyes when you want to enhance figure; use pigment stains when you want more uniform, opaque color. NGR (non-grain-raising) dyes use alcohol carriers and don\'t raise grain. Mix dyes in water to raise grain, let dry, sand, then apply a second dye coat for best penetration.',
  },
  {
    id: 'mb-gel-stain',
    topic: 'Gel stain for blotch-prone woods',
    keywords: ['gel','stain','pine','birch','blotch','even','thick','apply','wipe'],
    answer: 'Gel stain is thick — it sits on the surface rather than penetrating, which is exactly why it works on blotchy woods (pine, cherry, birch, maple). The thick gel can\'t penetrate unevenly because it doesn\'t penetrate much at all. Apply generously, work into the grain, and wipe off excess. Build color slowly with multiple thin coats. Gel stain is harder to apply on vertical surfaces (it sags) and inside corners (it pools). It\'s the go-to for a cherry-look on pine or cherry without conditioner.',
  },
  {
    id: 'mb-wash-coat',
    topic: 'Wash coat to control stain penetration',
    keywords: ['wash','coat','shellac','thin','seal','stain','blotch','pine','control'],
    answer: 'A wash coat is a very diluted finish (typically 1-lb cut shellac or 10% oil-based poly in mineral spirits) that partially seals the wood surface to control stain penetration. On blotch-prone woods, it limits how much stain soaks in, preventing the dark/light mottling. Apply it after raising the grain and final sanding, let dry, then apply stain on top. The wash coat also works as a de-nibbing coat under veneer to prevent sand-through.',
  },
  {
    id: 'mb-toning',
    topic: 'Toning finishes to even out color',
    keywords: ['toning','color','shellac','spray','unify','blend','panel','even'],
    answer: 'Toning adds color to the finish itself (rather than the wood) by dissolving dye or pigment into the topcoat. Sprayed toner can unify color variation between boards in a panel, blend sapwood to heartwood, or add subtle color without the blotchy risk of direct staining. Apply toner in light passes — too much obscures the grain figure. A toned finish looks best when you can still see the wood texture clearly.',
  },
  {
    id: 'mb-glazing',
    topic: 'Glazing for antique and distressed finishes',
    keywords: ['glaze','antique','distress','gel','pigment','highlight','shadow','dark','brush'],
    answer: 'Glazing applies a translucent pigmented layer between coats of finish to add depth, highlight carvings, and create aged effects. Apply glaze over a sealed surface, work it into profiles and corners with a brush, then wipe back the flats to leave color only in recesses. Seal with a topcoat when dry. The "dirty" look in raised panel doors and carved furniture often comes from brown or black glaze pushed into the corners and profiles.',
  },
  {
    id: 'mb-rubbing-out',
    topic: 'Rubbing out a finish to a gloss or satin sheen',
    keywords: ['rub','out','finish','gloss','satin','pumice','rottenstone','compound','flat'],
    answer: 'Rubbing out flattens the final topcoat to a perfectly even sheen — from the same gloss finish you can produce matte, satin, or high gloss depending on how you rub it. Let the finish cure hard (2–4 weeks for oil-based). Wet-sand with 400, 600, 800 grit paper using soapy water. Follow with automotive rubbing compound on a foam pad. Finish with polishing compound for glass-smooth high gloss. Mineral spirits and 0000 steel wool produce satin; automotive compound produces gloss.',
  },
  {
    id: 'mb-paste-wax-topcoat',
    topic: 'Paste wax as a topcoat and between coats',
    keywords: ['paste','wax','topcoat','buff','johnson','renaissance','carnauba','final'],
    answer: 'Paste wax (Johnson\'s, Briwax, Renaissance Wax) applied over a cured hard finish adds a soft sheen and a sacrificial protective layer that can be renewed without stripping. It\'s NOT a primary finish — wax alone offers very little protection. Apply thin, let haze, buff with a cloth or rotary buffer. On furniture, rewax annually in high-wear areas. Carnauba wax is harder and more heat-resistant; beeswax is softer and more natural-looking. Don\'t apply wax if you intend to apply more finish coats — wax prevents adhesion.',
  },
  {
    id: 'mb-between-coats-sanding',
    topic: 'Between-coat sanding for film finishes',
    keywords: ['between','coat','sand','320','scuff','adhesion','nib','flat','smooth'],
    answer: 'Light sanding between finish coats removes dust nibs, levels brush marks, and improves adhesion for the next coat. Use 320 or 400 grit — you\'re just scuffing, not removing the finish. The surface should be uniformly dull after scuffing; shiny spots mean you missed them. Remove all dust before recoating. Don\'t sand between coats of lacquer (it bonds chemically); do sand between coats of varnish, poly, and waterborne finishes that rely on mechanical adhesion between coats.',
  },
  {
    id: 'mb-finish-compatibility',
    topic: 'Finish compatibility — what can go over what',
    keywords: ['compatibility','finish','layer','over','poly','shellac','lacquer','oil','order'],
    answer: 'General rule: oil first (if any), then shellac as sealer, then any topcoat. Shellac goes over everything and everything goes over shellac. Oil-based finishes go over oil, shellac, or oil-based varnish. Water-based finishes go over water-based or dewaxed shellac (not over oil or waxed shellac without testing first). Never apply lacquer over an oil-based sealer — it wrinkles. Never apply polyurethane over pure oil that hasn\'t fully cured — it stays soft for months.',
  },
  {
    id: 'mb-milk-paint-finishing',
    topic: 'Milk paint and chalk paint for furniture',
    keywords: ['milk','chalk','paint','flat','matte','distress','wax','seal','furniture'],
    answer: 'Milk paint (real or modern) produces a very flat, porous surface with an antique look. Real milk paint bonds permanently to bare wood and is hard to remove; modern milk paint can be used over existing finishes. Apply in thin coats — it dries fast (30 minutes). Seal with wax (traditional) or oil for a natural finish. Chalk paint (Annie Sloan style) is similar but bonds to nearly any surface. Both can be sanded, distressed, and dry-brushed to create aged furniture effects.',
  },
  {
    id: 'mb-finish-outdoor',
    topic: 'Finishing outdoor wood furniture',
    keywords: ['outdoor','exterior','finish','teak','oil','spar','varnish','uv','weather'],
    answer: 'Outdoor furniture needs UV protection and water resistance. Options: spar varnish (flexible, UV-resistant alkyd), penetrating teak oil (needs reapplication every year), exterior water-based poly (2–3 season life), or epoxy prime with spar topcoat (longest lasting). Any outdoor film finish will eventually peel — penetrating finishes are easier to maintain because they don\'t peel. Reapply penetrating finishes before the wood weathers to gray and starts to check.',
  },

  // ── GLUE & ADHESIVES ─────────────────────────────────────────────────────────
  {
    id: 'mb-titebond-types-comparison',
    topic: 'Titebond I, II, and III in-depth comparison',
    keywords: ['titebond','1','2','3','waterproof','type','outdoor','I','II','III'],
    answer: 'Titebond I (original) has the longest open time (~5 min) and makes the strongest joints in pure wood-to-wood tests. It fails at about 150°F so it\'s not for objects near heat. Titebond II is water-resistant (Type II ANSI) — fine for occasional moisture but not submersion; the slight difference from Type I rarely matters. Titebond III is fully waterproof (Type III ANSI) but has shorter open time and slightly lower dry-strength than I. For furniture, Titebond I or II is ideal. Use III only when genuine waterproofing is required.',
  },
  {
    id: 'mb-hide-glue-hot',
    topic: 'Hot hide glue — preparation and use',
    keywords: ['hot','hide','glue','pot','protein','reversible','temperature','gram','bloom'],
    answer: 'Hot hide glue (rabbit skin or pearl) must be dissolved in water and heated to 140–145°F in a double boiler. Too hot degrades it; too cool it gels on contact. Bloom strength (192–251 gram bloom) affects assembly time — higher bloom = shorter working time. Apply quickly to both surfaces, assemble and clamp within 30–60 seconds. Hot hide glue is the traditional choice for antique furniture because it\'s reversible with heat and water — invaluable for instruments and heirloom pieces that will need future repair.',
  },
  {
    id: 'mb-liquid-hide-glue',
    topic: 'Liquid hide glue convenience and tradeoffs',
    keywords: ['liquid','hide','glue','old','brown','convenient','open','time','reversible'],
    answer: 'Liquid hide glue (like Old Brown Glue) contains a urea or glycerin retarder that keeps it liquid at room temperature — no heating required. Open time is much longer than hot hide glue (15–20 minutes). It\'s still reversible with heat and water. Strength is slightly lower than hot hide glue, and it has a shelf life of about 1 year after opening. Ideal for repairs, instrument building, and anyone who wants the advantages of hide glue without the glue pot and timing pressure.',
  },
  {
    id: 'mb-epoxy-types',
    topic: 'Slow vs fast curing epoxy — when to use each',
    keywords: ['epoxy','slow','fast','cure','five','minute','gap','fill','potlife','thick'],
    answer: '5-minute epoxy cures fast but is brittle, has minimal penetration, and provides a weaker bond than slower epoxies. Use it only for quick fixes that won\'t be stressed. Slow-cure epoxy (30 min to 2 hr pot life) penetrates better, cures harder, and fills gaps more reliably. For gap-filling on end grain or porous woods, thin slow-cure epoxy slightly with its own solvent for better penetration. West System and System Three are quality boat-grade epoxies that work well in furniture applications.',
  },
  {
    id: 'mb-ca-glue-types',
    topic: 'CA glue viscosities — thin, medium, thick',
    keywords: ['CA','cyanoacrylate','thin','medium','thick','gap','penetrate','accelerator','second'],
    answer: 'CA (cyanoacrylate) glue comes in three viscosities. Thin CA is water-like — it wicks into tight joints by capillary action and is great for closing splits and stabilizing loose joints. Medium CA is the general-purpose type — workable for most gluing tasks. Thick CA (gel) fills gaps and is ideal for porous surfaces or larger gaps. Accelerator (kicker) speeds any CA to instant cure — useful for one-sided applications. CA joints are very brittle under impact — don\'t rely on CA for structural furniture joints.',
  },
  {
    id: 'mb-polyurethane-glue',
    topic: 'Polyurethane glue — expansion and cleanup',
    keywords: ['polyurethane','glue','gorilla','expand','foam','water','activate','cleanup'],
    answer: 'Polyurethane glue (Gorilla Glue, PL Premium) cures by reacting with moisture — slightly dampen one surface before assembly. It foams and expands as it cures, filling gaps but also creating ugly brown foam squeeze-out that\'s hard to clean. Let foam squeeze-out fully cure (rock hard), then chisel or scrape it off. Polyurethane glue is excellent for bonding dissimilar materials (wood to metal, plastic, masonry) but offers no advantage over PVA for standard wood-to-wood gluing.',
  },
  {
    id: 'mb-contact-cement-types',
    topic: 'Contact cement — solvent vs water based',
    keywords: ['contact','cement','solvent','water','laminate','veneer','formica','toxic'],
    answer: 'Solvent-based contact cement is stronger, more waterproof, and bonds faster than water-based. It\'s extremely flammable and toxic — only use it with excellent ventilation, no open flames. Water-based contact cement is safer and lower-odor but requires longer dry time and slightly less aggressive initial bond. Both work by coating both surfaces, letting dry until not tacky, then pressing together for an instant permanent bond. Bond is immediate on contact — position pieces carefully before pressing.',
  },
  {
    id: 'mb-open-time-strategy',
    topic: 'Managing glue open time during complex glue-ups',
    keywords: ['open','time','glue','complex','slow','batch','temperature','cold','rush'],
    answer: 'A complex glue-up with many joints can exhaust your glue open time before all joints are assembled and clamped. Strategies: rehearse the assembly dry with clamps already staged, use slow-setting PVA (Titebond Extend has 8+ min open time), use hot hide glue then add hot water to buy time, or break the assembly into sub-assemblies glued in stages. Cold temperatures (50–60°F) extend open time significantly. Never rush a glue-up — a joint that closes 30 seconds too late will have a glue-starved joint.',
  },
  {
    id: 'mb-clamping-pressure',
    topic: 'Correct clamping pressure for glue joints',
    keywords: ['clamp','pressure','squeeze','out','gap','too','much','too','little'],
    answer: 'The right clamping pressure produces a thin, continuous bead of squeeze-out along the entire joint — this confirms full coverage and sufficient pressure. Too little pressure leaves gaps. Too much pressure starves the joint by squeezing all the glue out (a "starved joint" is stronger than it looks but weaker than optimal). For PVA, you don\'t need massive force — 100–150 psi is fine for most joints. More clamps applying light pressure beats fewer clamps applying excessive force.',
  },
  {
    id: 'mb-squeeze-out-cleanup',
    topic: 'Cleaning up glue squeeze-out timing',
    keywords: ['squeeze','out','cleanup','timing','wet','rubbery','stain','finish'],
    answer: 'Timing glue cleanup matters. Wet cleanup with a damp cloth spreads diluted glue into the grain — invisible now, but it blocks stain and finish later. Better: let squeeze-out harden to a rubbery gel (30–45 min for PVA) then peel or slice it off cleanly with a chisel. For interior corners, a glue chisel (or a sharpened stick) gets into the corner. Any glue residue in the grain will show as a lighter spot under stain — check with naphtha before finishing.',
  },
  {
    id: 'mb-gap-filling-glue',
    topic: 'Gap filling in wood joinery — best approaches',
    keywords: ['gap','fill','joint','sawdust','epoxy','glue','filler','structural','cosmetic'],
    answer: 'Structural gaps in load-bearing joints need real solutions — wood shims, re-cutting, or epoxy fills only (not sawdust fillers). Cosmetic gaps on exterior surfaces can be filled with colored epoxy, walnut wood filler, or the wood\'s own sawdust mixed with CA glue. Sawdust-and-CA filler matches the color closely but sands differently and may resist finish. Pre-mixed wood fillers (Timbermate, Famowood) sand and take finish better. Color-match the filler to the finished wood, not the raw wood.',
  },
  {
    id: 'mb-glue-temp-requirements',
    topic: 'Temperature requirements for wood glue',
    keywords: ['temperature','cold','freeze','glue','apply','shop','winter','minimum'],
    answer: 'Most PVA wood glues require minimum application temperature of 50–55°F for the glue itself AND the wood. Cold glue is thick and doesn\'t penetrate well. Cold wood causes glue to chill too quickly before it can form a proper bond. PVA that has frozen is permanently ruined — shake it; if it separates, discard it. In cold shops, bring glue inside overnight and use it at room temperature even if the shop is cold — the working time drops but the bond is better than applying cold glue to cold wood.',
  },
  {
    id: 'mb-glue-reversibility',
    topic: 'Reversible vs permanent adhesives for antiques and instruments',
    keywords: ['reversible','hide','glue','repair','antique','instrument','epoxy','permanent'],
    answer: 'For antique furniture and musical instruments that will need future repair, use reversible adhesives — hide glue (hot or liquid) is the classic choice. It releases with heat (120–140°F) and moisture. PVA can sometimes be released with steam but often tears wood fibers. Epoxy, cyanoacrylate, and polyurethane are essentially permanent — joints can be broken but the surfaces are damaged. Using epoxy on a valuable antique makes all future repairs far harder.',
  },
  {
    id: 'mb-rubbed-joint',
    topic: 'Rubbed butt joint without clamps',
    keywords: ['rubbed','joint','rub','flat','hide','glue','clamp','less','veneer'],
    answer: 'A rubbed joint applies hide glue to both flat surfaces, then slides them against each other while pressing firmly. The heat from friction activates the glue and the molecular contact creates a strong bond without clamps. It works on perfectly flat mating surfaces — any gap prevents contact and the joint fails. This technique is used for attaching veneers, building up tabletops from narrow boards, and joining thin cabinet back panels. Modern PVA doesn\'t work well for rubbed joints — use hot hide glue.',
  },
];
