import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_C: KnowledgeEntry[] = [
  // ── FASTENERS & HARDWARE ─────────────────────────────────────────────────────
  {
    id: 'mc-wood-screw-thread',
    topic: 'Wood screw thread types — coarse vs fine',
    keywords: ['screw','coarse','fine','thread','type','holding','grain','sheet','solid'],
    answer: 'Coarse-thread screws have wider, deeper threads that cut aggressively into solid wood and softwood — better holding power in face grain. Fine-thread screws suit hardwood and machine applications. Self-tapping screws have a sharp point that cuts without a pilot hole in softwood. For solid hardwood, always pre-drill to avoid splitting — the clearance hole should match the shank diameter and the pilot hole match the core diameter.',
  },
  {
    id: 'mc-pilot-hole-size',
    topic: 'Pilot hole sizing for wood screws',
    keywords: ['pilot','hole','clearance','size','bit','screw','chart','hardwood','split'],
    answer: 'The pilot hole drill bit should match the screw\'s root (core) diameter — the solid metal between the threads. The shank clearance hole (in the top board) matches the full shank diameter so the screw can pull the boards together. A common guide: for #8 screws, use a 5/64" bit for softwood pilot, 7/64" for hardwood pilot, and 11/64" for the clearance hole. If in doubt, drill a test hole in scrap — the screw should drive in with moderate hand pressure but not spin freely.',
  },
  {
    id: 'mc-countersink-counterbore',
    topic: 'Countersink vs counterbore differences',
    keywords: ['countersink','counterbore','flat','oval','head','plug','flush','recessed'],
    answer: 'A countersink creates a conical recess for flat-head or oval-head screws that sit flush with the surface. A counterbore creates a cylindrical pocket deep enough to accept the whole screw head below the surface, leaving room for a wood plug. Counterbores are used when you want to conceal the screw entirely. Combination drill-and-countersink bits do both the pilot hole and countersink in one step — very convenient for face frames and cabinet assembly.',
  },
  {
    id: 'mc-wood-plug-hiding',
    topic: 'Hiding screw heads with wood plugs',
    keywords: ['plug','screw','hide','counterbore','match','grain','sand','flush'],
    answer: 'Counterbore the screw hole, drive the screw, cut a plug with a plug cutter from the same board (matching grain direction and figure), glue it in with the grain aligned, and sand flush after the glue cures. The plug will be nearly invisible if grain and color match. For a deliberate decorative plug, use contrasting wood (walnut plugs in maple). Plugs aligned with the grain disappear; plugs with end grain showing or cross-grain don\'t — always orient them correctly.',
  },
  {
    id: 'mc-pocket-screw-length',
    topic: 'Pocket screw length selection by material thickness',
    keywords: ['pocket','screw','length','thickness','chart','3/4','1/2','1.5','kreg'],
    answer: 'Pocket screw length must be calibrated to the material thickness — too short and it won\'t reach the mating piece; too long and it blows through. Kreg\'s guide: 3/4" material uses a 1-1/4" screw; 1" material uses a 1-1/2" screw; 1-1/2" material uses a 2-1/2" screw. Fine-thread screws for hardwood; coarse-thread for softwood and sheet goods. Always set the pocket hole jig\'s depth collar to match the material thickness or the screw will be angled incorrectly.',
  },
  {
    id: 'mc-structural-screw',
    topic: 'Structural screws for heavy connections',
    keywords: ['structural','screw','simpson','sdw','grip','rite','heavy','lag','load'],
    answer: 'Structural screws (GRK, Simpson SDS, FastenMaster HeadLOK) are engineered fasteners with greater shear and withdrawal values than standard construction screws. They self-countersink, don\'t need pilot holes in most applications, and are rated for structural connections. Use them for stair stringers, deck ledgers, beam-to-post connections, and workbench assembly. They\'re far faster to install than lag bolts (no pre-drilling required) and often stronger for the same size.',
  },
  {
    id: 'mc-european-hinge-adjustment',
    topic: 'European cup hinge adjustment — in, out, up, down',
    keywords: ['european','hinge','cup','adjust','side','height','depth','overlay','inset'],
    answer: 'European (cup) hinges have three adjustments. Side-to-side: the lateral screw moves the door left or right within the opening — typically ±2mm. Up and down: sliding the hinge on the mounting plate slot. In and out (depth): moves the door toward or away from the case face — adjusts the gap reveal. Make adjustments with the door hung — one screw at a time. Most hinges can be adjusted without removing the door. Set all hinges to have even reveals (gaps) all around the door.',
  },
  {
    id: 'mc-hinge-cup-sizes',
    topic: 'Cup hinge cup size and overlay type',
    keywords: ['cup','hinge','35mm','26mm','overlay','full','half','inset','boring'],
    answer: 'Standard European cup hinges use a 35mm cup bored 13mm deep into the door back. Smaller 26mm cups exist for thin cabinet doors. Overlay type determines how much of the face frame the door covers: full overlay covers almost all of the case side; half overlay is used on interior partitions where two doors share a divider; inset hinges require a door that fits inside the face frame opening. Choose overlay type first when ordering hinges — it determines the hinge arm geometry.',
  },
  {
    id: 'mc-drawer-slide-types',
    topic: 'Drawer slide types — undermount vs side mount',
    keywords: ['drawer','slide','undermount','side','mount','soft','close','full','extension'],
    answer: 'Side-mount slides attach to the side of the drawer box and the cabinet side — simple to install, widely available. Undermount slides attach to the drawer bottom and clip under the front of the drawer — completely hidden in the closed position for a clean look. Full-extension slides allow the drawer to extend completely out of the cabinet for full access. Soft-close slides use a dampened mechanism to close silently in the last inch. Undermount slides with soft close are the current industry standard for quality kitchens.',
  },
  {
    id: 'mc-figure-8-table-clip',
    topic: 'Table clips and figure-8 fasteners for tops',
    keywords: ['figure','8','table','clip','Z','clip','movement','allowance','slot','seasonal'],
    answer: 'Figure-8 fasteners, Z-clips, and tabletop clips attach a solid wood top to an apron while allowing seasonal movement. They sit in a slot or rabbet in the apron, with one tab screwed to the top. As the top expands and contracts, the clip slides or pivots in the slot. Never screw a solid wood top rigidly in multiple places along the grain — it will crack at the joints or buckle. Space fasteners 8–10" apart; elongate slots perpendicular to the grain direction for maximum movement.',
  },
  {
    id: 'mc-shelf-pins',
    topic: 'Shelf pin hole systems and 32mm spacing',
    keywords: ['shelf','pin','hole','32mm','system','spacing','jig','drill','cabinet'],
    answer: 'The 32mm system spaces shelf pin holes exactly 32mm apart in vertical rows — it\'s the European production standard. A 5mm drill bit (for standard shelf pins) is used with a drilling jig. Typically drill two rows on each cabinet side, set in 37mm from the front and back edges. The advantages: holes align perfectly across multiple cabinets, and the shelf pin math simplifies into multiples of 32. Many router-bit and dado-stack jigs produce 32mm spacing automatically.',
  },
  {
    id: 'mc-bed-bolt',
    topic: 'Bed bolts for knock-down bed construction',
    keywords: ['bed','bolt','rail','post','knock','down','assemble','disassemble','strong'],
    answer: 'Bed bolts (barrel nuts) pull bed rails tightly against the headboard and footboard posts for a strong, removable joint. The bolt threads into a barrel nut set in the post, and the bolt head is recessed in the rail end with access through the rail face. Tighten with a box wrench or dedicated bed bolt key. The joint gets tighter the more load the bed carries. Pre-drill the bolt and barrel nut holes with a dedicated jig — alignment is critical for the bolt to thread cleanly.',
  },
  {
    id: 'mc-piano-hinge',
    topic: 'Piano hinge continuous support for lids and boxes',
    keywords: ['piano','hinge','continuous','lid','box','full','length','support','evenly'],
    answer: 'Piano hinges (continuous hinges) run the full length of a lid or door, distributing load evenly along the entire joint. They prevent warping in thin lid material by fully supporting the entire edge. Cut piano hinge to length with a hacksaw or snips, and file the cut end smooth. Mortise them flush for a clean look or surface-mount for utility installations. Piano hinges on box lids often need a chain or lid support to keep them from falling flat and breaking off.',
  },
  {
    id: 'mc-magnetic-catch',
    topic: 'Magnetic catches and cabinet door hardware',
    keywords: ['magnetic','catch','door','cabinet','close','hold','latch','strike'],
    answer: 'Magnetic catches use a magnet in the cabinet and a steel strike plate on the door back. The catching strength varies (250g to 2kg) — heavier doors need stronger catches. Position the catch at the top or bottom of the door away from the hinge side for the most leverage. Roller catches (a small roller that snaps over a strike) are an alternative for overlay doors. Touch-latch systems let you open the door by pushing it — useful for handle-free modern cabinets.',
  },
  {
    id: 'mc-drawer-pulls-placement',
    topic: 'Drawer pull placement and consistency',
    keywords: ['drawer','pull','handle','placement','center','consistent','layout','jig'],
    answer: 'Drawer pulls should be placed consistently — centered left-to-right and at a consistent height relative to the drawer front (typically centered top-to-bottom for small drawers, or at the top third for tall drawers). Make a simple drill jig from scrap for consistent hole placement across all drawers. Mark one drawer front carefully and use it as the template. European pulls with two screws must be centered on the hole spacing — note whether it\'s a 96mm, 128mm, or 160mm center-to-center.',
  },
  {
    id: 'mc-knockdown-hardware-types',
    topic: 'Knock-down hardware for flat-pack furniture',
    keywords: ['knock','down','rta','cam','lock','confirmat','minifix','barrel','nut'],
    answer: 'Common knock-down hardware: cam-lock (barrel nut + cam bolt) for panel-to-panel connections; confirmat screws for edge-to-face connections in particleboard; cross-dowels (barrel nuts) with machine bolts for stronger connections in solid wood. All these allow assembly and disassembly without tools damage. The key is accurate hole placement — use a drilling jig or CNC. Assemble and disassemble more than three times and the particleboard core starts to degrade around the holes.',
  },
  {
    id: 'mc-screw-end-grain',
    topic: 'Why screws in end grain fail and alternatives',
    keywords: ['end','grain','screw','hold','weak','cross','dowel','alternative','pocket'],
    answer: 'Screws driven into end grain hold at roughly 40% of the strength compared to face or edge grain — the fibers run parallel to the screw shaft and pull out easily. For stronger end-grain connections, angle the screw toward face grain (toe-nailing), use cross-dowels that bear on face-grain walls, or use epoxy to fill the hole before driving the screw. Pocket hole screws that angle through a face into the end grain of another piece work better than straight end-grain screwing.',
  },

  // ── SHOP MATH & LAYOUT ───────────────────────────────────────────────────────
  {
    id: 'mc-board-feet-formula',
    topic: 'Board feet formula in full detail',
    keywords: ['board','feet','formula','calculate','thickness','width','length','bf'],
    answer: 'Board feet = (T × W × L) ÷ 12, where T is thickness in inches, W is width in inches, and L is length in feet. Example: a 4/4 board (1" thick) × 6" wide × 8 feet long = (1 × 6 × 8) ÷ 12 = 4 board feet. Hardwood lumber is always sold by board foot at the rough thickness — a 4/4 board is roughly 1" rough-sawn. Buy 15–20% extra for waste, defects, and milling loss.',
  },
  {
    id: 'mc-linear-feet-vs-bf',
    topic: 'Linear feet vs board feet — when each applies',
    keywords: ['linear','feet','board','feet','difference','molding','trim','sell','price'],
    answer: 'Linear feet measures only length — used for mouldings, trim, and lumber sold by the running foot. Board feet measures volume (thickness × width × length) — used for dimensional lumber and hardwood. A 1×6×8\' board is 8 linear feet but 4 board feet. When estimating trim, calculate linear feet; when estimating hardwood furniture material, calculate board feet. Big-box stores sell 1×3, 1×4, 1×6 pine by linear feet at a fixed width — hardwood yards price by board foot regardless of width.',
  },
  {
    id: 'mc-sheet-good-yield',
    topic: 'Sheet good yield calculation for cabinet projects',
    keywords: ['sheet','plywood','yield','parts','lay','out','nest','optimize','waste'],
    answer: 'A 4×8 sheet of plywood yields 32 sq ft. Rough rule: a standard base cabinet case uses about 1.5–2 sheets of 3/4". Layout matters — try to orient all grain the same direction and minimize crosscuts. For planning, add 10–15% waste for cutting errors and offcuts. DoveDesign\'s cut list panel shows board feet and sheet counts automatically based on your design. Draw out your cut layout on graph paper for large orders to minimize sheet count before purchasing.',
  },
  {
    id: 'mc-miter-angle-polygons',
    topic: 'Miter angles for polygon frames',
    keywords: ['miter','angle','polygon','formula','hexagon','octagon','pentagon','frame','sides'],
    answer: 'Miter angle per cut = 90° ÷ number of sides. Square (4 sides): 22.5° per cut, 45° total corner. Pentagon (5): 18°. Hexagon (6): 15°. Octagon (8): 11.25°. These are for flat regular polygons. Cut all pieces the same length (short point to short point for miters) to get equal sides. If pieces vary in length, the interior angles still hold but the polygon won\'t close — check all lengths are identical before cutting final material.',
  },
  {
    id: 'mc-taper-calculation',
    topic: 'Calculating taper for furniture legs',
    keywords: ['taper','calculation','leg','width','start','end','length','ratio','formula'],
    answer: 'A tapered leg requires calculating the taper angle or drop per inch of length. Formula: taper per inch = (start width - end width) ÷ length. Example: 2" top, 1" bottom, 28" long = 1" taper ÷ 28" = 0.0357" taper per inch. Set your taper jig to this ratio. For even four-sided tapers, taper two opposite faces first, then rotate 90° and taper the other two — the reference face for the second two cuts is the already-tapered face, not the original.',
  },
  {
    id: 'mc-golden-ratio',
    topic: 'Golden ratio in furniture proportions',
    keywords: ['golden','ratio','phi','proportion','rectangle','furniture','aesthetic','1.618'],
    answer: 'The golden ratio (1:1.618 or φ) describes proportions found aesthetically pleasing across many cultures. For furniture: a table top might be 30"×48.5" (1:1.618), or a bookcase 18" deep × 29" wide (1:1.618). To find the golden ratio for any dimension: multiply by 1.618 for the longer dimension, or divide by 1.618 for the shorter. It\'s a starting point, not a rule — successful furniture design regularly violates it. But when a piece "looks right" and you can\'t say why, the proportions are often close to φ.',
  },
  {
    id: 'mc-rule-of-thirds',
    topic: 'Rule of thirds in cabinet door and panel design',
    keywords: ['rule','thirds','panel','door','proportion','upper','lower','rail','divider'],
    answer: 'The rule of thirds divides a rectangle at 1/3 and 2/3 intervals. For a cabinet door, placing the horizontal rail at the 1/3 point from the top (or bottom) looks more dynamic than centering it. A chest with three drawers looks better with a proportioned height progression (3:4:5 or similar) than equal-height drawers. Divide a wall unit into thirds — tall open section, shorter cabinet section, and base — for visual interest. The rule prevents the monotony of exactly halved proportions.',
  },
  {
    id: 'mc-wood-movement-formula',
    topic: 'Calculating seasonal wood movement',
    keywords: ['movement','formula','percent','species','change','MC','width','calculate'],
    answer: 'Movement = width × (MC change ÷ 100) × species coefficient. Example: 12" wide hard maple panel, moving from 14% MC (summer) to 7% MC (heated winter) = 7% MC change. Maple tangential coefficient ≈ 9.9. Movement = 12 × (7 ÷ 100) × 9.9 = 0.083 inches ≈ 5/64" per foot. A 24" wide maple panel could move almost 3/8" seasonally — that gap must be accounted for in panel float and tabletop attachment. Species coefficients are in every woodworking reference; quartersawn is always about half the tangential value.',
  },
  {
    id: 'mc-dovetail-ratio',
    topic: 'Dovetail angle ratios for hardwood and softwood',
    keywords: ['dovetail','angle','ratio','1:6','1:8','hardwood','softwood','slope','marking'],
    answer: 'The conventional dovetail slope ratio for hardwoods is 1:6 — for every 6 units along the grain, the tail sides splay 1 unit. For softwoods (pine, cedar), use 1:8 — a shallower angle that reduces the risk of short grain snapping off the softwood pins. Steeper angles (1:4 or 1:5) look bold but are weaker. Lay out the ratio geometrically on paper or use a sliding bevel — mark 6 (or 8) units along the baseline and 1 unit up, connect for the slope. Set the bevel to this line and scribe all tails from it.',
  },
  {
    id: 'mc-drawer-height-progression',
    topic: 'Drawer height progression for visual balance',
    keywords: ['drawer','height','progression','series','stack','balance','visual','proportion'],
    answer: 'A stack of identical-height drawers looks static. Use a progression: the top drawer is shortest, with each drawer below slightly taller (arithmetic or geometric progression). Example: 4" / 5" / 6" / 7" or using a 1.15× multiplier between drawers. The heaviest, largest items go in the lowest, tallest drawer — practical and visually weighted to the base. Survey furniture catalogs to internalize proportions that read as "right" before designing your own progression.',
  },
  {
    id: 'mc-diagonal-squaring',
    topic: 'Diagonal measurement for squaring carcases and frames',
    keywords: ['diagonal','square','carcase','frame','measure','equal','check','winding'],
    answer: 'Equal diagonals mean a rectangle is square — measure corner to corner in both directions. If diagonals are equal, the frame is square; if one is longer, push the longer-diagonal corners toward each other while clamping. This works for any rectangle regardless of size. Check before the glue sets — once cured, correcting a racked carcase requires cutting apart joints. On large carcases, a steel tape is accurate enough; for small boxes, use the same diagonal stick both ways.',
  },
  {
    id: 'mc-trammel-points',
    topic: 'Trammel points for large circles and arcs',
    keywords: ['trammel','point','circle','arc','large','radius','mark','layout','stick'],
    answer: 'Trammel points are metal tips clamped to a wooden beam, acting as a large compass for circles and arcs too large for a standard compass. Set the two points the desired radius apart, anchor one point at the center, and scribe the arc with the other. Make your own trammel from a 1×2 strip with a nail at one end and a pencil or knife at the desired radius. Router circle jigs work the same way — pivot nail at center, router at the radius.',
  },
  {
    id: 'mc-compound-angle-chart',
    topic: 'Compound miter angles for splayed boxes and picture frames',
    keywords: ['compound','miter','splay','angle','tilted','bevel','table','saw','tilt'],
    answer: 'Splayed sides (like a planter box or a tray with angled sides) require compound miters — the miter saw tilts in two planes simultaneously. The exact angles depend on both the splay angle and the number of sides. For a 4-sided box with 10° splay: bevel = arctan(cos(45°) × tan(10°)) ≈ 7.1°; miter = arctan(sin(45°) / cos(10°)) ≈ 44.3°. Woodworking apps and compound miter charts provide these values — don\'t calculate by hand. Always cut test pieces in scrap before committing to good material.',
  },
  {
    id: 'mc-percent-waste',
    topic: 'Estimating waste percentage for projects',
    keywords: ['waste','percent','overage','buy','extra','defect','kerf','cut','estimate'],
    answer: 'Buy 15–20% more lumber than your cut list requires to account for defects, bad cuts, and kerf waste. For figured or highly figured lumber, buy 25–30% extra because yields are lower. For sheet goods, buy 10% over the optimized sheet count. For mouldings and trim, buy 10–15% linear feet extra for miter waste and bad cuts. Leftover stock is always useful for test cuts and small projects; running out means a trip back to the lumber yard and risk of not matching color or grain.',
  },
  {
    id: 'mc-pythagorean-woodworking',
    topic: '3-4-5 triangle for checking square in the shop',
    keywords: ['3','4','5','triangle','square','layout','right','angle','pythagorean'],
    answer: 'The 3-4-5 triangle (Pythagorean relationship) creates a perfect right angle: if one leg is 3 units, another is 4 units, and the hypotenuse is 5 units, the corner is exactly 90°. Use any multiples — 6-8-10 or 12-16-20 work equally well. To check a large structure or slab foundation for square, measure 3 feet on one edge, 4 feet on the perpendicular edge, and the diagonal should be exactly 5 feet. For smaller work, any reliable framing square works better.',
  },
  {
    id: 'mc-metric-imperial-convert',
    topic: 'Converting between metric and imperial in woodworking',
    keywords: ['metric','imperial','convert','inch','mm','centimeter','32mm','fraction'],
    answer: '1 inch = 25.4mm exactly. Common conversions: 3/4" = 19mm, 1/2" = 12.7mm, 1/4" = 6.35mm, 1/8" = 3.175mm. The 32mm cabinet system uses: 37mm setback for shelf pins, 16mm panel thickness (5/8"), 18mm (3/4"). Most European hardware is in mm; most US lumber is in fractions of inches. Keep a conversion chart at the bench — mental arithmetic between the two systems is error-prone.',
  },
  {
    id: 'mc-fibonacci-sequence',
    topic: 'Fibonacci sequence in furniture design',
    keywords: ['fibonacci','sequence','golden','proportion','shelf','height','rail','design'],
    answer: 'The Fibonacci sequence (1, 1, 2, 3, 5, 8, 13, 21...) produces proportions that approach the golden ratio. Use consecutive Fibonacci numbers as dimension ratios — 5:8 for a table width to depth, 8:13 for a bookcase height to width, 3:5 for drawer heights in a two-drawer chest. These ratios feel natural and well-proportioned because human visual perception is sensitive to the golden ratio. Use it to set heights, widths, and panel divisions rather than defaulting to round numbers.',
  },

  // ── DESIGN & FURNITURE STYLES ────────────────────────────────────────────────
  {
    id: 'mc-shaker-design',
    topic: 'Shaker style design principles',
    keywords: ['shaker','style','simple','tapered','leg','mortise','tenon','honest','design'],
    answer: 'Shaker furniture is defined by simplicity, honesty of materials, and utility. Features: square or slightly tapered legs (no carving), frame-and-panel construction with mortise-and-tenon joinery, minimal surface decoration, and natural wood finishes (milk paint or linseed oil). Cherry and maple are the most historically accurate species. The aesthetic rejects ornamentation as dishonest — every element must serve a functional purpose. Shaker proportions are usually classic: tall, narrow cabinet doors and simple turned or carved pulls.',
  },
  {
    id: 'mc-arts-crafts-design',
    topic: 'Arts and Crafts furniture design elements',
    keywords: ['arts','crafts','mission','stickley','through','tenon','quartersawn','oak','pegged'],
    answer: 'Arts and Crafts furniture (Mission style) celebrates exposed joinery and structural honesty. Key features: through tenons pegged with ebony or contrasting wood, quartersawn white oak for its ray-fleck figure, wide corbels and stretchers, flat surfaces with minimal moulding, and leather or canvas upholstery. Hardware is hammered copper or hand-forged iron. The style emerged as a reaction to Victorian excess — craftsmanship and material quality are the decoration.',
  },
  {
    id: 'mc-mid-century-design',
    topic: 'Mid-century modern furniture design',
    keywords: ['mid','century','modern','tapered','leg','thin','plywood','organic','1950','1960'],
    answer: 'Mid-century modern (1940s–1960s) features: thin, tapering legs (often angled outward), clean horizontal lines, organic curves on chairs and sofas, extensive use of bent plywood (Eames), teak and walnut as preferred species, and minimal ornamentation. Hardware is often completely hidden. The aesthetic was influenced by post-war optimism and new materials (molded plywood, fiberglass). To achieve the style: thin profiles, light footprint legs, and natural oil finishes rather than heavy polys.',
  },
  {
    id: 'mc-traditional-period-design',
    topic: 'Traditional and period furniture design elements',
    keywords: ['traditional','period','cabriole','ogee','carved','detail','bracket','foot'],
    answer: 'Traditional furniture (Queen Anne, Chippendale, Federal) features cabriole legs with ball-and-claw or pad feet, carved details on crests and aprons, ogee bracket feet on case pieces, broken pediment tops, and rich mahogany or cherry with shellac or varnish finishes. The style emphasizes elaborate detail and visual complexity. Period furniture requires strong carving skills, advanced joinery, and deep knowledge of historical proportions — a demanding but deeply rewarding area of woodworking.',
  },
  {
    id: 'mc-contemporary-mixed-materials',
    topic: 'Contemporary furniture with mixed materials',
    keywords: ['contemporary','mixed','steel','glass','concrete','wood','modern','contrast'],
    answer: 'Contemporary furniture mixes materials expressively — thick walnut slabs on welded steel bases, concrete tabletops on wood frames, glass shelves in wooden cases. The contrast between raw metal or concrete and warm wood is the main aesthetic statement. For woodworkers, the challenge is making clean connections between materials — steel legs bolt to wood through properly sized through-holes with barrel nuts, or the steel is welded to a flat plate that screws to the wood from underneath.',
  },
  {
    id: 'mc-farmhouse-style',
    topic: 'Farmhouse style furniture characteristics',
    keywords: ['farmhouse','rustic','painted','apron','table','bench','knotty','pine','white'],
    answer: 'Farmhouse style embraces imperfection — knotty pine, rough-sawn oak, wide farmhouse tables with breadboard ends, apron tables painted white or gray, and bench seating. Joinery is honest and simple — mortise-and-tenon apron-to-leg connections, visible hardware, and face-frame cabinet construction. Distressing and aging techniques (milk paint chipping, wire brushing, light sanding edges) are common. This style rewards the use of less-than-perfect lumber that would be rejected for fine furniture.',
  },
  {
    id: 'mc-scandinavian-design',
    topic: 'Scandinavian (Scandi) furniture design',
    keywords: ['scandinavian','danish','swedish','nordic','light','simple','beech','functional'],
    answer: 'Scandinavian design combines simple forms with excellent craftsmanship and functional purpose. Features: blonde woods (beech, ash, birch), clean simple profiles, natural finishes (oil, soap, wax — no heavy lacquer), ergonomic attention to human proportions, and modest ornamentation. Danish furniture icons (Hans Wegner, Finn Juhl) use steam-bending for chair backs and complex leg-to-seat angles. The style rewards precision joinery and thoughtful ergonomics over decorative complexity.',
  },
  {
    id: 'mc-cabriole-leg',
    topic: 'Cabriole leg construction techniques',
    keywords: ['cabriole','leg','S','curve','knee','ankle','pad','foot','bandsaw','carve'],
    answer: 'The cabriole leg is an S-curved leg found in Queen Anne and Chippendale furniture. Cut the rough shape on the bandsaw in two passes — cut one face, tape the offcut back, rotate 90°, and cut the second face. This produces a perfect blank that can then be carved and smoothed. The knee (upper curve), shank, and foot are refined with spokeshave, rasps, and scrapers. The pad foot is turned on the lathe or shaped with rasps. Proportioning the leg is the critical skill — study originals carefully.',
  },
  {
    id: 'mc-table-proportions',
    topic: 'Table proportions — height, width, and apron rules',
    keywords: ['table','height','proportion','apron','top','overhang','clearance','knee','leg'],
    answer: 'Standard dining table height is 28"–30". Desk/work height: 28"–29". Coffee table: 16"–18". The apron underside should be at least 24"–25" from the floor for knee clearance at a dining table. Top overhang beyond apron: 1"–2" standard (more looks clunky; less risks hitting the apron with your legs). Leg-to-leg span (inside measure) at a four-person dining table should be at least 24" for two seats per side. A table top at least 36" wide seats two across comfortably.',
  },
  {
    id: 'mc-chair-ergonomics',
    topic: 'Chair ergonomics — seat angle, back angle, height',
    keywords: ['chair','ergonomics','seat','angle','back','rake','height','comfort','design'],
    answer: 'Dining chair seat height: 17"–18" from floor. Seat depth: 15"–17". Seat angle (rake): 2°–5° downward from front to back. Back angle from vertical: 5°–10°. Back height: 14"–18" for mid-back, 32"+ for high-back. Arm height (if present): 7"–8" above seat. These are starting points — vary them for target users (children need different dimensions). Make a full-size cardboard mockup before building a chair — adjustments to angles are much easier before cutting wood.',
  },
  {
    id: 'mc-negative-space',
    topic: 'Negative space in furniture design',
    keywords: ['negative','space','void','opening','shelving','visual','light','airy','frame'],
    answer: 'Negative space — the open areas through and around a piece — is as important as the solid wood parts. Thick legs without negative space between them look heavy; open stretcher arrangements look lighter. Bookcase backs recessed into the shelf rather than flush create a visual frame. Open cabinet sections alternating with closed ones give rhythm. Evaluate furniture design by flipping the silhouette upside down — the negative shapes should be as considered as the positive ones.',
  },
  {
    id: 'mc-grain-matching-design',
    topic: 'Grain matching for tabletops and panels',
    keywords: ['grain','match','tabletop','panel','direction','figure','book','sequence'],
    answer: 'For a glued-up tabletop, use sequential boards from the same log (or at least the same species and figure character) and arrange them for best visual match. Try all possible arrangements before gluing — bark side always up or always down was traditional advice (now debated), but keeping grain direction consistent for planing matters. Mark the boards before breaking the arrangement. Boards from the same log opened bookmatched give the most dramatic matched top.',
  },
  {
    id: 'mc-leg-to-top-ratio',
    topic: 'Leg size to top thickness visual proportion',
    keywords: ['leg','size','top','thickness','ratio','proportion','visual','thick','thin'],
    answer: 'A common guideline: table leg size should be roughly equal to the top thickness in visual weight. A 1.5" top looks good on 1.5"–2" square legs; a massive 2.5" thick slab demands chunkier legs or a heavy structural base. Thin tapered legs look best under delicate tops. Breaking the rule intentionally can be design-forward — a thick slab on thin steel legs creates visual tension. When in doubt, make scale cardboard models before committing to wood.',
  },
  {
    id: 'mc-case-proportions',
    topic: 'Casework proportions — height, width, and depth ratios',
    keywords: ['casework','cabinet','proportion','height','width','depth','ratio','design'],
    answer: 'Well-proportioned case pieces follow some loose guidelines. Width:height should rarely exceed 1:2 (a very tall, narrow case) or be less than 1:0.6 (a squat, wide case). Depth is typically 14"–18" for bookshelves, 23"–24" for kitchen base cabinets, and 12" for wall cabinets. Hanging wall cabinets proportioned too deep look top-heavy. Break wide casepieces into visual vertical sections (using pilasters or varied door widths) to avoid monotony.',
  },

  // ── WOOD DEFECTS & PROBLEM SOLVING ───────────────────────────────────────────
  {
    id: 'mc-knots-working-around',
    topic: 'Knots — tight vs loose and how to work around them',
    keywords: ['knot','tight','loose','intergrown','encased','crack','circle','plan'],
    answer: 'Tight (intergrown) knots are solidly connected to surrounding wood and can be left in place — they\'re a character feature in rustic work. Loose (encased) knots may fall out; stabilize them with thin CA glue or epoxy, or plan your cut list to place them in waste. Dead knots (darker, often surrounded by a black ring) signal a dead branch — the wood around them is weaker. On visible surfaces, orient knots where they\'re least objectionable or cut around them entirely by adjusting your layout.',
  },
  {
    id: 'mc-checks-splits-prevention',
    topic: 'Checks and splits — causes and prevention',
    keywords: ['check','split','crack','end','grain','seal','dry','fast','surface'],
    answer: 'Wood checks (cracks) when surface fibers dry faster than the interior, creating tension that tears across the fibers. Prevent checking in slabs and live-edge pieces by sealing end grain with end-grain sealer, wax, or even latex paint immediately after cutting. For boards in storage, sticker-stack with good airflow and cover the ends and top — not the sides. In the shop, don\'t leave boards in direct sun or near a heat source for extended periods.',
  },
  {
    id: 'mc-reaction-wood',
    topic: 'Reaction wood — tension wood and compression wood',
    keywords: ['reaction','tension','compression','wood','softwood','hardwood','bow','stress','release'],
    answer: 'Trees on slopes or in wind develop reaction wood — wood with internal stresses to keep the tree growing upright. In softwoods, reaction wood is on the lower side of leaning branches (compression wood) — it\'s darker, denser, and often has abnormal growth. In hardwoods, reaction wood is on the upper side (tension wood) — it\'s lighter, weak in compression, and furry after cutting. Reaction wood releases stress as you cut it — boards spring and bind saw blades. Cut extra length and expect to flatten more than usual.',
  },
  {
    id: 'mc-tearout-prevention',
    topic: 'Tearout prevention techniques',
    keywords: ['tearout','prevent','sharp','back','bevel','downcut','score','blade','plane'],
    answer: 'Tearout happens when wood fibers are lifted instead of cut. Prevention: keep tools sharp (sharp tools slice, dull tools tear); plane in the correct grain direction; score a knife line before routing or sawing across grain; use a backing board when drilling through (drill press or clamp scrap below); use a zero-clearance insert on the table saw; take lighter cuts on figured wood with a tight plane mouth. On the router table, run a final light climb cut to eliminate tearout from the standard direction if needed.',
  },
  {
    id: 'mc-cupping-flattening',
    topic: 'Cupping causes and how to flatten cupped boards',
    keywords: ['cupping','cup','cup','warp','flatten','plane','wet','moisture','caul'],
    answer: 'Boards cup across their width when one face dries faster than the other (the faster-drying face becomes concave). To flatten: for mild cupping, wet the concave face with a damp cloth, place it concave-side-down on a flat surface, and let it flatten overnight under weight. Then joint the convex face flat first on the jointer, then thickness plane. For severe cupping, handplane the convex face first to reduce it, then joint and plane. Store boards standing on edge or fully supported to prevent cupping during storage.',
  },
  {
    id: 'mc-bowing-fixing',
    topic: 'Bow and crook in lumber — should you fix it',
    keywords: ['bow','crook','warp','long','flat','mill','waste','reject','joint'],
    answer: 'Bow (curve along the length of the face) and crook (curve along the edge length) are removed by milling. Joint the face first — the bow means only the high points contact the jointer in the first pass. Repeated light passes bring the board to flat. If the bow is severe, the waste to flatten it will significantly reduce thickness; calculate whether the resulting board is thick enough for your purposes. Buying rough-sawn stock thicker than needed gives you more room to flatten bowed boards.',
  },
  {
    id: 'mc-twisting-fixing',
    topic: 'Twist (wind) in lumber and how to remove it',
    keywords: ['twist','wind','winding','stick','diagonal','plane','diagonal','face','check'],
    answer: 'Twist (wind) means opposite corners of the board are not in the same plane. Use winding sticks to identify the high corners. Mark the high corners and plane diagonally across the face (at 45° to the length) to remove the high corners first, then work toward flat with strokes parallel to the grain. The jointer removes twist only if you can get one face fully supported on the table — with severe twist, it rocks, and the jointer makes it worse. Hand plane twist first before using the jointer.',
  },
  {
    id: 'mc-drilling-blowout',
    topic: 'Preventing blowout when drilling through wood',
    keywords: ['blowout','drill','exit','through','backing','clamp','forstner','spade','brad'],
    answer: 'When a drill bit exits wood, it pushes the last few fibers out rather than cutting them, creating a ragged exit hole (blowout). Prevention: clamp a piece of scrap wood tightly against the exit face and drill through both. On the drill press, use a sacrificial backer on the table. Slow feed rate and sharp bits help. For the cleanest exit hole, drill from both sides, meeting in the middle — requires accurate center marking. Forstner bits blowout less than spade bits; brad-point bits less than twist drills.',
  },
  {
    id: 'mc-chipout-crosscuts',
    topic: 'Preventing chipout on crosscuts',
    keywords: ['chipout','crosscut','veneered','plywood','score','blade','back','zero','clearance'],
    answer: 'Crosscutting veneered plywood or hardwood produces chipout on the exit face. Prevention: zero-clearance insert in the table saw (supports fibers right up to the blade); score the cut line with a knife before sawing; use a fine-tooth blade (60+ teeth for 10" blade); apply blue painter\'s tape along the cut line; use a circular saw with a track (fine blade, scored tape on exit). On the miter saw, back the cut with a sacrificial fence attachment.',
  },
  {
    id: 'mc-end-grain-staining',
    topic: 'End grain absorbing stain too darkly',
    keywords: ['end','grain','stain','dark','absorb','seal','pre-coat','control'],
    answer: 'End grain is extremely absorbent — stain soaks in 5–10x more than face grain, turning end grain dramatically darker. To equalize: apply a diluted coat of finish (shellac, 10% poly) or end grain sealer, let dry, sand lightly, then stain. Some end grain darkening is acceptable and expected, but untreated end grain on a stained piece looks jarring. Test your sealing strategy on scrap cut from the same board before working on the actual piece.',
  },
  {
    id: 'mc-grain-direction-milling',
    topic: 'Reading grain direction before milling',
    keywords: ['grain','direction','milling','jointer','planer','read','fiber','uphill','downhill'],
    answer: 'Before running a board through the jointer or planer, look at the edge to determine grain direction. Fibers that slope "downhill" in the direction you\'re feeding will be cut cleanly. Fibers that slope "uphill" in the feed direction will be lifted and torn. Flip the board if needed — most boards have at least one direction where the grain runs favorably. On boards with reversing grain, reduce depth of cut to 1/32" or less and accept that one section will tearout regardless — hand plane it after machining.',
  },
  {
    id: 'mc-punky-wood',
    topic: 'Working with punky (partially decayed) wood',
    keywords: ['punky','soft','rot','stabilize','epoxy','firming','consolidant','pen','turning'],
    answer: 'Punky wood has partially decayed, crumbly fibers. Small areas can be stabilized with thin penetrating epoxy (System Three SilverTip or similar) — flood the area, let it soak in, and reapply until the wood firms up. For pen and small turning blanks, commercial wood stabilizing resins (vacuum-pressure impregnation) produce a very firm blank from highly punky material. Machining stabilized punky wood requires sharp tools — it\'s abrasive from the epoxy. Never use structurally punky wood in load-bearing applications.',
  },
  {
    id: 'mc-interlocked-grain-challenge',
    topic: 'Working with interlocked grain woods',
    keywords: ['interlocked','grain','elm','sapele','tearout','handplane','scraper','direction'],
    answer: 'Interlocked grain reverses direction every few inches — the wood fibers literally corkscrew around the tree. Any planing direction will tear out in some zones. Strategies: take very light cuts (0.001"–0.003" plane depth) with a very sharp, tightly set plane; use a high cutting angle on the plane iron (50°–55° instead of 45°); use a card scraper instead of a plane for final surface prep; or sand with progressive grits rather than planing at all. Accept that these woods require more finishing time.',
  },
  {
    id: 'mc-nail-pops',
    topic: 'Nail pops in face-framed cabinets',
    keywords: ['nail','pop','brad','finish','face','frame','show','move','seasonal'],
    answer: 'Nail pops occur when the wood shrinks and the fastener stays in place, pushing a small bump above the surface. Prevention: use screws or pocket screws instead of brads for face frames; keep the wood at equilibrium moisture content before assembling; use small finish brads (not larger ring-shank nails) only to hold while glue sets. If nails pop after installation, drive them below the surface with a nail set, fill with putty, and refinish. In a heated interior, seasonal shrinkage is unavoidable — design accordingly.',
  },

  // ── BUYING & MILLING LUMBER ───────────────────────────────────────────────────
  {
    id: 'mc-lumber-grades',
    topic: 'Hardwood lumber grades — FAS, Select, Common',
    keywords: ['grade','FAS','select','common','1','2','face','yield','clear','better'],
    answer: 'FAS (Firsts and Seconds) is the highest hardwood grade — boards 6"+ wide, 8\'+ long, with 83%+ clear face area. Select is nearly FAS quality in shorter boards. #1 Common has 66%+ clear yield — good for furniture with cutting optimization. #2 Common has 50%+ clear — economical for rustic work and smaller parts. For furniture, #1 Common often offers the best value — the lower price more than offsets the extra cutting time. FAS is worth the premium only for wide, long, clear parts you can\'t get from lesser grades.',
  },
  {
    id: 'mc-quartersawn-quarter',
    topic: 'What 4/4, 5/4, 6/4 lumber thickness means',
    keywords: ['4/4','5/4','6/4','8/4','quarter','rough','actual','thickness','lumber'],
    answer: '4/4 lumber is nominally 1" thick rough-sawn (actually 1–1-1/8"). After surfacing, it typically yields 13/16"–7/8". 5/4 gives about 1-1/16" surfaced, 6/4 gives about 1-5/16", 8/4 gives about 1-3/4". The fractions refer to 1/4" increments of rough-sawn thickness. Buy extra thickness for heavily bowed stock that needs significant milling. Specify "S2S" (surfaced two sides) if you want the yard to plane both faces; "rough" or "rough sawn" means you mill it yourself.',
  },
  {
    id: 'mc-moisture-meter',
    topic: 'Using a moisture meter for lumber',
    keywords: ['moisture','meter','reading','percent','MC','pin','pinless','species','correction'],
    answer: 'A pin-type moisture meter drives two probes into the wood; a pinless meter uses electromagnetic fields to read moisture without penetrating. Pin meters are more accurate at a specific depth; pinless meters scan a larger area quickly. Target moisture content for interior furniture: 6–8% in dry climates, 7–9% in moderate climates. Most meters need a species correction factor since different woods have different electrical resistance — use the correction table in the manual. Take multiple readings along the board.',
  },
  {
    id: 'mc-air-drying-rates',
    topic: 'Air drying rates for different species and thicknesses',
    keywords: ['air','dry','time','rate','year','inch','thickness','sticker','rule'],
    answer: 'The traditional rule: one year of air drying per inch of thickness. This varies significantly: softwoods and lighter hardwoods (poplar, butternut) dry faster; dense hardwoods (oak, hickory, walnut) dry slower. A 4/4 (1") walnut board needs 1–2 years minimum; 8/4 (2") needs 3–4 years. Proper stickering (3/4" dry sticks every 16"–24"), good airflow, shaded storage, and sealed end grain all speed the process and reduce checking. Check with a moisture meter before using — don\'t guess by time alone.',
  },
  {
    id: 'mc-kiln-dried-types',
    topic: 'Kiln drying methods — conventional, dehumidification, RF',
    keywords: ['kiln','dried','conventional','dehumidifier','radio','frequency','method','fast','slow'],
    answer: 'Conventional kiln drying uses forced hot air and humidity control — the standard for commercial lumber. Dehumidification kilns work at lower temperatures and are common in small custom operations. Radio frequency (RF) kilns use microwave-like energy to dry from the inside out — very fast (days vs months) but can cause checking if not carefully controlled. Air-dried lumber is often considered superior for stability by some craftspeople — slower drying allows stresses to equalize gradually.',
  },
  {
    id: 'mc-acclimatizing-lumber',
    topic: 'Acclimatizing lumber to the shop before use',
    keywords: ['acclimate','acclimatize','shop','humidity','moisture','days','weeks','sticker','indoor'],
    answer: 'Bring lumber into your shop and sticker it (stack with spacers) for at least 2 weeks — 4 weeks or more is better, especially for 6/4+ stock. The wood will adjust its moisture content to match the shop environment. Check with a moisture meter when you start and at the end of the acclimation period — when the reading stabilizes, the wood has equalized. Never mill and immediately build — wood milled cold or from a humid outdoor environment will move significantly in the first week inside.',
  },
  {
    id: 'mc-milling-sequence',
    topic: 'Milling sequence for dimensioning lumber',
    keywords: ['mill','sequence','order','face','joint','edge','thickness','crosscut','flatten','first'],
    answer: 'The correct milling sequence: (1) flatten one face on the jointer (reference face); (2) joint one edge square to the flat face (reference edge); (3) thickness-plane the opposite face parallel to the reference face; (4) rip to final width on the table saw with the reference edge against the fence; (5) crosscut to length. Never skip steps or change the order — each step depends on the reference surfaces created by the previous. Mark reference face and edge with chalk before starting.',
  },
  {
    id: 'mc-reading-end-grain',
    topic: 'Reading end grain to identify cuts and species',
    keywords: ['end','grain','read','rings','pore','species','identify','quartersawn','plain'],
    answer: 'End grain tells the whole story. Annual rings running roughly parallel to the face = flatsawn (cathedral grain on face). Rings running perpendicular to the face = quartersawn (straight grain on face). Dense, small uniform pores = diffuse-porous (maple, cherry). Large distinct early-wood pores = ring-porous (oak, ash). Color, pore size, and ray width help identify species. A reference guide (Hoadley\'s "Identifying Wood") with a hand lens is the most reliable field identification tool.',
  },
  {
    id: 'mc-buying-figured',
    topic: 'Tips for buying figured wood at the lumber yard',
    keywords: ['figured','buy','selection','flash','chatoyance','lighting','wet','choose','yard'],
    answer: 'Figured wood hides in a dry lumber stack — take a damp sponge and wet the face to reveal figure. The moisture simulates a finish and makes curly, quilted, and ray fleck pop clearly. Bring a small LED flashlight and rake it across the surface at various angles — chatoyance (3D ripple effect) is angle-dependent. Pull the board fully out of the rack and sight down its length for bow and twist. Buying figured wood requires physically selecting at the yard; online purchasing is a gamble.',
  },
  {
    id: 'mc-sawyer-direct',
    topic: 'Buying lumber direct from a sawyer',
    keywords: ['sawyer','direct','portable','mill','fresh','green','low','cost','custom'],
    answer: 'Buying directly from a local sawyer gives access to unusual species, large slabs, fresh-sawn lumber, and custom-cut dimensions at lower cost than lumber yards. The tradeoff: the lumber is usually green (unseasoned) and you must dry it yourself — years, not weeks. Some sawyers sell air-dried lumber if you\'re willing to wait for their stock to season. Local Facebook groups, Craigslist, and state woodworking guild forums are good sources. Bring your moisture meter and a flashlight.',
  },
  {
    id: 'mc-rough-vs-s4s',
    topic: 'Rough sawn vs S2S vs S4S lumber',
    keywords: ['rough','S2S','S4S','surfaced','dressed','mill','ready','four','two','sides'],
    answer: 'Rough sawn lumber comes straight from the mill — irregular surfaces, possibly still air-drying. S2S (surfaced 2 sides) has both faces planed flat but edges are still rough. S4S (surfaced 4 sides) has faces and edges planed and is ready to use at nominal thickness. Rough sawn from a hardwood dealer is the best value but requires your own milling. S4S from a home center is convenient but expensive per board foot and limited to a few species. S2S is a good middle ground from a hardwood dealer.',
  },
  {
    id: 'mc-plywood-buying',
    topic: 'Buying plywood — what to check before purchasing',
    keywords: ['plywood','buy','check','flat','void','delaminate','warp','face','core','quality'],
    answer: 'Before buying a plywood sheet, hold it vertical and sight along the face for bow — slight bow is common and usually works itself flat when fastened. Check the face veneer for patching (small football-shaped patches indicate lower grade). Look at the edge for voids in the inner plies — many domestic sheets have voids in cheaper grades. Flex the sheet slightly and listen for delamination sounds. Choose BB or better grade for visible cabinet exteriors; CD or BC for cabinet backs and carcases.',
  },
  {
    id: 'mc-lumber-species-identify',
    topic: 'Identifying common wood species at the lumber yard',
    keywords: ['identify','species','smell','color','pore','ring','grain','oak','maple','cherry'],
    answer: 'Quick identification clues: Red oak — very open pores, pinkish tan, distinct ring-porous pattern. Maple — very tight grain, white to cream, heavy. Cherry — fine grain, pinkish when fresh, darkens fast, often has gum pockets. Walnut — dark chocolate brown heartwood with distinct grain. Pine — prominent resin canals, soft, yellow-white. Many species are best identified by a combination of color, grain pattern, smell (pine is resinous, cherry has a distinctive scent), and end grain pore structure. Hoadley\'s "Identifying Wood" is the standard reference.',
  },
  {
    id: 'mc-wide-slab-sources',
    topic: 'Sourcing wide solid wood slabs for tabletops',
    keywords: ['slab','wide','tabletop','source','live','edge','local','online','price'],
    answer: 'Wide slabs come from tree removal services, local sawyers, specialty slab dealers, and online marketplaces (Etsy, Hardwood Market, local sawmill Facebook groups). Local tree services are gold — when a large urban tree is removed, contact the owner or service before the log hits the chipper. Slab prices vary wildly: a basic 2" walnut slab might be $30–50/linear foot; figured or exotic slabs can reach $200–400/linear foot. Always see large slabs in person before buying — photos hide defects.',
  },
];
