import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_A: KnowledgeEntry[] = [
  // ── WOOD SPECIES ─────────────────────────────────────────────────────────────
  {
    id: 'ma-ash-grain-pattern',
    topic: 'Ash grain pattern and figure',
    keywords: ['ash','grain','figure','olive','wavy','sports','tool','handle'],
    answer: 'Ash has a bold open grain similar to oak but with a lighter, cream color. Straight-grained ash is preferred for tool handles because the fibers absorb shock. Olive ash has dark brown heartwood streaks that make it a premium figured wood for furniture. The wide growth rings make ash excellent for steam bending into curved chair parts.',
  },
  {
    id: 'ma-walnut-regional',
    topic: 'American black walnut regional variation',
    keywords: ['walnut','black','american','region','color','light','dark','appalachian'],
    answer: 'American black walnut varies dramatically by region — Appalachian trees often produce darker, richer heartwood, while Midwest and West Coast trees can be lighter brown. Trees grown in the open tend to have more figured grain than forest-grown straight-grained trees. Color also varies within a single log, with outer sapwood being cream to tan while heartwood ranges from chocolate to purple-brown.',
  },
  {
    id: 'ma-walnut-sapwood',
    topic: 'Using walnut sapwood in furniture',
    keywords: ['walnut','sapwood','cream','heartwood','contrast','steamed'],
    answer: 'Walnut sapwood is pale cream and is often cut away, but some designers use the sapwood-to-heartwood contrast as a design element. Commercially, walnut logs are often steamed to darken the sapwood closer to heartwood color. If you want uniform color, steam-dried walnut is the way to go; if you want contrast, air-dried unsteamed boards show the full range.',
  },
  {
    id: 'ma-cherry-blotch',
    topic: 'Cherry blotching with stain',
    keywords: ['cherry','blotch','stain','conditioner','pre-stain','uneven'],
    answer: 'Cherry blotches badly with oil-based stains because its pores are very fine and absorb unevenly. A pre-stain wood conditioner (or a thin wash coat of shellac) seals the surface evenly before stain. Many woodworkers skip stain entirely on cherry — the natural color deepens beautifully with just an oil or clear varnish finish and UV exposure over months.',
  },
  {
    id: 'ma-curly-maple',
    topic: 'Curly maple figure and how it forms',
    keywords: ['curly','maple','figure','tiger','fiddleback','chatoyance','wave'],
    answer: 'Curly maple (also called tiger maple or fiddleback maple) has wavy grain that creates a 3D chatoyance — it appears to ripple as you change viewing angle. The curls are caused by undulating wood fibers, possibly from wind stress or genetic factors. It machines fine but is prone to tearout, so take light passes and plane from multiple directions. The figure is most visible under a clear or light tinted finish — heavy stains mask it.',
  },
  {
    id: 'ma-birdseye-maple',
    topic: 'Birdseye maple rarity and working',
    keywords: ['birdseye','maple','eyes','figure','rare','turning'],
    answer: 'Birdseye maple has small circular "eyes" scattered throughout the face grain, caused by dormant buds that never fully developed. It\'s not a separate species — it occurs in sugar maple, occasionally soft maple. The eyes are only visible on the flatsawn face; quartersawn birdseye loses the pattern. It planes well but the tiny eyes can pop out with aggressive cuts — use sharp tools and light passes.',
  },
  {
    id: 'ma-quartersawn-oak-ray',
    topic: 'Quartersawn oak ray fleck appearance',
    keywords: ['quartersawn','oak','ray','fleck','medullary','silver','figure'],
    answer: 'Quartersawn oak exposes the medullary rays as broad, lustrous silver or tan flecks on the face — this is the "silver grain" prized in Arts & Crafts furniture. The rays run perpendicular to the annual rings; quartersawing cuts across them to expose their full width. Ray fleck size varies — white oak has larger, more dramatic rays than red oak. Quartersawn oak also moves less across its width, making it more dimensionally stable for tabletops and doors.',
  },
  {
    id: 'ma-riftsawn-legs',
    topic: 'Riftsawn lumber for table and chair legs',
    keywords: ['riftsawn','rift','leg','vertical','straight','consistent','grain'],
    answer: 'Rift-sawn boards are cut at roughly 30–60° to the annual rings, producing straight, consistent grain lines on all four faces with no ray fleck. This makes rift-sawn stock ideal for table legs and chair legs where you want grain to look the same on every visible face. It\'s the most wasteful cutting method and therefore the most expensive, but the visual result on legged furniture is unmatched.',
  },
  {
    id: 'ma-flatsawn-cathedral',
    topic: 'Flatsawn cathedral grain appearance',
    keywords: ['flatsawn','cathedral','arch','grain','plain','sawn','most','common'],
    answer: 'Flatsawn (also called plain-sawn) lumber shows the classic cathedral arch grain patterns on the face — the annual rings curve across the width. It\'s the most common and economical cut because it yields the widest boards from a log. Flatsawn boards move more in width than quartersawn and are more prone to cupping, but the bold figure is desirable for tabletops and case sides.',
  },
  {
    id: 'ma-ambrosia-maple',
    topic: 'Ambrosia maple coloring and working',
    keywords: ['ambrosia','maple','beetle','worm','track','streaks','character'],
    answer: 'Ambrosia maple is soft maple with gray-brown streaks and tracks caused by the ambrosia beetle, which bores through the log and introduces a fungus that stains the wood. The result is character figure prized by modern rustic designers. The wood itself is structurally sound — the staining doesn\'t compromise strength. It finishes beautifully with a clear finish, and the streaks look striking with an oil or hardwax-oil finish.',
  },
  {
    id: 'ma-spalted-wood',
    topic: 'Spalted wood — beauty and caution',
    keywords: ['spalted','zone','line','fungus','rot','stabilize','safety'],
    answer: 'Spalted wood has dark zone lines and color patches caused by competing fungi staining the wood fibers. The lines and patterns are unique to each piece. Working spalted wood requires care — advanced spalting means the wood is partially rotted and crumbly, making it dangerous to turn or mill. Mildly spalted wood is fine; heavily punky areas should be stabilized with penetrating epoxy before machining. Always wear a P100 respirator — spalted wood dust contains live fungal spores.',
  },
  {
    id: 'ma-live-edge',
    topic: 'Working with live edge slabs',
    keywords: ['live','edge','slab','bark','natural','wane','flatten'],
    answer: 'Live edge slabs retain the natural edge of the tree, sometimes including bark. Before finishing, decide whether to remove the bark (it often falls off eventually) and clean out the cambium layer underneath. Flatten wide slabs with a router sled or a wide drum sander before surfacing — hand planes alone aren\'t practical on large slabs. Seal the live edges heavily with finish to prevent checking from uneven moisture exchange.',
  },
  {
    id: 'ma-crotch-figure',
    topic: 'Crotch figure in wood',
    keywords: ['crotch','figure','feather','plume','cathedral','premium','veneer'],
    answer: 'Crotch figure comes from the junction where a trunk splits into two major branches — the wood fibers swirl in dramatic plume or feather patterns. Crotch wood is almost always sold as veneer because the sections are small and the grain is so wild it can\'t be planed without tearing. It makes spectacular tabletop centers and door panels. Expect to pay a premium — good crotch veneer is expensive and in limited supply.',
  },
  {
    id: 'ma-purpleheart',
    topic: 'Purpleheart color, stability, and working',
    keywords: ['purpleheart','purple','tropical','color','fade','turning','hard'],
    answer: 'Purpleheart starts as a gray-brown when freshly cut and turns vivid purple within hours of air and light exposure. Over years of UV exposure, it fades to brown — protect it with a UV-resistant finish. It\'s extremely hard (Janka ~1860) and very stable, making it excellent for cutting boards, furniture accents, and tool handles. It\'s resinous and can be tough on saw blades; sharp carbide is essential. It glues well once the surface oils are removed with acetone.',
  },
  {
    id: 'ma-padauk-color',
    topic: 'Padauk color change over time',
    keywords: ['padauk','red','orange','fade','brown','uv','finish','protect'],
    answer: 'Padauk is a vivid red-orange when freshly cut — one of the most striking colors in woodworking. Like purpleheart, it fades significantly with UV exposure and will turn a deep brick-red to brown-red over years. A UV-filtering varnish or oil slows the fade but can\'t stop it entirely. It\'s moderately hard, machines well, and glues well if you wipe the surface with acetone before applying glue to remove surface oils.',
  },
  {
    id: 'ma-wenge',
    topic: 'Wenge characteristics and safety',
    keywords: ['wenge','splinter','pore','fill','black','stripe','pain','grain'],
    answer: 'Wenge is a dark brown/black African hardwood with coarse, open grain and dramatic dark streaks. It\'s very hard and produces vicious splinters — always wear gloves when handling rough stock. The large pores need grain filler before applying film finishes; without it, the finish sinks into the pores and looks blotchy. Its bold grain makes it striking as a design accent, though it\'s challenging to work by hand.',
  },
  {
    id: 'ma-bloodwood',
    topic: 'Bloodwood color and stability',
    keywords: ['bloodwood','red','bright','stable','accent','turning','hard'],
    answer: 'Bloodwood is a deep scarlet red tropical hardwood from South America — similar to padauk in color but more stable with less color fading. It\'s very dense and hard, takes a high natural polish, and is popular for turning, inlay, and furniture accents. The dust can irritate skin and respiratory system; wear a respirator. It glues well and accepts finishes without the oil-removal step needed for teak or padauk.',
  },
  {
    id: 'ma-sapele',
    topic: 'Sapele ribbon stripe figure',
    keywords: ['sapele','ribbon','stripe','interlocked','grain','mahogany','substitute'],
    answer: 'Sapele is an African hardwood often used as a mahogany substitute, with a rich reddish-brown color and pronounced ribbon stripe figure on quartersawn faces. The interlocked grain produces the ribbon effect but also causes tearout when planing — always plane with a sharp, finely set blade. It\'s a great choice for door panels, cabinet faces, and veneered surfaces where you want mahogany-like figure at a lower cost.',
  },
  {
    id: 'ma-african-vs-genuine-mahogany',
    topic: 'African mahogany vs genuine (Honduran) mahogany',
    keywords: ['mahogany','african','honduran','genuine','khaya','swietenia','compare'],
    answer: 'Genuine (Honduran) mahogany (Swietenia macrophylla) is CITES-listed and rare — expect to pay a premium. African mahogany (Khaya) is widely available, similar in color and workability, but with more interlocked grain that can cause tearout. Genuine mahogany has finer, straighter grain and a more even pore structure. Both finish beautifully with oil or varnish and are excellent furniture woods. For most shop work, African mahogany is the practical choice.',
  },
  {
    id: 'ma-redwood-outdoor',
    topic: 'Redwood for outdoor furniture and decking',
    keywords: ['redwood','outdoor','rot','resistant','deck','fence','tannin','straight'],
    answer: 'Redwood contains natural tannins and oils that resist rot, insects, and weathering, making it ideal for outdoor furniture, decking, and garden structures. It\'s lightweight and easy to work with hand tools. The straight grain means minimal warping and splitting. Use stainless or hot-dipped galvanized fasteners — redwood tannins react with regular steel and leave black stains. Heartwood is far more resistant than sapwood; look for "all-heart" grades for outdoor use.',
  },
  {
    id: 'ma-douglas-fir',
    topic: 'Douglas fir for structural and decorative work',
    keywords: ['douglas','fir','structural','beam','strong','hard','softwood','span'],
    answer: 'Douglas fir is one of North America\'s strongest softwoods — commonly used in structural applications like beams, joists, and house framing. Clear vertical-grain Douglas fir is beautiful for furniture, showing tight, straight grain lines. It\'s harder and stiffer than most pines, and heavy enough that large pieces are physically demanding to handle. Finishing is easy, though the resin channels need attention on stained work — wiping with naphtha before staining helps.',
  },
  {
    id: 'ma-eastern-cedar',
    topic: 'Eastern red cedar aromatic properties',
    keywords: ['eastern','red','cedar','aromatic','closet','moth','chest','aroma','lining'],
    answer: 'Eastern red cedar has a distinctive aromatic smell from natural oils that repel moths and insects, making it the traditional choice for cedar chests and closet linings. The oils diminish over years, but lightly sanding the surface revives the aroma. It\'s soft, which means it dents easily in furniture applications — use it as a liner, not a structural member. The purple-red heartwood with white sapwood makes beautiful contrasting panels.',
  },
  {
    id: 'ma-butternut',
    topic: 'Butternut wood characteristics',
    keywords: ['butternut','white','walnut','soft','carve','light','grain'],
    answer: 'Butternut (also called white walnut) is a soft hardwood with open grain similar to black walnut but much lighter in weight and color — a warm tan-brown. It carves beautifully and is one of the best carving woods in North America. It\'s too soft for furniture tops or high-wear surfaces but excellent for carved panels, drawer fronts, and accent pieces. Butternut is susceptible to butternut canker disease, making large clear logs increasingly rare.',
  },
  {
    id: 'ma-black-locust',
    topic: 'Black locust hardness and rot resistance',
    keywords: ['black','locust','hard','dense','rot','outdoor','yellow','heavy'],
    answer: 'Black locust is one of North America\'s hardest and most rot-resistant hardwoods — it outlasts redwood and cedar in ground contact and was historically used for fence posts and ship pegs. The yellow-green heartwood is extremely dense (Janka ~1700) and difficult to machine. It\'s underappreciated in furniture work; the color mellows to a warm tan and the wood machines to a fine surface. Smaller diameters make wide clear boards rare and expensive.',
  },
  {
    id: 'ma-sycamore',
    topic: 'Sycamore lacy figure',
    keywords: ['sycamore','lacewood','lace','ray','figure','interior','interlocked'],
    answer: 'American sycamore has prominent medullary rays that, when quartersawn, produce a "lacewood" pattern similar to Australian lacewood. The rays appear as light tan patches against a pinkish-brown background. It\'s prone to interlocked grain and can be challenging to plane cleanly, but produces a beautiful turned bowl or veneered panel. It was historically used for butcher blocks because it doesn\'t split from the end grain impacts of chopping.',
  },
  {
    id: 'ma-elm-interlocked',
    topic: 'Elm and its interlocked grain challenge',
    keywords: ['elm','interlocked','grain','tough','crack','bend','chairleg','burl'],
    answer: 'American elm has severely interlocked, cross-grain structure that makes it nearly impossible to split — which is why it was the traditional choice for wagon wheels, wheel hubs, and chair seats that needed to resist splitting. This same interlocked grain makes planing extremely difficult, with tearout in multiple directions. Elm burls are prized for turning and veneered panels. Dutch elm disease has made large clear elm rare; reclaimed elm from old buildings is a good source.',
  },
  {
    id: 'ma-osage-orange',
    topic: 'Osage orange hardness and rot resistance',
    keywords: ['osage','orange','hedge','apple','hardest','bow','yellow','dense'],
    answer: 'Osage orange (hedge apple or bodark) is one of North America\'s hardest and most decay-resistant woods — fence posts can last 50+ years in the ground. The heartwood is bright yellow and oxidizes to golden-brown. It was the premier wood for Native American bows. It\'s so dense and hard that it dulls tools quickly and can be dangerous to machine — secure work carefully, use carbide, and expect to sharpen often.',
  },
  {
    id: 'ma-ipe-decking',
    topic: 'Ipe for decking and outdoor structures',
    keywords: ['ipe','decking','hardwood','tropical','dense','oil','finish','pre-drill'],
    answer: 'Ipe (Brazilian walnut) is one of the densest commercial lumbers available — it sinks in water. It\'s exceptionally rot-resistant and holds up for 25+ years as decking without treatment. Its density means you must pre-drill every fastener hole to prevent splitting and burning screws. It\'s too oily for most glues and films — use penetrating oil finishes only. The dark brown color fades to silver-gray without maintenance, which many designers prefer.',
  },
  {
    id: 'ma-sitka-spruce',
    topic: 'Sitka spruce for musical instruments',
    keywords: ['sitka','spruce','guitar','top','resonance','stiffness','weight','ratio'],
    answer: 'Sitka spruce has the highest stiffness-to-weight ratio of any commercial wood, making it the standard for guitar soundboards, violin tops, and other instrument tops. Quarter-sawn Sitka with tight, straight grain and minimal runout is preferred — it transmits vibration efficiently. The same properties make it useful for airplane spars historically. For furniture, it\'s rarely used due to its softness, but as an acoustic material it\'s unrivaled.',
  },
  {
    id: 'ma-longleaf-pine',
    topic: 'Longleaf pine reclaimed and new growth',
    keywords: ['longleaf','pine','heart','virgin','reclaimed','dense','resin','old','growth'],
    answer: 'Old-growth longleaf pine is one of the hardest pines — the centuries-old trees grew slowly and have dense, resin-saturated heartwood far harder than modern plantation pine. Much of it is now reclaimed from old warehouses and factories. New-growth longleaf is being reforested and is available from sustainable sources, though it lacks the density of old-growth. The golden-orange heart pine takes a beautiful finish and holds fasteners extremely well.',
  },
  {
    id: 'ma-alder',
    topic: 'Alder for cabinets and staining',
    keywords: ['alder','west','coast','cabinet','paint','stain','fine','grain','inexpensive'],
    answer: 'Red alder is the primary commercial hardwood of the Pacific Northwest — inexpensive, light, with fine uniform grain that accepts stain very evenly, making it popular for kitchen cabinets. It\'s softer than maple or oak (Janka ~590) so it dents more easily, but it machines beautifully and has minimal blotching compared to pine or cherry. It\'s an excellent paint-grade wood and one of the best choices for stained cabinetry at a budget price.',
  },
  {
    id: 'ma-janka-hardness',
    topic: 'Janka hardness scale explained',
    keywords: ['janka','hardness','scale','rating','comparison','pound','ball','test'],
    answer: 'The Janka hardness test measures the force in pounds-force (lbf) needed to embed a steel ball halfway into the wood surface. Common reference points: balsa is around 100, pine 380–870, red oak 1290, hard maple 1450, hickory 1820, Brazilian walnut 3684. Higher numbers mean more dent resistance for flooring and tabletops, but also more tool wear and harder machining. Janka numbers help compare species objectively when choosing material for a project.',
  },
  {
    id: 'ma-ring-porous',
    topic: 'Ring-porous vs diffuse-porous wood',
    keywords: ['ring','porous','diffuse','oak','maple','pore','grain','stain'],
    answer: 'Ring-porous woods (oak, ash, elm, hickory) have large pores concentrated in the early wood (spring growth), creating bold, open grain. Diffuse-porous woods (maple, cherry, birch, walnut) have small pores evenly distributed, creating finer, more uniform grain. Ring-porous woods show strong grain patterns under stain; diffuse-porous woods stain more evenly. Knowing the type helps predict how a species will take finish and how visible the grain will be.',
  },
  {
    id: 'ma-tannin-effects',
    topic: 'Tannin content and its effects on finishing',
    keywords: ['tannin','oak','walnut','iron','stain','black','chemical','react'],
    answer: 'High-tannin woods (oak, walnut, chestnut, mahogany) react chemically with iron and steel, causing black stains at fastener locations and wherever water carries dissolved iron. Always use stainless or hot-dipped galvanized fasteners in tannin-rich woods. Tannins also interfere with certain adhesives and can bleed through water-based finishes, causing discoloration. Seal high-tannin wood with shellac before applying water-based topcoats.',
  },
  {
    id: 'ma-silica-tropical',
    topic: 'Silica in tropical hardwoods dulling tools',
    keywords: ['silica','teak','ipe','tropical','dull','carbide','blade','edge'],
    answer: 'Many tropical hardwoods — teak, ipe, iroko, afrormosia — contain silica deposits that rapidly dull steel and even carbide cutting tools. You\'ll notice blades that dull in minutes rather than hours. Use carbide-tipped tools and expect to sharpen or replace blades more often. A blade dulled on silica-rich wood will often feel sharp by touch but cut poorly — the silica abrades the microscopic cutting edge rather than chipping it visibly.',
  },
  {
    id: 'ma-baltic-birch',
    topic: 'Baltic birch plywood in depth',
    keywords: ['baltic','birch','void','ply','cabinet','drawer','shop','grade','russia','finland'],
    answer: 'Baltic birch plywood comes from Russia and Finland and is manufactured with thin, void-free birch plies throughout — unlike domestic plywood which may have softwood inner plies and voids. It\'s available in 5x5 sheets (1525×1525mm) and comes in metric thicknesses (6mm, 12mm, 18mm). It\'s the best choice for drawer boxes, cabinet carcases, and jig-making. The edge grain has a beautiful stacked-ply appearance that many woodworkers leave exposed rather than banding.',
  },
  {
    id: 'ma-mdo-plywood',
    topic: 'MDO plywood for painting and signs',
    keywords: ['mdo','medium','density','overlay','paint','sign','smooth','exterior'],
    answer: 'MDO (Medium Density Overlay) plywood has a resin-fiber surface bonded to each face, creating an extremely smooth, paint-ready surface. It\'s designed for exterior signs, concrete forms, and painted panels. Unlike MDF, MDO has a structural plywood core so it holds fasteners and handles moisture better. If you need a perfectly smooth painted surface that resists moisture, MDO is superior to MDF for cabinets going in humid environments.',
  },
  {
    id: 'ma-melamine-board',
    topic: 'Melamine coated board for cabinet interiors',
    keywords: ['melamine','coated','board','particleboard','interior','white','cabinet','shelf'],
    answer: 'Melamine board is particleboard or MDF with a melamine resin film laminated to the surface. It comes in white, colors, and wood-grain prints. It\'s the standard for modern cabinet interiors — the surface is easy to clean, doesn\'t need finishing, and resists most household chemicals. Cut it with a fine-tooth saw blade to minimize chip-out on the laminate surface. The particleboard core doesn\'t hold fasteners as well as plywood — use knock-down hardware designed for it.',
  },
  {
    id: 'ma-bending-plywood',
    topic: 'Bending plywood for curved work',
    keywords: ['bending','plywood','kerfed','flexible','curve','form','bend','radius'],
    answer: 'Flexible bending plywood (also called wiggle board or flexply) has thin plies all running in one direction, allowing it to bend easily across the grain direction. It comes in two orientations — bends lengthwise or widthwise. Stack two layers with opposing grain directions and glue over a form to make a rigid curved panel. It\'s ideal for curved cabinet doors, reception desks, and curved stair risers.',
  },
  {
    id: 'ma-phenolic-plywood',
    topic: 'Phenolic (dark brown) plywood for jigs',
    keywords: ['phenolic','dark','brown','slippery','jig','template','flat','smooth'],
    answer: 'Phenolic plywood has a dark brown resin overlay that makes the surface extremely hard, flat, and slippery. It\'s a favorite for router table tops, jig bases, and shooting boards because workpieces slide smoothly across it. It\'s also very flat and dimensionally stable. The surface dulls router bits faster than MDF but holds up to heavy use without wearing. It comes in 4x8 sheets and is available from industrial lumber suppliers.',
  },
  {
    id: 'ma-hardboard',
    topic: 'Hardboard (Masonite) uses in the shop',
    keywords: ['hardboard','masonite','thin','panel','back','template','drawer','bottom'],
    answer: 'Hardboard is dense pressed wood fiber panel, sold as 1/8" or 1/4" sheets. Tempered hardboard has oil added and is harder and slightly water-resistant. Common uses: cabinet backs, drawer bottoms, templates for routing, dust panels on chair frames, and covering workbench tops for a smooth sacrificial surface. It\'s cheap but doesn\'t hold fasteners well — rely on dado grooves or construction adhesive to secure it in place.',
  },
  {
    id: 'ma-cost-tiers-domestic',
    topic: 'Cost tiers for domestic hardwoods',
    keywords: ['cost','price','expensive','cheap','domestic','hardwood','budget','value'],
    answer: 'Budget tier: poplar, soft maple, alder — $3–5 per BF. Mid-tier: red oak, ash, birch, hard maple — $5–8 per BF. Premium domestic: walnut, cherry, white oak — $8–15 per BF. Figured wood (curly, birdseye, quilted) commands double to triple the figure-grade premium on top of the base price. Prices vary significantly by region and yard — walnut is cheaper in the Midwest where it\'s local, and oak is cheaper in the East.',
  },
  {
    id: 'ma-cost-tiers-exotics',
    topic: 'Cost tiers for exotic hardwoods',
    keywords: ['exotic','tropical','cost','price','expensive','teak','ebony','per','board','foot'],
    answer: 'Entry-level exotics: sapele, sipo, okoume, meranti — similar prices to mid-tier domestics. Mid-tier exotics: mahogany, teak, purpleheart, padauk — $10–20 per BF. Premium exotics: bubinga, wenge, bocote, ziricote — $20–40 per BF. Ultra-premium: ebony, cocobolo, lignum vitae — $40–100+ per BF and often only available in small sizes. CITES restrictions on certain species (rosewood, ebony) affect availability and legal import status.',
  },
  {
    id: 'ma-wood-movement-rates',
    topic: 'Wood movement rates by species comparison',
    keywords: ['movement','seasonal','shrinkage','radial','tangential','rate','species','compare'],
    answer: 'Wood moves tangentially (parallel to rings) about twice as much as radially (perpendicular to rings). Quartersawn is more stable because the wood is cut radially. High-movement species: beech, sycamore, red oak. Medium movement: hard maple, cherry, walnut, white oak. Low movement: teak, mahogany, quartersawn white oak. The ratio of tangential to radial shrinkage also affects whether wood cups — low ratios (close to 1:1) are more stable like mahogany; high ratios (2:1+) like beech tend to cup more.',
  },
  {
    id: 'ma-equilibrium-moisture',
    topic: 'Equilibrium moisture content (EMC) and wood movement',
    keywords: ['emc','equilibrium','moisture','content','humidity','rh','target','indoor'],
    answer: 'Wood naturally adjusts its moisture content to balance with the surrounding relative humidity — this is its equilibrium moisture content (EMC). At 40-50% RH (typical heated home), EMC is around 7-9%. At 70% RH (garage in summer), EMC is around 13-15%. Wood needs to be at its EMC for its final environment before you build — if you install furniture at 15% MC in a 8% MC home, it will shrink and crack. Use a moisture meter and acclimate lumber for weeks in the shop before milling.',
  },
  {
    id: 'ma-wood-toxicity',
    topic: 'Wood dust toxicity and allergens by species',
    keywords: ['toxicity','allergen','dust','sensitize','poison','reaction','species','health'],
    answer: 'Some woods cause sensitization — repeated exposure creates allergic reactions that worsen over time. High-risk: cocobolo, rosewood, mahogany, teak, ebony, Western red cedar. Medium risk: walnut (contains juglone), oak, pine (resinous). Even "safe" species cause irritation with fine dust. Always wear a P100 half-face respirator for exotic woods, not just an N95. Once sensitized, even small exposures can trigger reactions. Keep your shop vacuumed and use dust collection at the source.',
  },
  {
    id: 'ma-bookmatch',
    topic: 'Bookmatching panels for symmetry',
    keywords: ['bookmatch','book','match','sequential','veneer','panel','symmetric','mirror'],
    answer: 'Bookmatching means opening two consecutive slices from the same log like pages of a book — the grain mirrors symmetrically across the joint. It creates a dramatic butterfly pattern on figured wood. For solid wood, use consecutive boards from the same log and orient them grain-side-down together, then flip one open. Glue the joint with careful alignment. Bookmatch panels are striking on cabinet doors, tabletops, and speaker cabinets.',
  },
  {
    id: 'ma-veneer-application',
    topic: 'Applying veneer with contact cement or PVA',
    keywords: ['veneer','contact','cement','pva','glue','roller','substrate','iron','bag'],
    answer: 'Contact cement gives an instant bond — apply to both surfaces, let dry, then press together (no repositioning). PVA with vacuum press or cauls gives more control — apply to substrate only, then place veneer, press firmly, and clamp for 30 minutes to several hours. A household iron with a damp cloth can activate hide glue on pre-glued veneer. Keep veneer flat by humidifying slightly if it\'s curled — pressing curled veneer risks it cracking or telegraphing through.',
  },
  {
    id: 'ma-rotary-vs-sliced-veneer',
    topic: 'Rotary-cut vs sliced veneer differences',
    keywords: ['rotary','sliced','veneer','cut','lathe','peel','figure','match'],
    answer: 'Rotary-cut veneer peels around a spinning log like unrolling a roll of paper — it produces wide sheets with wild grain patterns, used mainly for plywood face veneers. Flat-sliced veneer is sliced like salami from a half log, producing sheets that show the true grain figure. Quartersawn-sliced gives ribbon stripe on appropriate species. For matching and bookmatching decorative panels, always specify flat-sliced or quartersawn-sliced veneer — rotary-cut won\'t match.',
  },
  {
    id: 'ma-humidity-shop-control',
    topic: 'Controlling humidity in the shop for lumber storage',
    keywords: ['humidity','shop','control','dehumidifier','storage','acclimate','rh','wood'],
    answer: 'Ideally store and work lumber at the humidity of the room it\'s destined for — typically 35–55% RH for interior furniture. In humid climates, use a dehumidifier in summer; in dry climates, add a humidifier in winter. Sticker-stack lumber with small wood strips between layers to allow air circulation. Never store lumber on a concrete floor — wick moisture up from below. A $30 digital hygrometer lets you monitor shop RH and catch humidity swings before they warp your lumber.',
  },
  {
    id: 'ma-bluestain-pine',
    topic: 'Bluestain fungus in pine lumber',
    keywords: ['bluestain','blue','stain','fungus','pine','discolor','structural','beetle'],
    answer: 'Bluestain (sap stain) is a fungal discoloration in pine sapwood — it appears as blue-gray streaking and is introduced by bark beetles. It\'s purely cosmetic; bluestained pine is structurally identical to unstained pine. For painted or rustic work it doesn\'t matter at all. For natural or stained work, bluestain will show through clear finishes. Many designers embrace it as a character feature, especially in reclaimed or beetle-kill pine.',
  },
  {
    id: 'ma-mineral-streaks',
    topic: 'Mineral streaks in cherry and other hardwoods',
    keywords: ['mineral','streak','cherry','walnut','gray','discolor','stain','natural'],
    answer: 'Mineral streaks are gray, dark green, or dark brown discolorations in wood caused by mineral deposits absorbed during tree growth. Common in cherry, hard maple, and soft maple. They\'re natural — not decay or defect — but some buyers consider them downgrade. Under a clear finish they\'re often an interesting feature; under stain they may read differently than the surrounding wood. Avoid selecting boards with mineral streaks if you need consistent stain color.',
  },

  // ── JOINERY ──────────────────────────────────────────────────────────────────
  {
    id: 'ma-through-dovetail-detail',
    topic: 'Through dovetail proportions and layout',
    keywords: ['through','dovetail','tail','pin','ratio','layout','proportion','angle'],
    answer: 'Through dovetails are fully visible from both faces — the tails on one board interlock with pins on the other. The traditional ratio is 1:6 for hardwoods (less angle) and 1:8 for softwoods (more angle). Lay out tails first, then use them to scribe the pins directly — never trust transferred measurements. Half-pins at the ends are essential to close the corners neatly. The joint\'s mechanical resistance to pulling apart comes from the trapezoidal tail shape, not the glue.',
  },
  {
    id: 'ma-half-blind-dovetail',
    topic: 'Half-blind dovetails for drawer fronts',
    keywords: ['half','blind','dovetail','drawer','front','hidden','concealed','rabbet'],
    answer: 'Half-blind dovetails conceal the joint from the front face while remaining visible from the side — the classic choice for drawer fronts. The tails stop short of the front face by about 1/8"–1/4", leaving a thin wall that hides the joint. This thin wall is the most delicate part to chop — work from both the side and the face, never taking out too much at once. The joint is significantly more challenging to cut by hand than a through dovetail.',
  },
  {
    id: 'ma-full-blind-dovetail',
    topic: 'Full-blind (secret mitered) dovetail',
    keywords: ['full','blind','mitered','secret','dovetail','invisible','box','corner'],
    answer: 'The secret mitered dovetail hides both faces behind a mitered corner — from outside the box you see only a clean miter; inside, the dovetail structure is visible. It\'s one of the most difficult joints in hand woodworking. The miter must be cut after the dovetails are fitted, and the mitered sections need to align perfectly. It\'s used in fine boxes and cabinets where even the inside joint matters aesthetically.',
  },
  {
    id: 'ma-sliding-dovetail-detail',
    topic: 'Sliding dovetail joint setup and fit',
    keywords: ['sliding','dovetail','shelf','divider','fit','sneak','snug','router'],
    answer: 'A sliding dovetail has a trapezoidal tenon that slides into a matching groove — used for attaching shelves, dividers, or breadboards. The fit must be snug but not so tight the joint seizes. Cut the groove first, then sneak up on the tenon size in test cuts until it slides with light hand pressure. A tiny amount of wax on the tenon eases assembly. Glue only the first inch or two to allow seasonal movement on wide panels.',
  },
  {
    id: 'ma-mortise-tenon-proportions',
    topic: 'Mortise and tenon proportioning rules',
    keywords: ['mortise','tenon','proportion','rule','third','thickness','width','length'],
    answer: 'The classic rule: tenon thickness is one-third the stock thickness. Tenon width is no more than five times its thickness to limit racking. Tenon length should be at least 2/3 of the mortised member\'s width — a stub tenon less than 1" long has little mechanical strength. For a 3/4" thick rail, the tenon is 1/4" thick. For a 4" wide rail, use twin tenons rather than one very wide tenon to manage wood movement.',
  },
  {
    id: 'ma-haunched-tenon',
    topic: 'Haunched tenon for panel grooves',
    keywords: ['haunched','tenon','haunch','groove','panel','door','frame','fill'],
    answer: 'A haunched tenon has a notched shoulder — the haunch fills the groove that runs through the stile for the floating panel. Without the haunch, an ugly gap would appear at the top or bottom rail where the groove extends past the tenon. The haunch is typically square (full thickness of the tenon) and fills the groove depth exactly. This is the standard joint for frame-and-panel doors where the groove is run on the router table before assembly.',
  },
  {
    id: 'ma-wedged-tenon',
    topic: 'Wedged through tenon for permanent joints',
    keywords: ['wedged','tenon','kerf','fox','wedge','through','permanent','splay'],
    answer: 'A wedged through tenon has kerfs sawn in the end of the tenon; after assembly, wedges are driven in to splay the tenon and lock it permanently in the mortise. Fox-wedging does this blind — the wedges compress as the tenon seats, with no way to disassemble without breaking it. Straight wedging in a through tenon creates a visible decorative detail on the outside face. The angle of the wedge should match the splay it creates in the mortise walls.',
  },
  {
    id: 'ma-drawbore-detail',
    topic: 'Drawbore technique for tight mortise and tenon',
    keywords: ['drawbore','draw','bore','offset','pin','peg','pull','tight','clampless'],
    answer: 'Drawboring pulls a loose mortise and tenon joint tight using a misaligned peg hole. Drill through the mortise walls first, assemble dry, then mark and drill the tenon hole offset 1/16" toward the shoulder. Drive a tapered wooden peg (often dry oak) through — the offset forces the tenon to draw tight against the shoulder. The joint assembles without clamps and is permanently locked. Traditional timber framing uses drawbored joints throughout for this reason.',
  },
  {
    id: 'ma-bridle-joint-detail',
    topic: 'Bridle joint for T and corner connections',
    keywords: ['bridle','joint','T','corner','mortise','open','slotted','gate','frame'],
    answer: 'The bridle joint (open mortise and tenon) has a slot cut into one member and a fork on the other — the fork wraps around the slotted member. It\'s faster to cut than a traditional mortise and tenon and very strong in bending. It\'s the go-to joint for frame corners, gate corners, and T-connections on garden furniture. Cut the slot with a tenon saw and chisel, then use the slot to scribe the fork shoulders for a perfect fit.',
  },
  {
    id: 'ma-finger-joint-jig',
    topic: 'Box joint jig for the table saw',
    keywords: ['box','finger','joint','jig','table','saw','router','spacing','consistent'],
    answer: 'A box joint jig indexes the workpiece by one finger width per cut, producing perfectly spaced interlocking fingers. The jig has a key the same width as the cut — after each pass, you move the board over by resting the last slot against the key. The key-to-blade distance must equal one finger width exactly. Make a few test cuts in scrap to dial in the spacing before cutting good material. The fit should be snug but not forced — about the same feel as a good drawer fit.',
  },
  {
    id: 'ma-scarf-joint-types',
    topic: 'Scarf joint types and angle requirements',
    keywords: ['scarf','joint','angle','length','splice','long','grain','tension','compression'],
    answer: 'A scarf joint splices two boards end-to-end. A plain glued scarf needs a slope ratio of at least 1:8 (ideally 1:12) to have enough long-grain glue area for good strength. Mechanical scarfs add wedges, keys, or bolts for structural applications like timber frames. A fished scarf uses side plates on both faces bolted through. For furniture stretchers, a simple 1:10 glued scarf is invisible and nearly as strong as a single piece if the grain is perfectly parallel.',
  },
  {
    id: 'ma-lap-joint-types',
    topic: 'Lap joint variations for frames and boxes',
    keywords: ['lap','joint','half','cross','corner','middle','dado','rabbet'],
    answer: 'Lap joints overlap two pieces with half the thickness removed from each — they\'re fast and strong enough for many applications. Corner lap (end lap) works for box corners. Cross lap joins two pieces crossing at any point. Middle lap connects a rail to the middle of another rail. The dado and rabbet are essentially specialized laps. Lap joints have more long-grain glue area than a butt joint but less mechanical resistance than a mortise and tenon under racking loads.',
  },
  {
    id: 'ma-biscuit-sizes',
    topic: 'Biscuit joiner slot sizes and uses',
    keywords: ['biscuit','joiner','plate','size','0','10','20','align','strength'],
    answer: 'Biscuit joiners cut football-shaped slots for compressed beech biscuits that swell when glue contacts them. Size 0 is the smallest — for narrow stock 1/2"–3/4". Size 10 is medium — standard for most 3/4" panels. Size 20 is large — for thicker stock and frames. Biscuits are primarily alignment aids in furniture work; they add little structural strength in face grain. They do a better job in edge-to-face joints like shelf dadoes. Space them every 6–8" on long glue-ups.',
  },
  {
    id: 'ma-domino-vs-biscuit',
    topic: 'Festool Domino vs biscuit joiner comparison',
    keywords: ['domino','festool','biscuit','compare','strength','loose','tight','tenon','mortise'],
    answer: 'The Domino creates a floating mortise and oval tenon using a plunging oscillating bit — much stronger than a biscuit. Dominoes come in loose and tight tenon lengths; loose allows panel movement, tight locks the joint. The Domino is faster and more precise than a traditional mortise and tenon for frame work. The machine itself costs 5–10 times more than a biscuit joiner. For most hobby shops, a biscuit joiner plus pocket screws covers 90% of Domino use cases at a fraction of the cost.',
  },
  {
    id: 'ma-pocket-hole-engineering',
    topic: 'Pocket hole joint engineering and limits',
    keywords: ['pocket','hole','strength','limit','shear','tension','screw','kreg'],
    answer: 'Pocket hole joints excel at face-frame assembly, carcass backs, and table apron-to-leg connections. They\'re strong in shear (face frame connections, drawer assembly) but weak in tension (face-pulling loads). Never rely on pocket screws alone for chair joints — they\'ll pull loose under repeated stress. The screws need to engage enough material — a 3/4" board needs a longer screw than the standard setup; consult the pocket hole manufacturer\'s chart. Clamp the joint while driving screws to prevent offset.',
  },
  {
    id: 'ma-cam-lock-hardware',
    topic: 'Cam lock (confirmat) knock-down hardware',
    keywords: ['cam','lock','confirmat','knock','down','flat','pack','rta','euronut','barrel'],
    answer: 'Knock-down cam lock connectors let furniture be assembled and disassembled repeatedly. The cam (eccentric bolt head) locks into a barrel nut in the adjoining panel. Confirmat screws are a simpler alternative — coarse-thread screws designed for particleboard that drive directly into the edge. Both require accurately located holes; a drilling jig is essential. Knock-down hardware is used in RTA (ready-to-assemble) furniture and shop fixtures where you need to reconfigure later.',
  },
  {
    id: 'ma-dowel-jig',
    topic: 'Dowel jigs for accurate hole alignment',
    keywords: ['dowel','jig','alignment','drill','accurate','guide','self-centering'],
    answer: 'Dowel joints need precisely aligned holes or the joint will be offset and rack during assembly. Self-centering dowel jigs automatically locate in the center of the stock thickness — fast for edge-to-face joints. Transfer punches (dowel centers) let you drill one board, then mark the mating board by pressing them together. For cabinet face frames, a self-centering jig with depth stop is fastest. Grooved dowels let excess glue escape and reduce hydraulic pressure during assembly.',
  },
  {
    id: 'ma-krenov-style-joint',
    topic: 'Wedged through tenon as design element',
    keywords: ['krenov','wedge','tenon','visible','design','through','aesthetic','craft'],
    answer: 'The visible wedged through tenon — popularized by James Krenov — turns a structural joint into a decorative feature. The tenon extends through the mortised piece and is wedged with a contrasting wood species, the wedge visible on the outside face. This signals craft and intentionality. The mortise must be cut with slightly tapered sides to allow the splayed tenon to pull the joint tight. The wedge itself should be dense, fine-grained hardwood.',
  },
  {
    id: 'ma-loose-tenon-router',
    topic: 'Loose tenon joints cut with a router',
    keywords: ['loose','tenon','router','mortise','festool','lamello','strong','fast'],
    answer: 'A loose (floating) tenon system cuts identical mortises in both mating pieces, then inserts a separate tenon strip to fill both. The Festool Domino is the premium tool for this; a plunge router with a spiral bit and fence works just as well. Mill loose tenon stock from straight-grained hardwood to fit your mortise snugly. This approach is faster than cutting integral tenons and just as strong — the joint is essentially a double mortise with a floating tenon.',
  },
  {
    id: 'ma-rabbet-joint-variations',
    topic: 'Rabbet joint for case backs and box corners',
    keywords: ['rabbet','rebate','groove','back','panel','box','corner','lid'],
    answer: 'A rabbet (rebate) is an L-shaped cut along an edge or end — the most versatile case-making joint. Used for cabinet backs (rabbet cut in the case sides receives the back panel), box corners (rabbeted box corner hides end grain), and drawer backs (a rabbet on the drawer side receives the back). Cut rabbets on the table saw with a dado stack or a straight bit in the router table. A backing board prevents tearout on the exit side.',
  },
  {
    id: 'ma-tongue-groove-variations',
    topic: 'Tongue and groove joint variations',
    keywords: ['tongue','groove','flooring','panel','frame','floating','glue','align'],
    answer: 'Tongue and groove joints interlock a projecting tongue into a matching groove — they align panels and provide mechanical resistance to racking. In floating panels (frame-and-panel doors), the panel slides in the groove unglued to allow movement. In solid wood flooring, T&G provides alignment with no glue — the floor floats on the subfloor. For glued T&G panels, glue only the first few inches to allow movement. Keep tongue thickness at 1/3 the stock thickness.',
  },
  {
    id: 'ma-spline-miter',
    topic: 'Spline reinforcement for miter joints',
    keywords: ['spline','miter','corner','reinforce','glue','kerf','slot','plywood'],
    answer: 'A spline is a thin strip of wood or plywood inserted into a matching slot sawn across a miter joint. It dramatically increases the long-grain glue area and provides mechanical resistance to the joint opening. Cut the spline slot on the table saw with a jig that holds the mitered corner at 45°. Use plywood for the spline (cross-grain resists splitting) or a short-grain solid spline cut from scrap. Splines are standard on frame joints and small box miters.',
  },
  {
    id: 'ma-keyed-miter',
    topic: 'Keyed miter joint as visible decoration',
    keywords: ['keyed','miter','key','butterfly','box','corner','inlay','contrast'],
    answer: 'A keyed miter has a contrasting wood key inserted across the corner after assembly. The joint is assembled and fully cured, then slots are sawn across the corner on the table saw using a V-block jig. Contrasting keys (walnut keys in maple, for example) are glued in and trimmed flush. The keys are structural and decorative — they add real strength while signaling the maker\'s intent. Space keys evenly and use an odd number for best visual balance.',
  },
  {
    id: 'ma-rule-joint',
    topic: 'Rule joint for drop-leaf tables',
    keywords: ['rule','joint','drop','leaf','table','cove','roundover','hinge','knuckle'],
    answer: 'The rule joint is a matched cove and roundover between a drop-leaf table top and its leaf. When the leaf drops, the curved profiles rotate against each other cleanly, hiding the gap. The hinge is mortised below the joint pivot point — its knuckle aligns with the center of the roundover radius. If the hinge is set at the wrong location, the joint will bind or gap when swinging. The router makes cutting the profiles straightforward; getting the hinge placement right is the harder part.',
  },
  {
    id: 'ma-breadboard-end',
    topic: 'Breadboard ends for tabletop flatness',
    keywords: ['breadboard','end','tabletop','movement','slot','peg','flat','warp'],
    answer: 'Breadboard ends cap the end grain of a solid wood tabletop to keep it flat and protect the end grain. Because the top moves seasonally across its width and the breadboard is glued perpendicular to the grain, the joint must allow movement. Glue only the center peg; elongate the outer peg holes as slots to let the top move. The breadboard should be slightly shorter than the top\'s narrowest seasonal width to avoid it projecting in dry conditions.',
  },
  {
    id: 'ma-bridle-T-joint',
    topic: 'T-bridle joint for stretchers and rails',
    keywords: ['T','bridle','stretcher','rail','table','frame','open','slot'],
    answer: 'The T-bridle (stub mortise and tenon bridled) uses an open slot cut into one member to accept a two-shouldered tenon from another. It\'s used where a rail meets the middle of another rail — like a stretcher-to-stretcher connection. The slot is cut all the way through on the face, making it easier to clean than a traditional mortise. It\'s weaker in tension than a closed mortise but adequate for compression-loaded stretchers and framework joints.',
  },
  {
    id: 'ma-pinned-tenon',
    topic: 'Pinning a mortise and tenon for permanence',
    keywords: ['pin','peg','oak','tenon','mortise','timber','frame','permanent','round'],
    answer: 'Pegging a glued mortise-and-tenon joint adds mechanical reinforcement and is the standard in timber framing. Drill through the assembled joint and drive a seasoned hardwood peg (traditionally riven oak) that is slightly larger than the hole — it wedges in as you drive it and compresses the wood fibers for a self-tightening fit. Pre-bore the tenon peg hole slightly offset toward the shoulder (drawbore) to pull the joint tight. Saw the peg flush and the surface is clean.',
  },
  {
    id: 'ma-butterfly-key',
    topic: 'Butterfly (bowtie) key for stabilizing cracks',
    keywords: ['butterfly','bowtie','key','crack','check','stabilize','inlay','slab'],
    answer: 'Butterfly keys (bowties) are hourglass-shaped inlays driven across a crack to lock it and prevent further splitting. Make the key from dense hardwood — it should be slightly fatter than the routed pocket so it presses in. Rout the pocket by tracing the key shape with a marking knife, then chop and rout to depth. The key should sit slightly proud, then be planed flush after the glue cures. Contrasting species make a dramatic design feature on live-edge slabs.',
  },
  {
    id: 'ma-glue-mortise-strategy',
    topic: 'Where to glue in a mortise and tenon',
    keywords: ['glue','mortise','tenon','where','apply','squeeze','out','long','grain'],
    answer: 'Apply glue to the mortise walls (all four), to both tenon faces, and to the shoulders. Avoid putting glue on the end grain of the tenon — end grain absorbs glue but provides almost no strength. Too much glue creates hydraulic lock; back-chamfer the tenon end slightly to let excess squeeze out. Squeeze-out inside a deep mortise is hard to clean — use a small brush or pipe cleaner to apply glue precisely inside the mortise rather than globbing it on the tenon.',
  },
  {
    id: 'ma-box-joint-strength',
    topic: 'Box joints vs dovetails in strength',
    keywords: ['box','finger','joint','dovetail','strength','compare','glue','area'],
    answer: 'Box joints (finger joints) have more long-grain glue surface area than dovetails of the same finger count, making them potentially stronger in pure glue-joint tests. Dovetails resist mechanical pull-out (no glue needed to prevent the joint from opening in one direction) while box joints rely entirely on glue. In practice, both are more than strong enough for box and drawer construction. Box joints are faster to cut with a jig; dovetails signal hand craftsmanship.',
  },
  {
    id: 'ma-cope-stick-joint',
    topic: 'Cope and stick router bit joint for doors',
    keywords: ['cope','stick','router','bit','frame','panel','door','quick','profile'],
    answer: 'Cope and stick router bit sets cut both the frame profile and the panel groove in one pass (stick cut), then cope the rail ends to match (cope cut). The rail ends interlock with the stile profile for a strong, fast frame-and-panel joint. You must use both bits from the matched set — mix brands and the profiles won\'t mate. The joint has no real mechanical strength on its own (no tenon shoulders for racking resistance), so many woodworkers add a dowel or Domino at each rail-stile joint.',
  },
  {
    id: 'ma-coping-saw-curves',
    topic: 'Coping trim profiles for inside corners',
    keywords: ['cope','cope','trim','moulding','inside','corner','45','profile','butt'],
    answer: 'Coping an inside corner means cutting the profile of one trim piece so it overlaps the face of the other — rather than mitering two pieces at 45°. A coped joint stays tight even as the room expands and contracts; miters open at inside corners. To cope: miter the piece at 45° first, then use a coping saw to cut along the revealed profile line. Undercut slightly (angle the saw back a few degrees) for a tighter front edge fit against the mating piece.',
  },
  {
    id: 'ma-dado-depth',
    topic: 'Dado joint depth and strength',
    keywords: ['dado','groove','depth','shelf','half','third','weak','strength'],
    answer: 'A dado (housing joint) supports a shelf from below by capturing its end in a slot. Depth should be 1/3–1/2 of the thickness of the housed piece — never more than half, or you weaken the shelving unit significantly. A stopped dado (the slot doesn\'t run the full width) hides the joint from the front. Use a dado stack for clean, flat-bottomed dados on the table saw. The shelf should slide in snugly with hand pressure — not forced, not sloppy.',
  },
  {
    id: 'ma-double-tenon',
    topic: 'Twin tenons for wide rails',
    keywords: ['twin','double','tenon','wide','rail','movement','apron','table'],
    answer: 'When a rail is wider than about 3"–4", a single tenon across the full width will conflict with seasonal wood movement — the wide tenon would need to allow the full movement of the wide rail. Twin tenons (two narrower tenons side by side with a gap between) solve this: each tenon is narrower and the gap between them accommodates movement. Twin tenons also provide more surface area and better resist racking than one wide tenon.',
  },
  {
    id: 'ma-mortise-order',
    topic: 'Mortise before tenon cutting order',
    keywords: ['mortise','first','tenon','order','fit','chop','cut','sequence'],
    answer: 'Always cut the mortise first, then fit the tenon to the mortise — not the other way around. Mortises are harder to change once cut; tenons are easy to sneak up on with a shoulder plane or a few extra table saw passes. A tenon that is slightly too thick can be trimmed; a mortise that is slightly too large can\'t be easily reduced. Mark the mortise from your actual chisel width to set dimensions.',
  },
  {
    id: 'ma-loose-fit-joint',
    topic: 'How tight should a mortise and tenon be',
    keywords: ['fit','tight','loose','snug','hand','pressure','mortise','tenon','dry'],
    answer: 'A well-fitted mortise and tenon should slide together with firm hand pressure — not pounding, but not loose either. If it drops in under its own weight, it\'s too loose. If it requires mallet blows dry, it will crack the mortise when glue swells the wood. Test the fit dry before gluing; a joint that\'s slightly too tight will become impossible to assemble with wet glue adding friction. Shoot for: firm push by hand, comes apart with a sharp rap from the heel of your hand.',
  },
  {
    id: 'ma-japanese-joinery',
    topic: 'Japanese joinery principles and complexity',
    keywords: ['japanese','joinery','complex','interlocking','no','glue','timber','wood','frame'],
    answer: 'Japanese joinery uses complex interlocking geometry cut without glue or metal fasteners. Traditional examples include the kanawa tsugi (scarfed splice) and the shachi sen (wedged timber joint). The joints are self-locking under load and are designed for disassembly and repair. Learning Japanese joinery develops deep geometry and hand-tool skills. For furniture work, simplified Japanese joints (the sliding dovetail, wedged through tenon) offer a manageable introduction to the principles.',
  },

  // ── HAND TOOLS ───────────────────────────────────────────────────────────────
  {
    id: 'ma-no4-plane',
    topic: 'No. 4 bench plane for smoothing',
    keywords: ['no4','number','4','smoother','plane','final','surface','prep'],
    answer: 'The No. 4 smoothing plane is the classic final-step hand plane — 9–10" long, single iron, takes very fine shavings to leave a glass surface. Set the cap iron close to the cutting edge (1/16" or less) to reduce tearout on figured grain. A freshly honed iron should produce shavings thin enough to see light through. The No. 4 is the most versatile bench plane for a beginning hand tool woodworker.',
  },
  {
    id: 'ma-no5-jack-plane',
    topic: 'No. 5 jack plane for stock removal',
    keywords: ['no5','jack','plane','stock','removal','roughing','camber','fast'],
    answer: 'The No. 5 jack plane (14–15" long) is the workhorse — used to flatten, remove mill marks, and rough-dimension stock. Its iron is often cambered (curved edge, not straight) so it takes heavier gouging cuts without leaving straight track marks. It bridges high spots on bowed stock where a shorter plane would follow the wave. For stock over 6" wide, the jack works the wood down to near-flat before the jointer or a longer trying plane takes over.',
  },
  {
    id: 'ma-no7-jointer-plane',
    topic: 'No. 7 jointer plane for long edges',
    keywords: ['no7','jointer','plane','long','edge','joint','flat','22','inch'],
    answer: 'The No. 7 jointer plane (22") is the longest common bench plane, used to true long edges for glue joints and flatten large panels. Its length bridges low spots that shorter planes would follow, skimming only the high points. For glue-joint preparation, a jointed edge should show a light gap in the middle (1/32") so clamp pressure closes the joint firmly at the ends — a technique called a "sprung joint." The No. 7 is heavy and tiring to use, but irreplaceable for edge jointing without a power jointer.',
  },
  {
    id: 'ma-block-plane-uses',
    topic: 'Block plane uses and setup',
    keywords: ['block','plane','end','grain','chamfer','trim','low','angle','bevel','up'],
    answer: 'Block planes are small (6–7"), single-handed, and have the bevel facing up — the low angle (12° bed) makes them ideal for end grain. Use them for chamfering edges, trimming flush plugs and dowels, fitting drawer faces, and shooting miters. The adjustable mouth (on better versions) controls tearout — tighter for finish work, open for faster cuts. A block plane rides comfortably in an apron pocket and is useful for dozens of trim and fitting tasks.',
  },
  {
    id: 'ma-router-plane',
    topic: 'Hand router plane for consistent depth',
    keywords: ['router','plane','groove','dado','hinge','mortise','consistent','depth','hand'],
    answer: 'The hand router plane has a blade that extends below the sole to cut flat-bottomed grooves, dados, and recesses to a precise, consistent depth. It\'s invaluable for trimming hinge mortises, refining machine-cut dados, and cleaning up stub tenon shoulders. Set depth by clamping the blade at the desired projection — the flat sole registers on the surrounding surface, not the cut. A hand router plane does things a power router can\'t: it can reach into a stopped groove and trim incrementally without tearout risk.',
  },
  {
    id: 'ma-shoulder-plane',
    topic: 'Shoulder plane for trimming tenon shoulders',
    keywords: ['shoulder','plane','tenon','trim','square','rabbet','edge','accurate'],
    answer: 'The shoulder plane has an iron the full width of the body, so it can plane right up to a shoulder without leaving a ledge. It\'s the precise tool for trimming tenon shoulders square and trimming rabbets. Set it to take a very thin shaving and work the shoulder from both faces toward the center to prevent tearout at the edges. A good-fitting tenon often needs just a few shoulder plane strokes to tune a gap-free joint.',
  },
  {
    id: 'ma-compass-plane',
    topic: 'Compass plane for curved surfaces',
    keywords: ['compass','curved','plane','concave','convex','adjust','radius','hull'],
    answer: 'The compass plane has a flexible sole that can be adjusted to both convex and concave curves. It\'s used for chair seats, boat hull planking, coopered stave joints, and any curved surface too large to sand efficiently. Adjust the sole to match the curve of the work, then take light passes. On concave surfaces, the plane rocks slightly side to side — keep passes consistent in direction to avoid high spots. Good compass planes hold their curve setting accurately; cheap ones flex inconsistently.',
  },
  {
    id: 'ma-card-scraper-use',
    topic: 'Card scraper technique and sharpening',
    keywords: ['card','scraper','burnish','burr','hook','sharp','shaving','figure','tearout'],
    answer: 'The card scraper removes whisker-thin shavings and is often the best tool for figured wood where a plane causes tearout. To sharpen: file the edge square, hone on a stone, then turn a hook with a burnishing rod held at 5–10° above horizontal. The hook (burr) is the cutting edge — when shavings stop and dust appears, the hook is gone. Flex the card slightly while scraping — the center of the flex is the cutting zone. Keep the scraper moving to avoid heat buildup that blurs your thumbs.',
  },
  {
    id: 'ma-cabinet-scraper',
    topic: 'Cabinet scraper vs card scraper',
    keywords: ['cabinet','scraper','handle','flat','back','holder','large','surface'],
    answer: 'A cabinet scraper is a thicker plate of steel mounted in a handle — the Preston-style has an adjustment screw to flex the blade for optimal cutting. It works identically to a card scraper but reduces thumb fatigue over large surfaces. The Lie-Nielsen No. 80 and Veritas cabinet scrapers are the classic examples. Use a cabinet scraper to flatten areas too large for hand-held card scraping and for final prep before finishing on solid wood surfaces.',
  },
  {
    id: 'ma-marking-gauge-types',
    topic: 'Marking gauge, cutting gauge, mortise gauge',
    keywords: ['marking','gauge','cutting','mortise','pin','wheel','knife','fence','set'],
    answer: 'A marking gauge scribes a line parallel to an edge. A cutting gauge has a knife blade rather than a pin, cutting cleanly across grain for shoulder lines. A mortise gauge has two adjustable pins to scribe both sides of a mortise in one stroke — set the gap to your mortise chisel width. Wheel-type gauges (Veritas, Japanese) stay sharp longer than pin types. Always score from the reference face so the gauge fence bears firmly on the datum surface.',
  },
  {
    id: 'ma-sliding-bevel-use',
    topic: 'Sliding bevel for transferring angles',
    keywords: ['sliding','bevel','angle','transfer','dovetail','mortise','protractor','set'],
    answer: 'The sliding bevel (bevel gauge) sets to any angle and locks there — you use it to transfer angles from one piece to another without measuring. Set it from a protractor, a known angle, or directly from the work. For dovetails, set the bevel to the desired ratio (1:6 or 1:8) using a simple geometric method: mark 6 or 8 units along the grain and 1 unit across the edge, connect with the bevel, and lock. The sliding bevel is also useful for setting blade tilts on the table saw and bandsaw.',
  },
  {
    id: 'ma-winding-sticks-use',
    topic: 'Winding sticks for detecting twist',
    keywords: ['winding','stick','twist','wind','flat','parallel','sight','panel'],
    answer: 'Winding sticks are parallel straight sticks placed across opposite ends of a board. Sight from one end across the two sticks — if they appear parallel, the board is flat; if one end is higher, the board is in wind (twisted). The sticks amplify the twist optically. Mark the high corners with chalk and plane them down until the sticks appear perfectly level with each other. Inlay contrasting strips on one stick to make the misalignment easier to see.',
  },
  {
    id: 'ma-rip-saw-technique',
    topic: 'Hand rip saw technique and tooth geometry',
    keywords: ['rip','saw','tooth','angle','file','set','stroke','grain','hand'],
    answer: 'Rip saws have teeth filed at 90° across the face (like tiny chisels), optimized for cutting with the grain by paring fibers. The efficient stroke angle is 45°–60° to the workpiece. Start the cut by pulling to establish a kerf, then push strokes do the cutting. A sharp rip saw removes a surprising amount of material quickly. Dull rip saws require more force and wander; have them filed by a saw sharpener or learn to file and set teeth yourself.',
  },
  {
    id: 'ma-crosscut-saw-technique',
    topic: 'Crosscut saw tooth geometry and use',
    keywords: ['crosscut','saw','tooth','knife','bevel','file','angle','clean'],
    answer: 'Crosscut saws have teeth beveled to knife across fibers, producing a clean crosscut without splintering. Western-style crosscut saws cut on the push stroke; Japanese crosscut saws (ryoba) cut on the pull stroke with teeth that fold cleanly. For fine joinery crosscuts (tenon shoulders, dovetail baselines), use a dovetail saw or a fine-toothed Japanese saw. The critical thing is starting accurately — use a knife wall or guide block rather than a pencil line.',
  },
  {
    id: 'ma-dovetail-saw-detail',
    topic: 'Dovetail saw characteristics and alternatives',
    keywords: ['dovetail','saw','thin','fine','kerf','back','spine','joint','control'],
    answer: 'A dovetail saw is a small back saw with a thin plate (0.020"–0.025" kerf) and fine teeth (15–20 TPI). The stiff spine keeps the cut straight without needing much hand pressure. For through dovetails, a 20 TPI dovetail saw leaves a clean, thin kerf with minimal waste. Japanese dozuki saws are a fine alternative with very thin plates and pull-cutting action. Whatever you choose, the saw must be sharp — a dull saw drifts and requires pressure that wanders the cut.',
  },
  {
    id: 'ma-mortise-chisel-heavy',
    topic: 'Mortise chisels for heavy paring work',
    keywords: ['mortise','chisel','thick','heavy','lever','mallet','square','back'],
    answer: 'Mortise chisels have thick blades and robust handles designed to withstand mallet blows and levering out waste chips. The thick cross-section resists sideways flex during paring. Common widths: 1/4", 5/16", 3/8", 1/2". Always work to a scribed gauge line, chop halfway down, flip the board, and chop from the other side to meet in the middle. Never lever against the finished mortise wall — lever against the waste side to protect the layout lines.',
  },
  {
    id: 'ma-paring-chisel-detail',
    topic: 'Paring chisel for fine fitting work',
    keywords: ['paring','chisel','thin','long','hand','pressure','dovetail','hinge','fit'],
    answer: 'Paring chisels are thin, long, and driven by hand pressure only (never a mallet) — they\'re for fine fitting, cleaning dovetail corners, and trimming hinge mortises. A 1/8" paring chisel reaches into dovetail corners; a wide 1" is excellent for cleaning up flat mortise walls and tenon shoulders. Keep paring chisels at a lower bevel angle (15°–20°) than bench chisels for easier slicing. Never use a mallet on a paring chisel — the thin blade isn\'t designed for it.',
  },
  {
    id: 'ma-bench-chisel-set',
    topic: 'Bench chisel selection for a starter set',
    keywords: ['bench','chisel','set','starter','size','1/4','1/2','3/4','1'],
    answer: 'A practical starter chisel set: 1/4", 1/2", 3/4", and 1" bench chisels cover the vast majority of joinery work. The 1/4" is for small mortises and corner work; the 1/2" handles most mortises; the 3/4" and 1" are for paring and fitting wide joints. Buy a mid-tier set (Stanley 750 or equivalent, or a two-cherries set) rather than big-box chisels — cheap chisels hold an edge for minutes. Avoid complete sets of 10 — you\'ll use 4 chisels 90% of the time.',
  },
  {
    id: 'ma-coping-saw-use',
    topic: 'Coping saw for curves and interior cutouts',
    keywords: ['coping','saw','blade','curve','interior','pierce','scroll','fretwork'],
    answer: 'A coping saw has a thin blade tensioned in a C-frame, allowing curves and interior cuts (pierce through a drilled hole and reassemble the saw). The blade can be rotated in the frame for cutting in any direction. It\'s the hand-tool version of a scroll saw. Tension matters — too loose, the blade wanders; too tight, it snaps. Japanese-style kugihiki saws with flexible blades are often used for flush-cutting through tenons and dowels.',
  },
  {
    id: 'ma-drawknife-spokeshave',
    topic: 'Drawknife and spokeshave for shaped work',
    keywords: ['drawknife','spokeshave','chair','leg','curve','shaping','green','wood'],
    answer: 'The drawknife pulls toward you to hog off stock quickly — used for green woodworking, shaping chair legs and rungs, and rough-profiling curved work. The spokeshave is like a narrow-soled plane with handles on both sides, refined for smoothing curves after the drawknife. Flat-soled spokeshaves work convex curves; round-soled spokeshaves work concave. Chair makers rely on both to shape legs, stretchers, and back slats efficiently.',
  },
  {
    id: 'ma-hand-saw-starting',
    topic: 'Starting a hand saw cut accurately',
    keywords: ['start','saw','cut','knife','notch','guide','pull','stroke','chisel'],
    answer: 'To start a hand saw accurately: knife the line first (don\'t use pencil for joinery), then use your thumbnail or a guide block to register the saw. Pull two or three light strokes toward you to establish a kerf notch, then switch to push strokes. For crosscuts with no guide, place your thumb knuckle against the saw blade as a fence. Always check that the saw is vertical using the reflection from the side of the plate — a slight reflection error reveals lean.',
  },
  {
    id: 'ma-hand-plane-grain-direction',
    topic: 'Planing with grain direction — reading the arrows',
    keywords: ['plane','grain','direction','tearout','uphill','downhill','arrow','read'],
    answer: 'Plane in the direction the grain runs "downhill" — look at the edge of the board and observe the grain lines. If they slope up from left to right, plane right to left (going with the slope). Planing against the grain lifts fibers rather than slicing them, causing tearout. On quartersawn and figured wood, grain direction changes — reduce depth of cut, use a tighter mouth, or use a card scraper instead. When in doubt, take a test cut and observe whether shavings roll smoothly or fibers tear.',
  },
  {
    id: 'ma-hand-plane-setup',
    topic: 'Setting up a bench plane for the first time',
    keywords: ['plane','setup','flatten','sole','frog','chip','breaker','lateral','adjust'],
    answer: 'New bench planes often need the sole flattened — rub on a sheet of 120 grit paper on a flat surface (granite plate or glass) in figure-8 patterns. Flatten the back of the iron on your sharpening stones before establishing the bevel. Set the chip breaker close to the edge (1/16") for smooth hardwood work. Adjust the frog forward for a tighter mouth. Final check: sight down the sole from the toe — the iron should be visible as a fine, even sliver across the full width.',
  },
  {
    id: 'ma-scratch-stock',
    topic: 'Scratch stock for custom profiles',
    keywords: ['scratch','stock','profile','moulding','custom','file','scraper','tool'],
    answer: 'A scratch stock is a homemade tool: a steel scraper filed to the desired profile, mounted in a notched wood handle. Drag it along the edge of a board with even pressure to produce a consistent moulding profile. You can make any profile you want — bead, cove, ogee, or complex combinations — by filing the scraper to shape. It works slowly but with total control and zero tearout. Excellent for small mouldings on curved work where routers can\'t safely reach.',
  },
  {
    id: 'ma-hand-saw-maintenance',
    topic: 'Hand saw care and when to have it resharpened',
    keywords: ['hand','saw','sharpen','set','tooth','maintain','file','joint'],
    answer: 'Modern panel saws with hardened teeth (coated gray) can\'t be resharpened with a file — replace them when dull. Traditional hand saws with soft steel teeth are jointed, shaped, set, and filed on a regular cycle. Signs a saw needs work: it requires more effort, drifts in the cut, or leaves a rough surface. Basic maintenance: wipe the blade with an oily rag after use to prevent rust. Hang saws on the wall (tooth-up) rather than stacking them — contact dulls and bends teeth.',
  },
  {
    id: 'ma-mallet-types',
    topic: 'Wooden mallet vs rubber mallet for chisels',
    keywords: ['mallet','wooden','rubber','dead','blow','chisel','joinery','assembly'],
    answer: 'Traditional wooden mallets have heavy lignum vitae or beech heads that deliver crisp, controlled blows to chisel handles without rebounding energy back into your arm. Rubber/dead-blow mallets are good for assembly — their sand-filled heads reduce rebound that could knock a joint loose. Never use a steel hammer directly on a chisel handle — you\'ll mushroom the end. For mortise work, a weight of 16–20 oz is comfortable; heavier mallets are tiring for extended chopping.',
  },
  {
    id: 'ma-marking-knife-types',
    topic: 'Marking knife types and what to look for',
    keywords: ['marking','knife','bevel','single','double','japanese','line','accurate'],
    answer: 'A single-bevel marking knife (flat back, angled front) registers directly against a square or template — the flat back sits flush against the guide. A double-bevel knife can\'t do this; it rides up on the bevel and moves the line outward. Good marking knives are stiff (no flex) and hold a keen edge. Many woodworkers use a Japanese laminated blade — hard steel edge, soft steel body — that sharpens easily and holds longer than standard steel.',
  },
  {
    id: 'ma-story-pole-practice',
    topic: 'Making and using a story pole',
    keywords: ['story','pole','stick','layout','repeat','measure','transfer','kitchen','cabinet'],
    answer: 'A story pole is a thin stick (1/4" x 2" typically) on which you mark all the key dimensions of a project directly — no numbers, just marks and labels. For a kitchen cabinet run, mark every cabinet width, shelf position, door gap, and hardware location. Transfer these marks directly to the stock rather than re-measuring each time. Story poles eliminate cumulative tape measure error and speed up repetitive layout in large projects. Mark the stick with a marking knife for precision.',
  },
  {
    id: 'ma-travisher',
    topic: 'Travisher for hollowing chair seats',
    keywords: ['travisher','chair','seat','hollow','windsor','round','curved','compass'],
    answer: 'A travisher is a curved-sole spokeshave-like tool used to hollow the seat of Windsor and slab-seat chairs. Its convex sole curves in two planes, allowing it to work in all directions across a hollowed seat. Work from the edges toward the center, then refine with a card scraper. The hollow depth in a Windsor seat is typically 3/4"–1" at the deepest point. A travisher in skilled hands produces a smooth hollow in 20 minutes; a grinder and sanding drum take longer and are harder to control.',
  },
  {
    id: 'ma-dividers-spacing',
    topic: 'Using dividers for even spacing and proportions',
    keywords: ['dividers','compass','spacing','divide','even','dovetail','shelf','pin'],
    answer: 'Dividers (wing compasses) transfer distances without arithmetic. To divide a space into equal parts: set the dividers to your best guess, walk them across the space, and adjust by the error divided by the number of steps — repeat until they land exactly. Use dividers to space dovetails evenly, lay out shelf pin holes, transfer mortise positions from story poles, and mark circles for turning centers. Keep a second pair set to your most-used increment (like 32mm).',
  },
  {
    id: 'ma-spokeshave-setup',
    topic: 'Setting up and using a spokeshave',
    keywords: ['spokeshave','setup','adjust','blade','flat','round','chair','rung'],
    answer: 'Spokeshave blades are tiny — sharpen them like a plane iron on a stone, keeping the bevel flat. The cap iron screw controls blade depth; use a fine screwdriver to set it. Push-style spokeshaves need the blade to protrude just a whisker. Pull-style cut on the pull stroke. Always work with the grain on convex curves. On concave surfaces, you often need to work from both directions. A round-soled spokeshave (for concaves) and flat-soled (for convex) are the two essential types.',
  },
  {
    id: 'ma-hand-tool-shop-layout',
    topic: 'Setting up a hand tool friendly shop',
    keywords: ['hand','tool','shop','bench','height','layout','quiet','light','space'],
    answer: 'A hand tool shop needs less space and less noise than a power tool shop. Bench height is critical — your bench top should be at your first knuckle when you stand with arms at your sides. Good lighting from the side (raking light) reveals surface defects. A solid workbench that doesn\'t move under heavy planing is non-negotiable. Organize tools on the wall above the bench — the fewer steps between tool and bench, the faster you work.',
  },
  {
    id: 'ma-shaving-horse',
    topic: 'Shaving horse for green woodworking',
    keywords: ['shaving','horse','drawknife','green','wood','foot','pedal','clamp','free'],
    answer: 'A shaving horse is a foot-operated clamping bench that holds work for the drawknife — your foot pressure on the pedal drives a pivoting head that clamps the workpiece. Releasing foot pressure frees the work instantly for repositioning. It\'s ideal for shaping chair spindles, tool handles, and rungs from green (unseasoned) wood. Green wood is much easier to shape than dry wood. Build your own shaving horse — they\'re simple construction projects with dozens of available plans.',
  },
];
