import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_O: KnowledgeEntry[] = [
  // ── WOOD SPECIES: HARDWOODS ──────────────────────────────────────────────
  {
    id: 'mo-species-red-oak',
    topic: 'Red oak — properties and uses',
    keywords: ['red', 'oak', 'species', 'hardwood', 'grain', 'porous', 'furniture'],
    answer: 'Red oak is a hard, strong, open-grained hardwood with a pinkish-tan color and bold, straight grain. It takes stain evenly but can look blotchy with very dark stains, and its open pores make it a poor choice for anything meant to hold liquid (its grain is actually porous enough to blow air through end grain). It is affordable, widely available, and a common choice for furniture, cabinets, and flooring. Consider it a common rule-of-thumb "workhorse hardwood" — moderate cost, moderate difficulty to work.',
  },
  {
    id: 'mo-species-white-oak',
    topic: 'White oak — properties and uses',
    keywords: ['white', 'oak', 'species', 'hardwood', 'outdoor', 'tannin', 'durable'],
    answer: 'White oak is closely related to red oak but has closed pores (tyloses) that make it naturally water-resistant, which is why it was historically used for barrels and boats. It has a golden-brown color, is very durable outdoors, and takes an oil finish beautifully thanks to its high tannin content. It is somewhat harder to work than red oak and typically costs a bit more. Good choice for outdoor furniture, boat trim, and traditional Arts & Crafts style pieces.',
  },
  {
    id: 'mo-species-hard-maple',
    topic: 'Hard maple (sugar maple) — properties and uses',
    keywords: ['hard', 'maple', 'sugar', 'species', 'hardwood', 'dense', 'butcher', 'block'],
    answer: 'Hard maple (sugar maple) is one of the densest common domestic hardwoods — very durable but tough on tool edges and hard to hand-cut. It has a pale cream color with a tight, subtle grain, and is prized for cutting boards, butcher blocks, workbenches, and flooring because it resists dents and wear so well. It can blotch badly with stain — a wood conditioner or dye is usually recommended before staining. Good for anything that needs to survive heavy daily use.',
  },
  {
    id: 'mo-species-soft-maple',
    topic: 'Soft maple — properties and uses',
    keywords: ['soft', 'maple', 'species', 'hardwood', 'affordable', 'painted'],
    answer: 'Soft maple (red maple or silver maple) is noticeably easier to cut and machine than hard maple while still being harder than most softwoods. It has similar pale color but sometimes with more mineral streaking. It is a good budget-friendly stand-in for hard maple on painted projects, and works well for furniture where you do not need butcher-block-level wear resistance.',
  },
  {
    id: 'mo-species-black-walnut',
    topic: 'Black walnut — properties and uses',
    keywords: ['black', 'walnut', 'species', 'hardwood', 'dark', 'premium', 'furniture'],
    answer: 'Black walnut is a premium American hardwood with a rich chocolate-brown color, straight-to-wavy grain, and excellent workability with both hand and power tools. It is prized for fine furniture, cabinetry, and gunstocks, and machines and finishes beautifully with minimal blotching. It is one of the pricier domestic hardwoods, so many woodworkers use it as an accent (drawer fronts, inlay) paired with a cheaper secondary wood.',
  },
  {
    id: 'mo-species-cherry',
    topic: 'Cherry (black cherry) — properties and uses',
    keywords: ['cherry', 'black', 'species', 'hardwood', 'reddish', 'darken', 'aging'],
    answer: 'Cherry starts out a pale pinkish-tan and darkens dramatically to a rich reddish-brown over weeks to months of light exposure — a well-known quirk worth planning around (uneven sun exposure during a build can leave visible tan patches). It machines and sands easily, takes finishes beautifully with an oil or clear film finish, and is a classic choice for fine furniture. Avoid heavy stains that fight its natural color-change; most woodworkers just let cherry age naturally under a clear finish.',
  },
  {
    id: 'mo-species-white-ash',
    topic: 'White ash — properties and uses',
    keywords: ['white', 'ash', 'species', 'hardwood', 'tough', 'shock', 'handle', 'tool'],
    answer: 'White ash is a tough, flexible hardwood with excellent shock resistance, historically used for tool handles, baseball bats, and bent parts (it steam-bends very well). It has a light tan color with strong, open straight grain similar in look to oak but with a more even texture. Ash availability has dropped in many regions due to the emerald ash borer beetle, so check local supply before planning a large project around it.',
  },
  {
    id: 'mo-species-hickory',
    topic: 'Hickory — properties and uses',
    keywords: ['hickory', 'species', 'hardwood', 'hardest', 'domestic', 'tool', 'handle'],
    answer: 'Hickory is one of the hardest and toughest domestic hardwoods, historically the top choice for hammer and axe handles because of its shock resistance. It is difficult to hand-tool (very hard on edges) but produces a striking two-tone look (pale sapwood, brown heartwood) that is popular in rustic and farmhouse-style furniture and flooring. Plan on sharp carbide blades and slower feed rates when cutting it.',
  },
  {
    id: 'mo-species-yellow-birch',
    topic: 'Yellow birch — properties and uses',
    keywords: ['birch', 'yellow', 'species', 'hardwood', 'affordable', 'maple', 'substitute'],
    answer: 'Yellow birch is a pale, fine-grained hardwood similar in appearance and hardness to maple but usually less expensive. It machines and sands well and is a popular substitute where you want a maple-like look on a tighter budget. It can be prone to blotching with stain, same as maple, so a conditioner or gel stain helps even results.',
  },
  {
    id: 'mo-species-poplar',
    topic: 'Poplar (tulip poplar) — properties and uses',
    keywords: ['poplar', 'tulip', 'species', 'hardwood', 'cheap', 'paint', 'secondary'],
    answer: 'Poplar is a soft, inexpensive hardwood, easy to cut and sand, but often has a greenish or purplish streaky color that most woodworkers hide under paint rather than clear finish. It is a favorite "secondary wood" for drawer sides, painted cabinets, and shop jigs where strength matters more than looks. Not a good choice if you want a natural, unpainted look.',
  },
  {
    id: 'mo-species-mahogany',
    topic: 'Mahogany — properties and uses',
    keywords: ['mahogany', 'species', 'hardwood', 'premium', 'stable', 'boat', 'outdoor'],
    answer: 'Genuine mahogany (and African mahogany, a common substitute) is a reddish-brown hardwood prized for its stability — it moves very little with humidity changes — and its excellent workability with hand tools. It is a traditional choice for fine furniture, boat building, and musical instruments. Genuine (Honduran/Cuban) mahogany is increasingly restricted and pricey; African mahogany is a more available and affordable alternative with similar working properties.',
  },
  {
    id: 'mo-species-teak',
    topic: 'Teak — properties and uses',
    keywords: ['teak', 'species', 'hardwood', 'outdoor', 'oily', 'weather', 'boat'],
    answer: 'Teak is a naturally oily, weather-resistant hardwood, the classic choice for outdoor furniture and boat decking because it shrugs off moisture and resists rot without a finish. Its natural oils can interfere with glue bonds — wipe the glue surface with acetone or solvent before gluing teak. It is one of the more expensive woods available and can dull blades faster than expected due to embedded silica.',
  },
  {
    id: 'mo-species-beech',
    topic: 'Beech — properties and uses',
    keywords: ['beech', 'species', 'hardwood', 'workbench', 'steam', 'bend', 'dense'],
    answer: 'Beech is a dense, fine-grained, pale hardwood traditionally used for workbenches, hand plane bodies, and steam-bent chair parts (it bends exceptionally well). It has a bit of a bland, uniform look, which is why it is more often used structurally or painted than as a showcase wood. It machines cleanly and takes glue well.',
  },
  {
    id: 'mo-species-alder',
    topic: 'Alder — properties and uses',
    keywords: ['alder', 'species', 'hardwood', 'soft', 'cabinet', 'stain'],
    answer: 'Alder is a soft, lightweight hardwood (softer than most softwoods, confusingly) that is easy to work and takes stain evenly, making it a popular budget alternative to cherry for cabinetry. Its light tan-pink color and subtle grain make it a good stand-in wherever you want an even, workable wood without maple\'s blotching tendency.',
  },
  {
    id: 'mo-species-padauk',
    topic: 'Padauk — properties and uses',
    keywords: ['padauk', 'species', 'exotic', 'hardwood', 'orange', 'color', 'fade'],
    answer: 'African padauk is famous for its vivid orange-red color when freshly cut, which mellows to a deep brown over months of light exposure — the color shift is dramatic and worth planning for (a UV-inhibiting finish slows but does not stop it). It is moderately hard, works reasonably well with sharp tools, and is popular for accent strips, inlay, and turned items where the bold color is the point.',
  },
  {
    id: 'mo-species-purpleheart',
    topic: 'Purpleheart — properties and uses',
    keywords: ['purpleheart', 'species', 'exotic', 'hardwood', 'purple', 'dense', 'burn'],
    answer: 'Purpleheart is a very dense, hard exotic wood that is genuinely purple when freshly cut, darkening toward brown-purple over time. It is prone to burning on the table saw and router if feed rate is too slow, and its density is hard on tool edges — sharp carbide is a must. Popular for accent strips and inlay where the striking color is the whole point.',
  },
  {
    id: 'mo-species-wenge',
    topic: 'Wenge — properties and uses',
    keywords: ['wenge', 'species', 'exotic', 'hardwood', 'dark', 'splinter', 'dust'],
    answer: 'Wenge is a very dark brown-black, coarse-grained exotic hardwood, hard and abrasive on tools, and notorious for producing sharp, splinter-prone edges — wear gloves when handling rough-sawn pieces. Its dust is also a common respiratory and skin irritant for some people, so extra dust control (mask, good extraction) is a good idea when machining it. Used for bold, modern-look accents and furniture.',
  },
  {
    id: 'mo-species-sapele',
    topic: 'Sapele — properties and uses',
    keywords: ['sapele', 'species', 'exotic', 'hardwood', 'mahogany', 'ribbon', 'grain'],
    answer: 'Sapele is an African hardwood often used as a mahogany alternative, with a reddish-brown color and a distinctive interlocked "ribbon" grain that can tear out if planed against the grain — light passes or a sharp scraper help. It is reasonably stable and takes finishes well, and is a popular choice for veneers, doors, and fine furniture.',
  },
  {
    id: 'mo-species-basswood',
    topic: 'Basswood — properties and uses',
    keywords: ['basswood', 'species', 'hardwood', 'carving', 'soft', 'lightweight'],
    answer: 'Basswood is a very soft, lightweight, close-grained hardwood — technically a hardwood by leaf type, but softer to cut than most softwoods. It is the top choice for hand carving because it cuts cleanly in any grain direction with minimal tearout, and it is also used for models, patterns, and light-duty shop jigs. Not a good structural or show wood — it dents and marks easily.',
  },
  {
    id: 'mo-species-butternut',
    topic: 'Butternut — properties and uses',
    keywords: ['butternut', 'species', 'hardwood', 'soft', 'walnut', 'carving'],
    answer: 'Butternut (white walnut) is a soft, light-colored relative of black walnut, easy to carve and work but soft enough to dent easily, so it is a poor choice for high-wear surfaces. It is increasingly scarce due to a fungal blight affecting butternut trees, so treat available stock as somewhat special.',
  },
  {
    id: 'mo-species-elm',
    topic: 'Elm — properties and uses',
    keywords: ['elm', 'species', 'hardwood', 'interlocked', 'grain', 'bending', 'chair'],
    answer: 'Elm has a distinctive interlocked grain that makes it very resistant to splitting, which is why it was historically used for chair seats, wheel hubs, and other parts that take repeated stress. That same interlocked grain makes it harder to plane cleanly and prone to warping as it dries, so careful stock selection and slow drying matter more than usual.',
  },
  {
    id: 'mo-species-sycamore',
    topic: 'Sycamore — properties and uses',
    keywords: ['sycamore', 'species', 'hardwood', 'quartersawn', 'fleck', 'lace'],
    answer: 'Sycamore is a pale, fine-textured hardwood that is unremarkable when flatsawn but shows a striking flecked "lacewood" figure when quartersawn, because of its prominent ray cells. It is moderately easy to work and is popular for veneer, decorative panels, and turned bowls where the quartersawn figure can shine.',
  },
  {
    id: 'mo-species-osage-orange',
    topic: 'Osage orange — properties and uses',
    keywords: ['osage', 'orange', 'species', 'hardwood', 'bow', 'hard', 'durable'],
    answer: 'Osage orange is an extremely hard, dense, naturally rot-resistant domestic hardwood with a bright yellow-orange color that mellows to brown over time. It was the traditional wood of choice for archery bows because of its combination of strength and flexibility. It is hard on tools and not widely available at typical lumberyards — more of a specialty/hobbyist wood sourced from small mills.',
  },
  {
    id: 'mo-species-black-locust',
    topic: 'Black locust — properties and uses',
    keywords: ['black', 'locust', 'species', 'hardwood', 'outdoor', 'durable', 'rot'],
    answer: 'Black locust is one of the most rot-resistant domestic hardwoods, often used untreated for fence posts and outdoor structures, and it rivals hickory for hardness and toughness. It is difficult to work with hand tools due to its density, but a good choice for outdoor furniture where you want longevity without chemical treatment.',
  },
  {
    id: 'mo-species-cottonwood',
    topic: 'Cottonwood — properties and uses',
    keywords: ['cottonwood', 'species', 'hardwood', 'soft', 'lightweight', 'utility'],
    answer: 'Cottonwood is a soft, fast-growing hardwood, inexpensive but with a somewhat fuzzy grain that can be hard to get a clean finish on — a sharp blade and light sanding passes help. It is generally used for utility purposes (pallets, crates, rough shelving) rather than fine furniture.',
  },
  // ── WOOD SPECIES: SOFTWOODS ──────────────────────────────────────────────
  {
    id: 'mo-species-syp',
    topic: 'Southern yellow pine — properties and uses',
    keywords: ['southern', 'yellow', 'pine', 'syp', 'species', 'softwood', 'construction', 'strong'],
    answer: 'Southern yellow pine is a dense, strong, resinous softwood, commonly sold as construction lumber (2x4s, 2x6s, etc.) and prized for structural strength relative to cost. Its resin content can gum up blades faster than other softwoods, and it takes stain unevenly due to alternating hard/soft grain bands — expect a wood conditioner if you want an even stained look.',
  },
  {
    id: 'mo-species-white-pine',
    topic: 'Eastern white pine — properties and uses',
    keywords: ['eastern', 'white', 'pine', 'species', 'softwood', 'soft', 'easy', 'work'],
    answer: 'Eastern white pine is a soft, lightweight, easy-to-work softwood with a pale color and straight grain, popular for beginner projects, shelving, and traditional furniture (it was the primary wood of early American furniture). It dents easily and can blotch badly with stain — many woodworkers finish it clear or paint it rather than fight the blotching.',
  },
  {
    id: 'mo-species-douglas-fir',
    topic: 'Douglas fir — properties and uses',
    keywords: ['douglas', 'fir', 'species', 'softwood', 'structural', 'strong', 'straight'],
    answer: 'Douglas fir is a strong, stiff structural softwood with a pronounced straight grain and reddish-tan color, widely used in framing lumber and increasingly popular for rustic/modern furniture and beams. It has alternating hard/soft grain rings that can telegraph through paint over time and make hand planing a bit trickier than pine.',
  },
  {
    id: 'mo-species-spf',
    topic: 'Spruce-pine-fir (SPF) — properties and uses',
    keywords: ['spruce', 'spf', 'species', 'softwood', 'construction', 'cheap', 'stud'],
    answer: 'SPF (spruce-pine-fir) is a catch-all grading category for construction lumber from several similar softwood species, sold as dimensional lumber (2x4, 2x6, etc.) at big box stores. It is inexpensive and adequate for shop furniture, jigs, and rough framing, but tends to be less stable (more prone to warping/twisting) than kiln-dried hardwood, so sight down each board before buying.',
  },
  {
    id: 'mo-species-western-red-cedar',
    topic: 'Western red cedar — properties and uses',
    keywords: ['western', 'red', 'cedar', 'species', 'softwood', 'outdoor', 'rot', 'resistant'],
    answer: 'Western red cedar is a lightweight, naturally rot- and insect-resistant softwood, the classic choice for outdoor furniture, fencing, and siding because it holds up outdoors without chemical treatment. It is soft and dents easily, and its natural oils can bleed through some paints — an oil-based primer helps if painting.',
  },
  {
    id: 'mo-species-aromatic-cedar',
    topic: 'Aromatic red cedar — properties and uses',
    keywords: ['aromatic', 'red', 'cedar', 'species', 'softwood', 'closet', 'chest', 'moth'],
    answer: 'Aromatic red cedar (a different species from western red cedar) is the fragrant, reddish-and-cream-streaked wood used for lining closets and cedar chests — the scent is a natural moth deterrent. It is soft, brittle, and usually sold in narrow, knotty boards, so it is typically used as thin lining panels rather than structural furniture parts.',
  },
  {
    id: 'mo-species-redwood',
    topic: 'Redwood — properties and uses',
    keywords: ['redwood', 'species', 'softwood', 'outdoor', 'rot', 'resistant', 'deck'],
    answer: 'Redwood is a lightweight, naturally decay-resistant softwood popular for decking, outdoor furniture, and planters, prized for its rich reddish color and stability. It is relatively soft and can be pricier than treated pine, but needs no chemical treatment to handle outdoor exposure well.',
  },
  {
    id: 'mo-species-hemlock',
    topic: 'Hemlock — properties and uses',
    keywords: ['hemlock', 'species', 'softwood', 'construction', 'stiff'],
    answer: 'Hemlock is a moderately hard softwood, stiffer than many pines, often used interchangeably with fir for framing and occasionally for interior trim. It has a somewhat bland, straight grain and is not a common furniture-grade choice, but works fine for shop projects and utility builds.',
  },
  {
    id: 'mo-species-ponderosa-pine',
    topic: 'Ponderosa pine — properties and uses',
    keywords: ['ponderosa', 'pine', 'species', 'softwood', 'knotty', 'furniture'],
    answer: 'Ponderosa pine is a soft, easy-working pine with a more open, sometimes knotty grain pattern, popular for rustic furniture, paneling, and millwork in the western US. Like other pines, it can blotch with stain — a pre-stain conditioner or gel stain gives more even results.',
  },
  // ── SHEET GOODS & ENGINEERED MATERIALS ──────────────────────────────────
  {
    id: 'mo-material-baltic-birch',
    topic: 'Baltic birch plywood — what it is and why woodworkers like it',
    keywords: ['baltic', 'birch', 'plywood', 'sheet', 'good', 'void', 'free', 'edge'],
    answer: 'Baltic birch plywood is a premium plywood made entirely of thin birch veneer layers with no soft core or voids, giving it a strong, attractive edge that looks good even unfinished — great for shop jigs, drawer boxes, and Scandinavian-style furniture. It costs more than standard plywood but is worth it whenever the plywood edge will be visible or the piece needs maximum strength for its thickness.',
  },
  {
    id: 'mo-material-cabinet-plywood',
    topic: 'Cabinet-grade hardwood plywood — what it is',
    keywords: ['cabinet', 'grade', 'plywood', 'veneer', 'core', 'sheet', 'good'],
    answer: 'Cabinet-grade plywood has a thin hardwood veneer (oak, maple, birch, walnut, etc.) glued to a plywood or MDF core, giving you a matching-species surface at a fraction of solid wood cost and with far better dimensional stability across wide panels. It is the standard choice for cabinet sides, doors, and large flat panels where solid wood would be prone to cupping.',
  },
  {
    id: 'mo-material-mdf',
    topic: 'MDF (medium-density fiberboard) — properties and uses',
    keywords: ['mdf', 'medium', 'density', 'fiberboard', 'sheet', 'good', 'paint', 'flat'],
    answer: 'MDF is an engineered sheet material made of compressed wood fibers and resin — extremely flat, stable, and smooth, with no grain or knots, making it ideal for painted furniture, speaker boxes, and router templates. It is heavy, dulls blades faster than plywood, and swells badly if it gets wet, so it is not a good choice for anything exposed to moisture.',
  },
  {
    id: 'mo-material-particleboard',
    topic: 'Particleboard — properties and uses',
    keywords: ['particleboard', 'chipboard', 'sheet', 'good', 'cheap', 'weak'],
    answer: 'Particleboard is the cheapest common sheet good, made from compressed wood chips and resin. It is weaker and less screw-holding than plywood or MDF and swells badly with moisture, so it is mostly used for budget flat-pack furniture, shelving under light loads, and as a substrate under laminate countertops.',
  },
  {
    id: 'mo-material-osb',
    topic: 'OSB (oriented strand board) — properties and uses',
    keywords: ['osb', 'oriented', 'strand', 'board', 'sheet', 'good', 'construction'],
    answer: 'OSB is a structural sheet good made of large wood strands compressed and glued in layers, used mainly for construction (roof/wall sheathing, subfloors) rather than furniture, because of its rough appearance and coarse edges. It is strong for its cost but generally not chosen for anything with a visible finished surface.',
  },
  {
    id: 'mo-material-veneer',
    topic: 'Wood veneer — what it is and how it is used',
    keywords: ['veneer', 'thin', 'sheet', 'glue', 'substrate', 'sequenced', 'match'],
    answer: 'Veneer is a thin sheet of real wood (often less than 1/32" thick) glued to a stable substrate like plywood or MDF, letting you get the look of expensive or figured wood at a fraction of the solid-lumber cost while gaining much better stability across wide panels. Sequenced veneer sheets from the same log can be arranged (book-matched, slip-matched) for symmetrical grain patterns on doors and panels.',
  },
  // ── GENERAL SPECIES/MATERIAL CONCEPTS ───────────────────────────────────
  {
    id: 'mo-janka-hardness',
    topic: 'What Janka hardness means and why it matters',
    keywords: ['janka', 'hardness', 'scale', 'rating', 'durable', 'dent', 'resistance'],
    answer: 'Janka hardness is a standard test rating how much force it takes to embed a steel ball halfway into a wood sample — in practice, a higher-rated wood resists dents and wear better (good for floors and tabletops) but is also harder on saw blades, router bits, and hand tools. As a common rule of thumb: pine and cedar are soft, oak and maple are medium-hard, and hickory and exotic hardwoods like ipe or wenge are very hard. Match the wood\'s hardness to how much abuse the finished piece will take.',
  },
  {
    id: 'mo-workability-rating',
    topic: 'What "workability" means when choosing a wood species',
    keywords: ['workability', 'work', 'easy', 'hard', 'beginner', 'species', 'choose'],
    answer: 'Workability describes how easily a wood cuts, planes, sands, glues, and finishes with typical shop tools — softer, straighter-grained woods like pine, poplar, and alder are generally more forgiving for beginners, while dense or interlocked-grain woods like hickory, wenge, or purpleheart demand sharper tools and more careful technique. If you are newer to woodworking, choosing an easy-to-work species for your first few projects will save a lot of frustration, independent of how the wood looks.',
  },
  {
    id: 'mo-cost-tier-woods',
    topic: 'Wood cost tiers — budget, mid-range, premium',
    keywords: ['cost', 'price', 'budget', 'premium', 'expensive', 'cheap', 'species'],
    answer: 'As a rough rule of thumb: construction-grade softwoods (pine, SPF, fir) are the cheapest option and best for practice pieces and shop furniture; domestic hardwoods (oak, maple, poplar, ash) sit in the mid-range and are the workhorses of most furniture projects; premium domestic woods (walnut, cherry) and imported exotics (padauk, wenge, purpleheart, teak) cost significantly more and are usually reserved for accent pieces, small projects, or when the client/project budget supports it.',
  },
  {
    id: 'mo-sustainability-fsc',
    topic: 'Sustainable lumber sourcing and FSC certification',
    keywords: ['sustainable', 'fsc', 'certified', 'sourcing', 'responsible', 'forestry'],
    answer: 'FSC (Forest Stewardship Council) certification is a widely recognized label indicating lumber was harvested under responsible forestry practices — look for it on lumber tags if sustainable sourcing matters to you. Domestic species like oak, maple, poplar, and pine are generally more sustainably farmed than tropical exotics; when buying exotic species, ask your supplier about sourcing and consider whether a domestic substitute (e.g. walnut instead of an endangered rosewood) would work just as well.',
  },
  {
    id: 'mo-exotic-wood-cites',
    topic: 'Exotic wood legality and CITES restrictions',
    keywords: ['exotic', 'cites', 'legal', 'restricted', 'import', 'endangered', 'rosewood'],
    answer: 'Some exotic species (many true rosewoods, some ebony, Brazilian mahogany) are restricted under CITES, an international treaty regulating trade in endangered species — buying, selling, or shipping these across borders can require documentation or may be outright restricted. Buy exotic lumber from a reputable supplier who can confirm legal sourcing, and double check current CITES status before planning a project or shipping a finished piece internationally.',
  },
  {
    id: 'mo-wood-dust-toxicity',
    topic: 'Wood dust toxicity and allergy considerations',
    keywords: ['dust', 'toxic', 'allergy', 'respiratory', 'sensitizer', 'mask', 'safety'],
    answer: 'Some species produce dust that is a known respiratory or skin irritant for a meaningful fraction of woodworkers — walnut, wenge, cocobolo, padauk, and many exotic species are commonly reported offenders, though sensitivity varies a lot by individual. Good dust collection and a properly rated respirator are worth using for any species, but especially exotics — if you notice unusual skin or breathing reactions after working a particular wood, stop and switch to better protection or a different species.',
  },
  {
    id: 'mo-sapwood-heartwood',
    topic: 'Sapwood vs heartwood — what the color difference means',
    keywords: ['sapwood', 'heartwood', 'color', 'difference', 'log', 'tree'],
    answer: 'Heartwood is the darker, denser wood from the center of the tree, generally more decay-resistant and the part usually prized for color and figure. Sapwood is the paler outer wood that was actively conducting sap in the living tree — it is often less durable and less colorfast, which is why a board with both sapwood and heartwood can look two-toned. For a uniform look, select boards that are mostly heartwood, or plan the sapwood into the design deliberately (some styles, like live-edge furniture, embrace it).',
  },
  {
    id: 'mo-quartersawn-flatsawn-rift',
    topic: 'Quartersawn, flatsawn, and rift-sawn lumber differences',
    keywords: ['quartersawn', 'flatsawn', 'rift', 'sawn', 'grain', 'cut', 'stability'],
    answer: 'How a log is sawn changes both the grain pattern and the wood\'s stability. Flatsawn (plainsawn) boards show cathedral-arch grain and are the most common/cheapest cut, but move the most across their width with humidity changes. Quartersawn boards show straighter grain lines (and flecked figure in oak) and are noticeably more stable — worth the extra cost for tabletops and door panels prone to cupping. Rift-sawn falls between the two, prized in modern/contemporary furniture for very straight, consistent grain lines with minimal figure.',
  },
  {
    id: 'mo-reclaimed-salvaged-wood',
    topic: 'Working with reclaimed or salvaged wood',
    keywords: ['reclaimed', 'salvaged', 'barn', 'wood', 'nail', 'metal', 'detector'],
    answer: 'Reclaimed wood (old barn beams, pallets, demolition lumber) can have great character but often hides embedded nails, screws, or grit that will destroy a blade — always run a metal detector over reclaimed stock before cutting, and expect to sacrifice a blade occasionally anyway. It also may need longer to acclimate and can have inconsistent moisture content, so give it extra time in your shop before final milling.',
  },
];
