import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_E: KnowledgeEntry[] = [
  // ── MORE WOOD SPECIES ────────────────────────────────────────────────────────
  {
    id: 'me-bocote',
    topic: 'Bocote — striking figure and working notes',
    keywords: ['bocote','striped','mexican','rosewood','figure','dark','brown','line'],
    answer: 'Bocote is a Mexican hardwood with bold dark brown stripes and swirling grain on a golden-tan background. It\'s moderately hard, finishes beautifully with oil, and turns to a glassy surface. The interlocked grain causes some tearout — take light passes and use sharp tools. It\'s popular for knife handles, inlay, guitar backs, and small accent pieces where the figure shows best.',
  },
  {
    id: 'me-zebrawood',
    topic: 'Zebrawood — appearance and workability',
    keywords: ['zebrawood','stripe','african','parallel','contrast','coarse','grain'],
    answer: 'Zebrawood has pale yellow-brown background with dark brown parallel stripes — among the boldest patterned hardwoods available. The coarse, interlocked grain causes significant tearout when planing. Use sharp tools and a scraper for final surfacing. The bold pattern can overwhelm a piece — use zebrawood as an accent rather than primary surface. It machines well with carbide and finishes nicely with oil or wiping varnish.',
  },
  {
    id: 'me-bubinga',
    topic: 'Bubinga characteristics and use',
    keywords: ['bubinga','african','rosewood','pink','red','heavy','drum','furniture'],
    answer: 'Bubinga is a large African tree producing wide, stable boards with pinkish-red to reddish-brown color. It\'s quite heavy (similar to hard maple) and machines well with sharp carbide tools. Wavy, interlocked grain creates a beautiful pomele figure on some logs. It\'s popular for tabletops, workbench tops, and drum shells because of its stability and attractive color. It can cause skin irritation in some people — wear gloves when sanding.',
  },
  {
    id: 'me-lignum-vitae',
    topic: 'Lignum vitae — densest commercial wood',
    keywords: ['lignum','vitae','dense','hard','self','lubricating','oily','bearing','sinker'],
    answer: 'Lignum vitae is the world\'s densest commercial wood — it sinks in water and self-lubricates due to natural resins. Historically used for ship bearings, mallets, and croquet balls. It\'s nearly impossible to work with hand tools; carbide is required. Today it\'s expensive and limited to specialty applications like ship propeller shaft bearings, bowls, and tool handles. Its extraordinary hardness means turned surfaces need almost no finish.',
  },
  {
    id: 'me-cocobolo',
    topic: 'Cocobolo beauty and extreme allergen risk',
    keywords: ['cocobolo','rosewood','allergen','sensitize','oil','color','red','orange','knives'],
    answer: 'Cocobolo is a Central American rosewood with stunning orange-red to purple-red color and intricate grain. It\'s one of the most allergenic woods known — even people with no prior sensitivities can develop severe reactions from dust or handling the oiled wood. Always wear gloves, a P100 respirator, and eye protection. The natural oils make gluing difficult — wipe with acetone before gluing. Its beauty makes it a prized choice for knife handles, guitar headstocks, and small decorative pieces.',
  },
  {
    id: 'me-ebony-types',
    topic: 'Ebony species — Gaboon, Macassar, African',
    keywords: ['ebony','gaboon','macassar','black','stripe','piano','key','inlay','rare'],
    answer: 'Gaboon ebony is solid jet-black and the classic ebony for piano keys, fingerboards, and decorative inlay. Macassar ebony has dramatic black-and-tan striping and is often more available than solid black. African ebony (Grenadilla) is used for woodwind instruments. All ebony is CITES-regulated, rare, and very expensive. It machines to a natural polish and needs almost no finish — oil enhances the black depth. Small sizes (pen blanks, turning squares) are more accessible than large boards.',
  },
  {
    id: 'me-olive-wood',
    topic: 'Olive wood figure and working',
    keywords: ['olive','wood','mediterranean','wavy','yellow','tan','brown','fragrant','turning'],
    answer: 'Olive wood has a warm golden to tan color with dramatic wavy dark streaks, a distinctive fragrant smell when cut, and very dense, fine grain. It\'s excellent for turning, small boxes, and utensils. The interlocked, wavy grain causes tearout — sharp tools and a light touch are essential. Olive wood is available mostly in small sizes from Mediterranean trees. It finishes beautifully with oil and has excellent natural resistance to moisture, making it traditional for kitchen utensils and cutting boards.',
  },
  {
    id: 'me-fruitwood',
    topic: 'Apple, pear, and cherry fruitwood characteristics',
    keywords: ['apple','pear','fruitwood','small','turning','carving','tight','grain','dense'],
    answer: 'Fruitwoods (apple, pear, plum, quince) share common traits: very tight, fine grain with minimal figure, warm pinkish-tan to reddish-brown color, and excellent workability for carving and turning. They\'re available only in small sizes because orchard trees are rarely large. Pear has the finest, most uniform grain and was historically used for rulers and precision instruments. Apple turns to a smooth, near-burnished surface. Source them from orchardists when old trees are removed — excellent urban salvage wood.',
  },
  {
    id: 'me-beech-steam',
    topic: 'Beech for steam bending and tool handles',
    keywords: ['beech','steam','bend','chair','german','tool','handle','lathe','stiff'],
    answer: 'Beech is the classic European steam-bending wood — the dense, straight-grained fibers bend more reliably than almost any other species. Traditional Windsor chairs in Europe used beech for the legs and arm bows. It\'s also the standard wood for hand planes, work bench tops, and European hand tools because of its toughness and stability under mallet blows. Beech moves significantly with humidity changes, so it\'s less ideal for fine furniture that must stay flat.',
  },
  {
    id: 'me-hornbeam',
    topic: 'Hornbeam — the hardest European hardwood',
    keywords: ['hornbeam','hard','european','plane','workbench','mallet','axle','wearing'],
    answer: 'Hornbeam (also called ironwood or musclewood) is the hardest European deciduous hardwood, used historically for plane soles, mallet heads, and gear teeth. The very fine, dense grain takes extreme wear without denting. It\'s difficult to find as sawn lumber but beloved by traditional toolmakers. American hornbeam (blue beech) is similar in properties but smaller. If you want to build a wooden-soled hand plane or a heavy mallet, hornbeam is the premium choice.',
  },
  {
    id: 'me-cypress-outdoor',
    topic: 'Bald cypress for outdoor use',
    keywords: ['bald','cypress','outdoor','rot','swamp','boat','stable','knot','knee'],
    answer: 'Bald cypress is a softwood with excellent rot resistance from natural oils (cypressene), making it historically important for boat building, exterior siding, and outdoor furniture in the American South. Old-growth cypress is exceptionally resistant; second-growth may have less oil and resistance. It machines easily, takes paint and stain well, and is relatively lightweight. Reclaimed cypress from old buildings or water-logged logs is especially prized for its density and figure.',
  },
  {
    id: 'me-teak-aging',
    topic: 'Teak color change and weathering',
    keywords: ['teak','silver','gray','age','weather','oil','refresh','maintain','outdoor'],
    answer: 'New teak is golden-brown with a slightly oily feel. Without treatment, UV exposure turns teak silver-gray within a season — a look many designers actively choose for outdoor teak furniture. To maintain the golden color, apply teak oil annually (after cleaning with teak cleaner to remove dirt and oxidation). To restore weathered gray teak, clean with oxalic acid-based teak brightener, sand lightly, then oil. The gray weathered look requires zero maintenance and is structurally fine — it\'s purely aesthetic preference.',
  },
  {
    id: 'me-mesquite',
    topic: 'Mesquite for furniture and turning',
    keywords: ['mesquite','southwest','dense','hard','figured','crack','small','board','texas'],
    answer: 'Mesquite is a dense, hard Southwestern hardwood with rich golden-brown to reddish-brown color, often with dramatic figure, knots, and natural voids. It\'s very heavy and hard on tools. Available mainly in smaller dimensions because mesquite trees are rarely large and straight. The high figure and natural character (voids, crotches) suit rustic and contemporary furniture and turning. Fill voids with tinted epoxy for a distinctive look.',
  },
  {
    id: 'me-sassafras',
    topic: 'Sassafras characteristics and aroma',
    keywords: ['sassafras','aromatic','light','soft','tea','root','furniture','reclaimed'],
    answer: 'Sassafras has a distinctive root beer or tea-like aromatic smell from natural safrole oils. It\'s a light, moderately soft hardwood with coarse grain similar to white ash. Historically used for furniture, boats, and barrels. The aroma fades after years of use but is strong when freshly cut. It\'s relatively uncommon as sawn lumber today — find it from local sawyers and urban tree sources. Light, relatively low density makes it comfortable to work with hand tools.',
  },
  {
    id: 'me-catalpa',
    topic: 'Catalpa — soft, light, and rot resistant',
    keywords: ['catalpa','light','soft','rot','outdoor','boat','coarse','open','grain'],
    answer: 'Catalpa is surprisingly rot-resistant for such a soft, lightweight wood. It\'s been used historically for fence posts and railroad ties precisely because of this combination of low density and high durability. The coarse, open grain and bold growth rings give it a rustic character. It finishes nicely for outdoor furniture and is increasingly popular in the Southeast for benches and garden furniture. It\'s faster-growing than most rot-resistant species, making it more sustainable.',
  },
  {
    id: 'me-LVL-glulam',
    topic: 'LVL and glulam engineered lumber',
    keywords: ['LVL','laminated','veneer','glulam','engineered','beam','span','structural','shop'],
    answer: 'LVL (Laminated Veneer Lumber) is made from thin veneers with all grain running parallel — essentially a very precise plywood-like beam. It\'s straighter, more uniform, and stronger than sawn lumber for the same dimension. Glulam (glued laminated timber) stacks dimension lumber with alternating grain orientations for very large beams. Both are used for long-span beams and structural shop applications where solid wood would be too heavy, too expensive, or not available in the required size. Glulam beams can be beautiful left exposed.',
  },
  {
    id: 'me-reclaimed-wood-processing',
    topic: 'Processing reclaimed lumber safely',
    keywords: ['reclaimed','barn','wood','nail','metal','detector','mill','old','growth'],
    answer: 'Old barn wood and reclaimed lumber contains hidden nails, screws, and metal from previous lives — they will destroy carbide blades and potentially be ejected at high speed. Always sweep boards with a strong magnet or handheld metal detector before milling. Mark any suspect areas. Use cheaper blades for the first rough milling pass. Reclaimed wood is often dry and stable (decades of seasoning) but may have embedded grit, paint, or surface contamination that dulls tools quickly. The payoff is character-rich, old-growth dense wood unavailable new.',
  },
  {
    id: 'me-pallet-wood',
    topic: 'Pallet wood — what it is and safety',
    keywords: ['pallet','wood','HT','MB','heat','treated','methyl','bromide','safe','paint'],
    answer: 'Shipping pallets marked "HT" are heat-treated and safe to use for woodworking. Pallets marked "MB" were treated with methyl bromide pesticide — avoid these entirely. Most modern US pallets are HT. Pallet wood is usually low-grade mixed hardwood (oak, maple, poplar) that\'s rough-sawn but surprisingly dry. Expect significant nail holes, surface grit, and rough edges — plan for extra milling. The rustic character is prized for furniture; the material is essentially free. Run through a metal detector first.',
  },
  {
    id: 'me-cork-natural',
    topic: 'Cork as a woodworking material',
    keywords: ['cork','stopper','wall','floor','gasket','compressible','natural','bark'],
    answer: 'Cork is harvested from the bark of cork oak trees without killing the tree — a sustainable material. In woodworking, cork sheet is used as drawer and shelf liners, tool handle wraps, and acoustic dampening in speaker cabinets. It\'s easily cut with a knife and glued with contact cement. For cabinet interiors, cork shelf liners prevent dishes and glasses from sliding. Cork is also used as the sacrificial surface on shooting boards and hand router plane bases.',
  },
  {
    id: 'me-bamboo-material',
    topic: 'Bamboo as a woodworking material',
    keywords: ['bamboo','grass','floor','cutting','board','strand','woven','hard','flat'],
    answer: 'Technically a grass, bamboo is used in woodworking as flooring, cutting boards, and sheet material. Strand-woven bamboo is extremely hard (Janka ~1380 or higher) — nearly as hard as hard maple. Flat-pressed bamboo is softer and lighter. Bamboo is dimensionally stable, grows rapidly (sustainable), and takes finishes well. For shop use, bamboo sheets are available as a plywood alternative. The glue lines between strands can be visible — embrace them as part of the look or select for minimal layering.',
  },

  // ── MORE JOINERY ─────────────────────────────────────────────────────────────
  {
    id: 'me-tusk-tenon',
    topic: 'Tusk tenon for removable joints',
    keywords: ['tusk','tenon','wedge','removable','key','drawbore','disassemble','mortise'],
    answer: 'A tusk tenon passes through the mortise and locks with a removable wedge-shaped key (the tusk) that passes through a slot in the projecting tenon. Tightening the key tightens the joint; removing it allows disassembly. Used historically for workbenches, sawhorses, and any furniture that needed to be portable. The key slot is angled so that the wedge drives the joint tight. Cut the slot farther from the shoulder than it needs to be, then trim to fit so the wedge pulls the joint fully closed.',
  },
  {
    id: 'me-coopering',
    topic: 'Coopering — stave construction for cylinders',
    keywords: ['coopered','stave','cylinder','barrel','drum','angle','bevel','glue','circle'],
    answer: 'Coopering assembles narrow staves with angled edges to form cylinders or curved shapes — think barrels, wooden drums, and coopered cabinet doors. Each stave edge is beveled at an angle that depends on the diameter and number of staves: bevel angle = 90° ÷ number of staves. Dry-fit all staves with a band clamp before gluing — the joints must close evenly all the way around. A caul made from pipe insulation or a bent metal band helps apply even pressure during glue-up.',
  },
  {
    id: 'me-bent-lamination',
    topic: 'Bent lamination for curved parts',
    keywords: ['bent','lamination','curve','thin','strip','form','glue','chair','rail'],
    answer: 'Bent lamination stacks thin strips of wood (1/8"–1/4" thick) glued together over a curved form. The thin strips bend easily without breaking; the glue locks them in the curved shape permanently. The form must be built to the inside radius of the finished piece. Apply glue to every face, stack the strips, and clamp firmly over the form for several hours. The spring-back (slight straightening as the blank is removed from the form) must be anticipated — build the form slightly tighter than the final radius to compensate.',
  },
  {
    id: 'me-kerf-bending',
    topic: 'Kerf bending for curves without lamination',
    keywords: ['kerf','bend','cut','curve','plywood','radius','calculate','spacing','panel'],
    answer: 'Kerf bending makes a straight panel flexible by sawing a series of parallel cuts nearly through the thickness. The remaining web of wood (typically 1/8"–3/16") bends while the uncut face provides a clean outer surface. Calculate spacing: the closer the kerfs, the tighter the possible bend radius. Test with a strip of the actual material to find the minimum radius before committing. Kerf-bent plywood is used for curved cabinet doors, stair risers, and architectural millwork. The kerf side faces inward (away from view).',
  },
  {
    id: 'me-angled-mortise',
    topic: 'Laying out angled mortises for chair legs',
    keywords: ['angled','mortise','chair','leg','compound','angle','splay','rake','layout'],
    answer: 'Chair legs typically splay outward in two directions simultaneously — splay (front-to-back) and rake (side-to-side) — requiring compound-angled mortises in the seat. Use a sliding bevel set to each angle, a drill press tilted to the correct side-to-side angle with the workpiece shimmed for front-to-back angle, or a dedicated chair mortising jig. Traditional chairmakers often used a reference board and sight lines to set angles empirically rather than calculating them trigonometrically.',
  },
  {
    id: 'me-round-tenon-round-mortise',
    topic: 'Round tenon in round mortise for chair rungs',
    keywords: ['round','tenon','mortise','chair','rung','spindle','turned','drill','auger'],
    answer: 'Chair rungs and spindles use round tenons (turned on the lathe or shop-turned with a dowel former) in round mortises (drilled with a Forstner or auger bit). The tenon should be sized to enter the mortise with firm hand pressure — not pounding. Green wood traditions size the tenon slightly oversize and dry it (which shrinks the tenon); the dry tenon is then glued into a moister mortise that swells slightly, creating a locked joint without relying entirely on glue.',
  },
  {
    id: 'me-floating-panel-sizing',
    topic: 'Floating panel groove and panel sizing',
    keywords: ['floating','panel','groove','movement','size','gap','door','frame','allowance'],
    answer: 'For a floating panel (like a cabinet door panel) that isn\'t glued, the panel must be sized smaller than the groove length to allow seasonal movement. Allowance: panel width = groove length minus (panel width × movement coefficient × MC change). A simpler field rule: leave 1/8" gap per foot of panel width for panels moving into the groove season. Never fill the gap with caulk or glue — the panel must be free to move. Center the panel in the frame before assembly so it has equal expansion room in both directions.',
  },
  {
    id: 'me-pocket-hole-thin',
    topic: 'Pocket holes in thin material — under 3/4"',
    keywords: ['pocket','hole','thin','1/2','5/8','short','screw','Kreg','setting'],
    answer: 'For material thinner than 3/4", most pocket hole jigs have a secondary setting. Kreg\'s guide: 1/2" material uses a 1" screw and specific drill depth setting; 5/8" uses a 1-1/4" screw. If you use the 3/4" setting on 1/2" material, the screw will blow through the face. Always consult the pocket hole jig chart and use the exact drill depth collar setting for the material thickness. Test the setup on scrap before committing to the actual workpiece.',
  },
  {
    id: 'me-tongue-groove-sizing',
    topic: 'Tongue and groove sizing rules',
    keywords: ['tongue','groove','size','ratio','depth','width','panel','loose','fit'],
    answer: 'Tongue thickness: 1/3 of the total stock thickness. For 3/4" stock, that\'s a 1/4" tongue. Groove depth: slightly deeper than the tongue is long (1/16" extra) so the tongue doesn\'t bottom out before the shoulder seats. Groove width: tongue thickness plus a few thousandths clearance for glue or movement. For floating panels, size the groove to allow the tongue to move freely — it shouldn\'t be glued. A snug-sliding fit without binding is correct.',
  },
  {
    id: 'me-biscuit-near-edge',
    topic: 'Biscuit placement near board ends and edges',
    keywords: ['biscuit','near','edge','end','distance','minimum','splinter','blow','out'],
    answer: 'Keep biscuit slots at least 2" from the end of a board — slots too close to ends allow the biscuit to pop through when the board is under clamp pressure. Size #10 biscuits need 2" minimum from the end; #20 need 2.5". On edge joints (face-to-face glue ups), biscuits provide alignment but add no real strength. Space them 8–12" apart for best alignment. On miter joints, biscuits can reinforce the miter but must be placed precisely perpendicular to the miter face.',
  },
  {
    id: 'me-glue-starved-joint',
    topic: 'Starved glue joints and how to avoid them',
    keywords: ['starved','glue','joint','too','little','dry','weak','penetrating','open','grain'],
    answer: 'A starved joint has insufficient glue — either too little applied or too much squeezed out by excessive clamp pressure. It looks fully assembled but is weak. Signs: very little or no squeeze-out, joint opens at light stress, or dry line visible at joint. Prevention: apply sufficient glue to cover both mating surfaces completely, use moderate clamp pressure (light bead of squeeze-out all the way around means correct pressure), and don\'t leave joints unclamped too long after spreading glue on porous end grain.',
  },
  {
    id: 'me-mortise-tenon-table-corner',
    topic: 'Mitered mortise and tenon for table corners',
    keywords: ['mitered','mortise','tenon','table','corner','long','depth','maximize','miter'],
    answer: 'At a table corner, two apron rails meet at the same leg. Each needs a mortise, and the two mortises can\'t overlap inside the leg. A mitered tenon (the tenon end is cut at 45°) allows both tenons to extend deeper into the leg and come close together without intersecting. This maximizes glue area and mechanical strength at the corner. The diagonal miter at the tenon end is cut after the shoulder cuts. Mark the miters carefully so they clear each other by at least 1/8".',
  },
  {
    id: 'me-slot-mortise-jig',
    topic: 'Router mortising jig for consistent mortises',
    keywords: ['router','mortise','jig','plunge','consistent','repeat','fence','stop'],
    answer: 'A shop-made router mortising jig clamps to the workpiece and guides the router with two fences (for side-to-side centering) and stop blocks (for length). Plunge the router in the center first, then work toward the ends to avoid climbing cuts at the stop blocks. Spiral upcut bits clear chips efficiently in deep mortises. Routing mortises produces flat walls and a consistent depth automatically — better than hand-chisel mortises for batch production. Clean the rounded corners with a chisel or round the tenon corners to match.',
  },

  // ── MORE HAND TOOLS ───────────────────────────────────────────────────────────
  {
    id: 'me-japanese-plane',
    topic: 'Japanese kanna (hand plane) setup and use',
    keywords: ['japanese','kanna','pull','plane','laminated','chipbreaker','setup','hollow','back'],
    answer: 'Japanese planes cut on the pull stroke, which many find more controllable for fine work. The laminated iron (hard steel welded to soft backing steel) sharpens easily and holds an edge extremely well. The back of the iron has a hollow (ura) that must be maintained by occasional flattening on a waterstone — this ensures only the cutting edge and corners contact the stone. Planes are adjusted by tapping the body to advance the blade and tapping the iron laterally for alignment. Setup is more complex than Western planes but the result is exceptional.',
  },
  {
    id: 'me-japanese-chisel',
    topic: 'Japanese nomi (chisels) characteristics',
    keywords: ['japanese','nomi','chisel','laminated','ura','hollow','back','hard','steel'],
    answer: 'Japanese chisels (nomi) use the same laminated construction as Japanese plane irons — hard steel cutting edge, soft steel body. The hollow ura (hollow back) makes flattening the back fast and keeps it flat during use. Japanese bench chisels are driven with a round-headed hammer (genno) — the steel hoop on the handle prevents mushrooming. They\'re typically available in specific widths (3mm through 36mm) and hold an edge longer than most Western chisels at similar or lower sharpening cost.',
  },
  {
    id: 'me-japanese-saws',
    topic: 'Japanese pull saws (ryoba, dozuki, kataba)',
    keywords: ['japanese','saw','ryoba','dozuki','kataba','pull','thin','kerf','accurate'],
    answer: 'Japanese saws cut on the pull stroke, which keeps the thin plate in tension rather than compression — allowing extremely thin kerfs. Ryoba saws have two edges: rip teeth on one, crosscut on the other. Dozuki saws have a stiffening spine (like a Western backsaw) and very fine teeth for joinery cuts. Kataba are single-edge saws without a spine, allowing deeper cuts. Japanese saw kerfs are 1/32"–1/16" — significantly thinner than Western backsaws, removing less material and making cuts easier to correct.',
  },
  {
    id: 'me-wooden-planes',
    topic: 'Wooden bodied planes vs metal planes',
    keywords: ['wooden','plane','metal','infill','body','warm','glide','adjust','traditional'],
    answer: 'Wooden-bodied planes are lighter, warm to the touch, and glide more smoothly on some woods — the wood-on-wood friction is lower than metal-on-wood. They\'re adjusted by tapping with a mallet (to advance the iron) or tapping the heel (to retract). Without a chip breaker adjustment screw, they\'re harder to set precisely but master craftsmen prefer them for speed of adjustment once mastered. Infill planes (wooden body with metal sole, British tradition) combine the smoothness of wood with the mass of metal for exceptional surface prep.',
  },
  {
    id: 'me-burnisher-technique',
    topic: 'Burnisher technique for card scrapers',
    keywords: ['burnisher','technique','angle','hook','scraper','card','steel','rod','oval'],
    answer: 'A burnisher is a hardened smooth rod (often oval or round cross-section) used to turn the hook on a card scraper. After jointing and honing the scraper edge square, draw the burnisher along the edge at 90° two or three times (this consolidates and smooths the edge). Then tilt the burnisher 5–10° and make 2–3 strokes along each face to turn the tiny hook. The hook must be uniform all the way across — an uneven hook produces ridges. A fine oval-section burnisher gives more control than a round one.',
  },
  {
    id: 'me-toothing-plane',
    topic: 'Toothing plane for veneer work',
    keywords: ['toothing','plane','veneer','glue','roughen','substrate','tooth','score'],
    answer: 'A toothing plane has a serrated (toothed) iron that scores parallel grooves in a surface rather than taking a smooth shaving. It\'s used to roughen substrate surfaces before applying veneer with hide glue or contact cement — the grooves create mechanical tooth for better adhesion. It also removes any wax or silicone contamination that would prevent glue adhesion. Run it diagonally in both directions for maximum tooth. It\'s also useful for preliminary flattening of difficult, reversing-grain boards before final smooth planing.',
  },
  {
    id: 'me-inshave',
    topic: 'Inshave for chair seat hollowing',
    keywords: ['inshave','chair','seat','hollow','scorp','bent','gouge','curved','draw'],
    answer: 'The inshave (scorp) is a two-handled draw tool with a curved blade used for hollowing chair seats and inside curved surfaces. Unlike the travisher (which is a spokeshave), the inshave uses a drawknife-style grip and cuts with the grain across the seat hollow. Use a push-pull motion across the grain to rough out the hollow quickly, then follow with the travisher for final shaping. The curved blade radius should loosely match the desired hollow depth. Available from chairmaking suppliers.',
  },
  {
    id: 'me-adze-basics',
    topic: 'Adze for hollowing and rough shaping',
    keywords: ['adze','hollow','flat','chair','seat','rough','texture','log','shape'],
    answer: 'An adze is an axe-like tool with the blade perpendicular to the handle, used for hollowing large areas — chair seats, canoe hulls, and troughs. The flat adze is for flatter surfaces; the gutter adze has a rounded blade for deeper hollows. Swing it in controlled arcs, working across the grain. The adze removes material very fast — follow up with a travisher and scrapers for final surfacing. Always secure the workpiece firmly and be aware of your foot position on the downswing.',
  },
  {
    id: 'me-panel-gauge',
    topic: 'Panel gauge for wide marking',
    keywords: ['panel','gauge','wide','board','rip','fence','mark','layout','long'],
    answer: 'A panel gauge is an extended marking gauge with a long beam (12–24") that allows scribing lines parallel to the edge across wide boards — too wide for a standard mortise gauge. It\'s used to mark rip lines on wide planks and to scribe panel grooves on cabinet sides. Make a shop-built version from a hardwood beam and fence with a wedge and knife or pin. The key is a secure lock — the fence must not shift during a long scribing stroke.',
  },
  {
    id: 'me-hand-tool-set-priorities',
    topic: 'Hand tool starter set priorities for new woodworkers',
    keywords: ['starter','set','hand','tool','priority','buy','first','begin','essential'],
    answer: 'Start with: a No.5 jack plane for rough work, a No.4 smoother for final prep, a set of 4 bench chisels (1/4", 1/2", 3/4", 1"), a crosscut and a rip handsaw (or a ryoba Japanese saw covering both), a combination square, a marking gauge, a marking knife, and a wooden mallet. Add a shoulder plane when you start doing mortise and tenon work. This set handles 80% of hand tool furniture work. Don\'t buy a set of 20 chisels before you can sharpen one.',
  },
  {
    id: 'me-try-square-check',
    topic: 'Checking and calibrating a try square',
    keywords: ['try','square','check','accurate','calibrate','line','edge','reliable'],
    answer: 'All squares drift out of true over time — check yours regularly. Place the stock against a known-flat reference edge and scribe a line with a sharp knife. Flip the square end-for-end (same face) against the same edge and scribe a second line from the same starting point. If the square is true, both lines coincide. If they diverge, the square is out by half the divergence at the knife tip. The best combination squares can be adjusted; fixed try squares can sometimes be gently bent back into true, or replace them.',
  },

  // ── MORE POWER TOOLS ─────────────────────────────────────────────────────────
  {
    id: 'me-table-saw-blade-types',
    topic: 'Table saw blade types — rip, combination, crosscut, ATB',
    keywords: ['blade','rip','combination','crosscut','ATB','carbide','tooth','count','type'],
    answer: 'Rip blades have 24–30 large, flat-top teeth optimized for cutting parallel to grain. Crosscut blades have 60–80 small, ATB (alternate top bevel) teeth for clean grain-crossing cuts. Combination blades (40–50 teeth in groups of 5, with a raker tooth) handle both reasonably well — the compromise most shops use. For the cleanest sheet good cuts, an 80-tooth ATB blade is ideal. For production ripping, a 24-tooth blade is faster and cooler. Match blade selection to the most frequent task; buy the specialized blade when rip or crosscut quality becomes the priority.',
  },
  {
    id: 'me-sawstop-technology',
    topic: 'SawStop flesh detection technology',
    keywords: ['sawstop','flesh','detect','brake','cartridge','signal','safety','trigger'],
    answer: 'SawStop table saws detect flesh contact through electrical capacitance — the blade carries a small electrical signal; touching it with a finger changes the signal, triggering an aluminum brake cartridge that stops the blade in 5 milliseconds. The blade drops below the table simultaneously. Typical result: a small nick rather than a lost finger. The brake cartridge ($70–90) is destroyed in a triggering event and must be replaced. Wood conducts electricity poorly — wet, green, or treated wood can sometimes trigger a false stop. A legitimate tool for production shops and woodworking educators.',
  },
  {
    id: 'me-jointer-outfeed',
    topic: 'Jointer outfeed table height adjustment',
    keywords: ['jointer','outfeed','table','height','set','coplanar','cutter','head','flat'],
    answer: 'The jointer outfeed table must be exactly level with the highest point of the cutter head arc. Too low and the board drops off the outfeed table end and produces a slight hollow at the board end. Too high and the board hits the outfeed table and stops. To set: rotate the cutter head by hand to the top position, lay a metal straightedge across the outfeed table to the cutter, and adjust the outfeed table up or down until the straightedge just barely grazes the highest carbide point. Check and readjust whenever knives are replaced.',
  },
  {
    id: 'me-spiral-cutter-head',
    topic: 'Spiral/helical cutter head vs straight knives',
    keywords: ['spiral','helical','cutter','head','planer','jointer','quiet','tearout','carbide'],
    answer: 'Spiral (helical) cutter heads have dozens of small square carbide inserts arranged in a helix around the cylinder. They cut more quietly, produce far less tearout on difficult grain (each small insert takes a shearing cut at an angle), and individual carbide inserts are easily indexed to a fresh edge when dull. Straight knife heads (2–4 long knives) are cheaper and simpler but noisier and produce more tearout. Upgrading to a spiral head is one of the highest-impact investments for a jointer or planer that handles figured wood.',
  },
  {
    id: 'me-bandsaw-blade-guide',
    topic: 'Setting bandsaw blade guides correctly',
    keywords: ['bandsaw','guide','bearing','block','clearance','side','back','thrust'],
    answer: 'Bandsaw blade guides sit above and below the table on both sides of the blade and the back. Side guides (bearing or cool blocks) are set to just clear the blade width without touching — 0.004" clearance (the thickness of a piece of paper) is about right. The back thrust bearing contacts only when wood is fed against the blade — it should have a hair of clearance when no wood is present. Guides too tight cause blade heat and metal fatigue; too loose allows wandering. Readjust guides when changing blade widths.',
  },
  {
    id: 'me-drill-press-table',
    topic: 'Shop-built drill press table with fence',
    keywords: ['drill','press','table','shop','built','fence','stop','mdf','auxiliary'],
    answer: 'The standard drill press table is too small and lacks a fence. Build an auxiliary table from 3/4" MDF clamped or bolted to the cast iron table. Add a sacrificial insert in the center that can be replaced when drill-through holes accumulate. Build a sliding fence that adjusts with a T-track and knob-locks. Add a stop block to the fence for repeat-hole drilling at the same distance from the edge. A good drill press table transforms a fussy machine into a production-ready workhorse for shelf pin holes, mortises, and doweling.',
  },
  {
    id: 'me-router-collet-size',
    topic: 'Router collet sizes — 1/4" vs 1/2" shank',
    keywords: ['router','collet','1/4','1/2','shank','vibration','runout','strength','bit'],
    answer: '1/2"-shank bits run truer and with less vibration than 1/4"-shank bits because the larger shank has more bearing contact in the collet. For a router with a 1/2" collet, always use 1/2"-shank bits for larger profiles — panel raisers, large roundovers, and flush-trim bits especially. 1/4"-shank bits are fine for small bits (1/4" straight, small roundovers) and are the only option in trim routers. Never reduce a 1/2" collet with an adapter — the fit is imprecise and bit concentricity suffers.',
  },
  {
    id: 'me-fixed-vs-plunge-router',
    topic: 'Fixed base vs plunge base router — choosing',
    keywords: ['fixed','plunge','router','base','choose','edge','table','groove','start'],
    answer: 'Fixed-base routers have the motor locked at a set depth — ideal for router table use and edge routing where you plunge in from the end of the board. Plunge-base routers have a spring-loaded column that allows plunging into the middle of a workpiece — essential for starting mortises and through-holes in the center of a panel. Many routers have interchangeable bases (fixed and plunge) for versatility. For router table use, fixed is simpler and easier to set. For handheld mortising and groove work, plunge is necessary.',
  },
  {
    id: 'me-palm-router-uses',
    topic: 'Palm (trim) router — best applications',
    keywords: ['palm','trim','router','small','light','edge','flush','chamfer','one-handed'],
    answer: 'Palm routers (compact trim routers) are lightweight (under 2 lbs), one-hand operable, and ideal for light-duty edge routing, chamfering, flush-trimming laminate or veneer edges, and inlay routing. They typically accept only 1/4"-shank bits and have limited depth adjustment range. Not suitable for large profile bits or heavy production work — the light motor bogs down. For furniture work, a palm router with a roundover bit handles the majority of edge-profiling quickly and precisely.',
  },
  {
    id: 'me-drum-sander',
    topic: 'Drum sander for consistent thickness sanding',
    keywords: ['drum','sander','thickness','thin','veneer','wide','consistent','sandpaper','roll'],
    answer: 'A drum sander (wide belt or open-end drum) sands boards to consistent thickness without the snipe risk of a thickness planer. It\'s ideal for very thin stock (under 3/8") that a planer can\'t safely process, and for figured wood prone to tearout under planer knives. Feed boards slightly diagonal to minimize sanding pattern. Take light passes (0.005"–0.010" per pass) — too much removes the drum paper quickly and burns the wood. Change sandpaper rolls before they stop cutting — dragging dull abrasive causes heat.',
  },
  {
    id: 'me-spindle-sander',
    topic: 'Spindle sander for curves and inside corners',
    keywords: ['spindle','sander','oscillating','drum','curve','inside','convex','concave'],
    answer: 'An oscillating spindle sander has a drum that both rotates and moves up and down — the oscillation prevents the drum from loading with debris and burning. Use the drum diameter closest to the curve radius of the inside cut — a tight inside curve needs a smaller drum. Work the piece slowly into the rotating drum and let the sander do the work; forcing the stock removes too much and creates flat spots. Spindle sander drums come in 1/2" to 3" diameters to match various curve radii.',
  },
  {
    id: 'me-air-compressor-shop',
    topic: 'Air compressor selection for a woodworking shop',
    keywords: ['air','compressor','psi','cfm','gallon','tank','nailer','spray','size'],
    answer: 'For nailer use only: a small pancake compressor (1–2 gallon, 90 PSI) is sufficient. For a spray gun: a minimum 30-gallon tank at 6–8 CFM at 40 PSI. Larger is always better for spray finishing — small compressors cycle on and off during spraying, causing pressure fluctuation. Oil-free compressors contaminate the air with water vapor; add an inline water separator and oil-water separator for spray finishing. A quiet (under 70 dB) compressor makes the shop much more pleasant — worth the premium for extended use.',
  },
  {
    id: 'me-air-nailer-types',
    topic: 'Air nailer types — 18 gauge, 16 gauge, 15 gauge',
    keywords: ['air','nailer','brad','finish','framing','18','16','15','gauge','cleat'],
    answer: '18-gauge brad nailers shoot thin brads (1" to 2") — for light tacking while glue sets, attaching moldings, and trim work where nail holes are minimal. 16-gauge finish nailers shoot a heavier nail (1" to 3.5") — for attaching face frames, trim, and thicker stock. 15-gauge angled finish nailers shoot the heaviest finish nail (1-1/4" to 3.5") for structural trim and heavy molding. Never use a brad nailer for structural connections that will be stressed — brads pull out easily under load.',
  },
  {
    id: 'me-outfeed-table',
    topic: 'Table saw outfeed table — building one',
    keywords: ['outfeed','table','table','saw','support','long','board','fold','height'],
    answer: 'Long boards on the table saw need support as they exit the blade — without outfeed support, they tip down and bind or jerk. Build an outfeed table at exactly the same height as the saw table. A folding version (hinged and drops flat against the saw when not needed) saves shop floor space. The simplest option: a shop-built table from 3/4" plywood with adjustable legs (threaded rod and couplings). Height is critical — even 1/16" too high catches the board; 1/16" too low allows tipping.',
  },
  {
    id: 'me-miter-saw-stand',
    topic: 'Miter saw stand and material support',
    keywords: ['miter','saw','stand','support','wing','long','roller','stop','repeat'],
    answer: 'A miter saw stand needs wings that support long material on both sides of the saw at the same height as the saw table. Commercial fold-up stands have roller extensions. Shop-built stands can use benchtop wings at the correct height with a flip stop for repeat cuts. A flip stop (a hinged stop block that flips up to let the workpiece pass and then flips down to register the next cut) is the key efficiency tool — mark your stop positions in pencil on the fence for frequent cut lengths.',
  },
  {
    id: 'me-jigsaw-orbital',
    topic: 'Jigsaw orbital action setting',
    keywords: ['jigsaw','orbital','action','setting','wood','fast','rough','slow','clean'],
    answer: 'Modern jigsaws have adjustable orbital action — the blade swings forward on the upstroke (cutting stroke) in addition to moving up and down. Higher orbital settings cut faster and more aggressively in thick wood but leave a rougher cut. Setting 0 (straight up-and-down only) cuts slowest but cleanest — use for laminated panels and finish cuts. Setting 3 or 4 cuts fast through thick lumber for rough cuts. For most furniture work, a middle orbital setting (1 or 2) balances speed and surface quality.',
  },

  // ── MORE FINISHING ────────────────────────────────────────────────────────────
  {
    id: 'me-french-polish',
    topic: 'French polish — shellac pad technique',
    keywords: ['french','polish','pad','shellac','rubber','charge','oil','lubricant','figure-8'],
    answer: 'French polishing applies shellac with a cloth pad (the "rubber") using figure-8 and circular motions. The pad has a core of wool or cotton wrapped in lint-free cloth, charged with dilute shellac (1-lb cut). A tiny drop of mineral oil on the pad face lubricates it against sticking. Work quickly in sweeping figure-8s, never stopping on the surface. Layer thin coats — the accumulated film builds slowly over hours or days of work. Finish with a spirit-off coat (pure alcohol) to remove the oil residue. It produces the most stunning, deep finish achievable by hand.',
  },
  {
    id: 'me-bleaching-wood',
    topic: 'Bleaching wood for lighter color',
    keywords: ['bleach','wood','color','lighten','oxalic','two','part','A','B'],
    answer: 'Two-part (A/B) wood bleach uses sodium hydroxide (part A) followed by hydrogen peroxide (part B) to break down the natural color compounds in wood — dramatically lightening the color. Neutralize with dilute vinegar-and-water solution after bleaching, then let dry completely before finishing. Oxalic acid removes iron stains and tannin-based discoloration without changing overall wood color. Household chlorine bleach removes some surface mold but has minimal effect on wood color. Always test bleaching on scrap first — the result varies by species.',
  },
  {
    id: 'me-ebonizing-wood',
    topic: 'Ebonizing wood — making light wood dark',
    keywords: ['ebonize','black','vinegar','iron','tannin','chemical','reaction','reaction','oak'],
    answer: 'Ebonizing uses a chemical reaction between iron acetate (rusty steel wool dissolved in white vinegar) and the tannins in wood to produce a gray-to-black color. High-tannin woods (oak, walnut, cherry, mahogany) react strongly — sometimes producing deep black in one application. Low-tannin woods (maple, pine) need a tannic acid wash applied first. The color penetrates rather than sitting on the surface, producing a more natural look than black paint or stain. Experiment on scrap — results vary by species, iron concentration, and contact time.',
  },
  {
    id: 'me-shou-sugi-ban',
    topic: 'Shou sugi ban (yakisugi) charred wood technique',
    keywords: ['shou','sugi','ban','yakisugi','char','burn','torch','brush','seal','exterior'],
    answer: 'Shou sugi ban (yakisugi) chars the wood surface with a torch or fire, producing a beautiful textured carbonized layer that resists rot, insects, and fire. Traditional Japanese method used cedar; any wood can be charred. After charring, brush off loose carbon with a wire brush to reveal the texture — light brushing leaves bold texture; heavy brushing smooths it. Seal with oil or leave unsealed (the carbon itself is protective). Charred wood is a striking exterior cladding option and increasingly popular in contemporary interior furniture accents.',
  },
  {
    id: 'me-wire-brushing',
    topic: 'Wire brushing and texturing wood surface',
    keywords: ['wire','brush','texture','grain','soften','raised','rustic','exterior','finish'],
    answer: 'Wire brushing scrubs away the soft early wood (spring growth) from a sawn surface, leaving the harder latewood (dark rings) raised — producing a deeply textured, rustic surface. Use a wire cup brush on an angle grinder or drill, or a hand-held wire brush for smaller pieces. Work with the grain — brushing against it tears fibers and looks wrong. The result is striking on oak, ash, and Douglas fir with bold ring patterns. Apply oil or clear finish to seal the textured surface without filling the raised grain.',
  },
  {
    id: 'me-reactive-stain',
    topic: 'Reactive stains — iron acetate, vinegar, and salt',
    keywords: ['reactive','stain','iron','vinegar','salt','color','tannin','chemical','natural'],
    answer: 'Reactive stains change wood color through a chemical reaction rather than depositing pigment. Iron vinegar (vinegar with steel wool dissolved in it) reacts with tannins to create grays and blacks. Salt water accelerates some aging reactions. Ammonia vapors (in a sealed container with a bowl of ammonium hydroxide) fume oak to a deep honey-brown by reacting with the tannic acid. These reactions look completely natural because the color is in the wood itself, not on it. Results are permanent and can\'t be sanded off.',
  },
  {
    id: 'me-finish-adhesion-prep',
    topic: 'Preparing surfaces for finish adhesion',
    keywords: ['prep','adhesion','oil','grease','clean','wax','naphtha','mineral','spirits'],
    answer: 'Wax, oil, silicone, and skin oil prevent finish adhesion. Before finishing, wipe the entire surface with naphtha or mineral spirits on a clean cloth — this removes surface contamination and flashes off quickly. Don\'t use water (raises grain) or acetone (can affect some woods and is too aggressive for some finishes). After cleaning, avoid touching surfaces with bare hands — even clean skin oils can cause adhesion problems. Apply finish while the shop is as dust-free as possible after the final sanding.',
  },
  {
    id: 'me-spray-gun-setup',
    topic: 'Setting up an HVLP spray gun',
    keywords: ['hvlp','spray','gun','needle','cap','fluid','air','pressure','adjust','tip'],
    answer: 'HVLP spray gun setup: set air pressure to the gun manufacturer\'s recommended inlet pressure (typically 10–25 PSI at the gun). Thin the finish to the correct viscosity using a viscosity cup (#4 Zahn cup) — target 15–20 seconds flow time for most finishes. Adjust the fluid needle to control material output (open 1.5–2 turns for most jobs). Pattern knob controls fan width (vertical ellipse to circle). Test spray on cardboard — look for even, stipple-free atomization with no heavy center or heavy edges. Adjust air or fluid until the pattern is even.',
  },
  {
    id: 'me-spray-gun-clean',
    topic: 'Cleaning a spray gun after use',
    keywords: ['spray','gun','clean','solvent','nozzle','needle','dry','clog','maintain'],
    answer: 'Clean immediately after use — dried finish in the gun passages is very difficult to remove. Pour out remaining finish, fill the cup with appropriate solvent (lacquer thinner for lacquer, water for waterborne), and spray through until clean. Disassemble the fluid needle, nozzle, and air cap; soak in solvent. Use a gun cleaning brush set for small passages. Dry all parts and lightly oil the needle and packing nut. A dedicated gun-cleaning station (closed container that recycles solvent) keeps waste minimal. Never soak O-rings in harsh solvents — they swell and fail.',
  },
  {
    id: 'me-color-matching-repair',
    topic: 'Color-matching finish for repairs',
    keywords: ['color','match','repair','touch','up','dye','tint','blend','sample','custom'],
    answer: 'Color-matching is the hardest finishing skill. Start by identifying the finish (shellac, lacquer, or poly) and the stain or dye color. Mix colorants (universal tints, dry dyes, Japan colors) into the finish in tiny increments — it\'s always easier to darken than lighten. Test on scrap or an inconspicuous area. The repair area is never perfectly invisible — feather the finish into the surrounding area with graduated coats. Lighting conditions change color appearance dramatically — always check the color match under the room\'s actual lighting, not shop fluorescent lights.',
  },
  {
    id: 'me-finish-over-stain',
    topic: 'Choosing topcoat over stain — compatibility',
    keywords: ['stain','topcoat','poly','lacquer','compatible','wait','cure','bleed','interfere'],
    answer: 'Let oil-based stain dry thoroughly before applying topcoat — usually 24–48 hours minimum. Oil-based poly over oil stain: fine after full dry. Lacquer over oil stain: potentially problematic — the strong solvents in lacquer can dissolve and lift some stain pigments. Shellac over oil stain: fast, seals the stain. Water-based poly over oil stain: wait 3–4 days minimum for the oil to fully oxidize; otherwise the residual oils prevent adhesion. When in doubt, seal with a coat of dewaxed shellac between stain and topcoat — it\'s the universal compatibility bridge.',
  },
  {
    id: 'me-waterbased-dry-time',
    topic: 'Water-based finish dry time vs cure time',
    keywords: ['dry','cure','water','based','finish','time','hours','days','hardness','30','day'],
    answer: 'Water-based finishes are "dry" to the touch in 1–2 hours and recoatable in 2–4 hours — much faster than oil-based. But "full cure" (maximum hardness and chemical resistance) takes 2–4 weeks. During the cure period, the finish is vulnerable to scratches, water rings, and chemical damage that it would resist when fully cured. Avoid placing objects on freshly finished surfaces for at least a week. Oil-based poly cures in 30 days — similar rules apply. The finish looks the same whether dry or fully cured; the hardness is the difference.',
  },
  {
    id: 'me-epoxy-river-table',
    topic: 'Epoxy river table construction',
    keywords: ['epoxy','river','table','slab','void','fill','bubble','color','pigment','deep'],
    answer: 'Epoxy river tables fill a natural void or gap between two live-edge slabs with colored epoxy. Use slow-cure, deep-pour epoxy rated for your pour depth — regular epoxy generates too much heat in thick pours and may crack or yellow. Pour in layers of no more than 1/2"–1" to manage heat buildup. Eliminate bubbles by warming the epoxy slightly before mixing, using a heat gun or torch briefly over the poured surface, or using a vacuum chamber for small pours. Color with alcohol inks, mica powder, or epoxy pigments — test your colors in a small cup first.',
  },
  {
    id: 'me-finish-softwood',
    topic: 'Finishing softwood — pine, cedar, fir special considerations',
    keywords: ['softwood','pine','finish','blotch','seal','conditioner','resin','coat','oil'],
    answer: 'Softwoods absorb stain very unevenly — pine is the worst offender, blotching dark in the growth rings and light between them. A pre-stain conditioner, gel stain, or very diluted wash coat of shellac before staining significantly reduces blotching. For a natural look without stain, oil finishes (danish oil, tung oil) enhance grain without the blotching risk. Cedar\'s natural oils can bleed through water-based finishes — seal with shellac first. Fir resins can also bleed through paint; shellac prime before topcoating.',
  },

  // ── MORE GLUE & ADHESIVES ────────────────────────────────────────────────────
  {
    id: 'me-resorcinol-glue',
    topic: 'Resorcinol glue for marine and structural use',
    keywords: ['resorcinol','marine','waterproof','dark','line','boat','structural','two','part'],
    answer: 'Resorcinol is a two-part structural adhesive (resorcinol resin + paraformaldehyde catalyst) that produces a bond stronger than the wood and is completely waterproof — the original marine and structural glue. It produces a dark reddish-brown glue line that shows clearly on light wood. It requires precise mixing ratios, has a short pot life, and needs temperatures above 70°F during cure. For most woodworking, epoxy has replaced resorcinol except in traditional boat building where its specific properties are mandated.',
  },
  {
    id: 'me-urea-formaldehyde',
    topic: 'Urea-formaldehyde (plastic resin) glue',
    keywords: ['urea','formaldehyde','plastic','resin','powder','mix','water','cure','hard','yellow'],
    answer: 'Urea-formaldehyde glue (sold as DAP Weldwood Plastic Resin) comes as a powder mixed with water. It cures rigid and hard, resists creep (doesn\'t compress under sustained load), and has a longer open time (15–30 min) than PVA. It\'s excellent for laminating cutting boards, veneered panels, and any application requiring a stiff glue line. It\'s water-resistant but not waterproof. Requires temperatures above 65°F during cure. The dry powder has a very long shelf life; mixed batches must be used the same day.',
  },
  {
    id: 'me-epoxy-thin-penetrating',
    topic: 'Thinning epoxy for deep penetration',
    keywords: ['epoxy','thin','penetrate','deep','stabilize','punky','rot','solvent','dilute'],
    answer: 'Standard epoxy is too thick to penetrate deeply into porous or punky wood. West System\'s 105/205 or Smith\'s CPES (Clear Penetrating Epoxy Sealer) contain solvents that carry the epoxy resins deep into the fibers — the solvents evaporate and the epoxy remains. CPES is specifically designed for this application and is the best choice for consolidating punky wood, stabilizing dry rot, and sealing end grain. Do not thin regular epoxy with acetone — the result is unpredictable and usually weaker.',
  },
  {
    id: 'me-hide-glue-spring-joint',
    topic: 'Hide glue for rubbed joints and spring joints',
    keywords: ['hide','glue','rub','spring','joint','clamping','flat','veneer','no','clamp'],
    answer: 'Hot hide glue has special properties that make rubbed joints possible — two flat surfaces coated and pressed together while the glue is hot will bond without clamps as the glue chills and gels. This works because hide glue has higher initial tack than PVA. Similarly, a "sprung joint" in guitar top construction uses hide glue to deliberately close a slight gap under spring tension, pre-stressing the joint. These techniques don\'t work with PVA or modern adhesives, which is one reason hide glue remains the standard in instrument making.',
  },

  // ── SHOP MATH ────────────────────────────────────────────────────────────────
  {
    id: 'me-ellipse-layout',
    topic: 'Drawing an ellipse for tabletops and mirrors',
    keywords: ['ellipse','draw','trammel','oval','table','mirror','string','pins','nail'],
    answer: 'Two methods for large ellipses. String method: drive two nails at the focal points (calculated from the major and minor axis lengths), tie a string loop around both nails, and trace the ellipse keeping the string taut with a pencil. Trammel method: make a trammel beam with two pins set at specific distances — slide the trammel along perpendicular guide rails as the pencil scribes the ellipse. The trammel method is more accurate for furniture. Calculator: focal distance = sqrt((major_axis/2)² − (minor_axis/2)²).',
  },
  {
    id: 'me-ogee-layout',
    topic: 'Laying out an ogee curve',
    keywords: ['ogee','curve','S','curve','layout','compass','tangent','foot','moulding'],
    answer: 'An ogee is an S-curve consisting of two opposite arcs tangent to each other. Lay out an ogee with a compass: draw the baseline and the top line, divide the vertical space into equal halves. Draw the first arc (concave upward) from its centerpoint below the baseline, then the second arc (convex upward) from its centerpoint above the top line. The two arcs meet at the midpoint and must be tangent (the centerpoints and the meeting point all lie on a straight line). This geometric layout produces a perfectly smooth S-curve.',
  },
  {
    id: 'me-compound-angle-splay',
    topic: 'Table saw compound angle settings for splayed boxes',
    keywords: ['compound','angle','splay','box','table','saw','bevel','miter','tilt','chart'],
    answer: 'For a 4-sided box with sides splayed at angle S from vertical: table saw miter angle = arctan(cos(45°) × tan(S)); bevel (blade tilt) = arctan(sin(45°) / cos(S)). For a common 10° splay: miter ≈ 7.1°, bevel ≈ 44.3°. For a 15° splay: miter ≈ 10.6°, bevel ≈ 43.1°. Round to the nearest 1/10° and test with scrap. Each side needs both cuts — the key is the miter tilts away from you on a standard table saw. A compound miter saw handles these cuts with a single setup if both angles can be set simultaneously.',
  },
  {
    id: 'me-pythagorean-chair-angle',
    topic: 'Using trigonometry for chair leg angle calculations',
    keywords: ['chair','leg','angle','trig','calculate','degree','splay','rake','math'],
    answer: 'Chair legs that splay in two directions (splay and rake) require compound angles for the seat mortises. Net angle from vertical = arccos(cos(splay) × cos(rake)). For 5° splay and 7° rake: net angle = arccos(cos(5°) × cos(7°)) ≈ 8.6°. The twist angle for the mortise (rotation in the seat plane) = arctan(sin(rake) / sin(splay)). These calculations are usually done once for a design and then set on a jig. Many experienced chairmakers measure the angles empirically from a full-scale drawing instead of calculating.',
  },
  {
    id: 'me-sequence-wood-cuts',
    topic: 'Cutting sequence math — largest parts first',
    keywords: ['cut','sequence','plan','largest','first','crosscut','rip','optimize','layout'],
    answer: 'Always cut largest parts first from a board. Rip to the widest needed width first, keeping the reference edge; then crosscut to the longest needed length. Never cut short pieces from a long board without planning what the remainder can provide — a 3" offcut may save another cut if planned. Mark all cut lines on the board before any cuts, then sequence from largest to smallest. This approach minimizes waste and avoids the situation where you\'ve cut too short for a needed piece.',
  },

  // ── DESIGN ────────────────────────────────────────────────────────────────────
  {
    id: 'me-trestle-table',
    topic: 'Trestle table design and stability',
    keywords: ['trestle','table','base','x','stretcher','leg','knock','down','long'],
    answer: 'Trestle tables use an A-frame or X-frame base at each end connected by a central stretcher. The stretcher is the key structural element — it ties the two bases together and prevents racking. Traditional trestle tables are knock-down (the stretcher is held with a tusk tenon) for easy transport. Leg spread determines stability — a wide stance at the feet prevents tipping. The stretcher height matters too: too low catches legs; too high interferes with seating. 6"–10" from the floor is the standard range.',
  },
  {
    id: 'me-pembroke-table',
    topic: 'Pembroke drop-leaf table design',
    keywords: ['pembroke','drop','leaf','table','swing','leg','gate','rule','joint'],
    answer: 'Pembroke tables have two small drop leaves supported by swing-out legs (gate-leg or fly-leg style). When leaves are up, the swing leg pivots out on a pivot point; when down, the swing leg tucks back against the apron. The leaves connect to the fixed top with rule joints (matched cove and roundover) and the hinges are set below the pivot of the rule joint. Pembroke tables are among the most space-efficient occasional table designs — compact with leaves down, useful dining or work table with leaves up.',
  },
  {
    id: 'me-highboy-design',
    topic: 'Highboy (tall chest) design elements',
    keywords: ['highboy','tallboy','chest','high','cabriole','bonnet','period','upper','lower'],
    answer: 'A highboy consists of a lower case (often with cabriole legs) topped by a taller upper case. The upper case typically has a bonnet pediment (curved top with finials), while the lower case has one or two rows of drawers above an apron. The connection between upper and lower is a precise fit with a few locating pins. Traditional highboys are Queen Anne or Chippendale period pieces in mahogany or walnut. Building one requires mastering a wide range of skills: case construction, drawer fitting, carved feet, and cornice moulding.',
  },
  {
    id: 'me-secretary-desk',
    topic: 'Secretary desk design and fold-down writing surface',
    keywords: ['secretary','desk','fold','down','writing','surface','lid','support','drawer','cubbies'],
    answer: 'A secretary desk has a slant-front or vertical drop-front lid that opens to a horizontal writing surface. The lid is held at 90° by chains, lid stays, or sliding "lopers" (pull-out wooden rails). Interior cubbies and small drawers provide document organization. The lid hinges carry the full weight when open — use heavy-duty or continuous hinges rated for the load. The slant-front style reveals the cubbies at a slight angle, which some find easier to access; the drop-front style creates a flat, level writing surface.',
  },
  {
    id: 'me-ladder-back-chair',
    topic: 'Ladder back chair construction',
    keywords: ['ladder','back','chair','slat','rung','post','woven','seat','shaker','weave'],
    answer: 'Ladder back chairs have horizontal slats between the rear posts that form the ladder-like back. Slats are typically steam-bent or flat-sawn and mortised into the rear posts. All post-to-rung and post-to-slat joints are round tenon in round mortise — drilled at compound angles. Seats are traditionally woven rush, cotton tape, or splint. The Shaker variant is one of the most replicated ladder backs — simple proportions, fine turnings on the back posts, and cotton tape seating. It\'s an excellent first chair project for a hand-tool woodworker.',
  },
  {
    id: 'me-workbench-vises',
    topic: 'Workbench vise placement and selection',
    keywords: ['workbench','vise','face','tail','leg','shoulder','wagon','placement','choose'],
    answer: 'A basic bench needs at least one face vise. The classic placement is front-left corner for right-handers. If adding a second vise, the tail vise (end vise for bench dog clamping) goes at the right end. Leg vises and shoulder vises are more specialized — the leg vise provides a huge clamping surface for long work; the shoulder vise allows work to overhang the bench end. For most hobby woodworkers, a quality quick-release face vise is the only vise needed for the first few years.',
  },
];
