import type { KnowledgeEntry } from './pepeKnowledge';

export const PEPE_KNOWLEDGE_MASTER_D: KnowledgeEntry[] = [
  // ── SHARPENING ───────────────────────────────────────────────────────────────
  {
    id: 'md-waterstone-grits',
    topic: 'Waterstone grit sequence for sharpening',
    keywords: ['waterstone','grit','220','1000','4000','8000','sequence','sharpen','plane','chisel'],
    answer: 'Waterstone sharpening follows a progression from coarse to fine. Damaged or very dull edges start at 220 or 400 grit to reshape the bevel. The 1000 grit removes the previous scratches and refines the edge. The 4000 grit polishes the bevel further. The 6000–8000 grit produces the final keen edge. Each step should fully remove all scratches from the previous stone. Skip a grit and you waste time on fine stones that can\'t erase the scratches from two grits back.',
  },
  {
    id: 'md-oilstone-types',
    topic: 'Oilstones — India, Arkansas, and synthetic',
    keywords: ['oilstone','India','Arkansas','coarse','medium','fine','oil','honing'],
    answer: 'Oilstones are the traditional American sharpening medium. India stones are aluminum oxide — coarse, medium, or fine grades for initial sharpening and bevel refinement. Arkansas stones are natural novaculite — soft Arkansas for medium work, hard Arkansas for final polishing, black Arkansas (translucent) for a near-mirror edge. Use honing oil (mineral oil or petroleum-based) to float swarf off the surface. Oilstones cut slowly compared to waterstones but stay flat longer and work without water.',
  },
  {
    id: 'md-diamond-plates',
    topic: 'Diamond sharpening plates — advantages and uses',
    keywords: ['diamond','plate','sharpen','fast','coarse','flat','stones','chisel','plane'],
    answer: 'Diamond plates cut faster than waterstones or oilstones and don\'t dish (hollow out). Use them for initial bevel grinding (coarse diamond), flattening waterstones and oilstones, and sharpening carbide. They require water or no lubricant at all (dry). The cutting surface is nickel-plated diamond particles — they wear over time and eventually stop cutting fast. Good diamond plates last years; cheap ones degrade in months. Inexpensive diamond paddles work well for flattening bench plane backs and quick touch-ups.',
  },
  {
    id: 'md-strop-compound',
    topic: 'Leather strop and honing compound for a keen edge',
    keywords: ['strop','leather','compound','honing','chromium','oxide','green','polish','burr'],
    answer: 'Stropping on leather with honing compound (chromium oxide "green chrome" is the standard) removes the final microscopic burr and polishes the edge to a razor sharpness. Drag the bevel at the sharpening angle AWAY from the edge (spine leading) — pulling toward the edge rolls the burr instead of removing it. 10–20 strokes per side on charged leather is enough. A well-stropped chisel or plane iron can shave end grain cleanly — that\'s the test for sharp. Strop regularly during use to extend time between full sharpening cycles.',
  },
  {
    id: 'md-bevel-angles',
    topic: 'Bevel angle selection for different tools and tasks',
    keywords: ['bevel','angle','degrees','chisel','plane','carving','paring','bench','grind'],
    answer: 'Bevel angles vary by tool and task. Paring chisels: 15°–20° for easy slicing. Bench chisels: 25°–30° for general joinery. Mortise chisels: 30°–35° for lever strength. Bench plane irons: 25°–30° primary, sometimes 35° for hardwoods. Block plane: 20°–25° (bevel up, so effective cutting angle is bed angle + bevel angle). Carving gouges: 10°–15° for softwood, 20°–25° for hardwood. Steeper angles are more durable; lower angles are keener but nick more easily on hard or abrasive woods.',
  },
  {
    id: 'md-hollow-grind',
    topic: 'Hollow grind vs flat grind for sharpening',
    keywords: ['hollow','grind','flat','wheel','bench','grinder','back','bevel','advantage'],
    answer: 'A hollow grind (from a bench grinder wheel) produces a concave bevel — only the edge and the heel touch the stone during honing. This makes honing faster because less steel touches the stone. A flat grind (from a flat grinding wheel or abrasive sheet) produces a flat bevel that fully contacts the stone — slower to hone but produces a stronger edge (no thin heel that can chip). Both work well; hollow grinds are popular for hand tools, flat grinds for chisels that do heavy mortising work.',
  },
  {
    id: 'md-micro-bevel',
    topic: 'Micro bevel technique for faster touch-ups',
    keywords: ['micro','bevel','secondary','hone','quick','touch','up','angle','degree'],
    answer: 'A micro bevel raises the honing angle 2°–5° above the primary bevel angle and creates a tiny secondary bevel at the very edge. The advantage: you only need to touch the small micro bevel on the fine stone for quick touch-ups between heavy sharpening sessions — far less steel to remove. Lift the tool slightly higher on the stone to engage only the micro bevel. When the micro bevel gets wide (more than 1/16"), re-grind the primary bevel to reset the process.',
  },
  {
    id: 'md-back-bevel',
    topic: 'Back bevel on plane irons for high-angle cutting',
    keywords: ['back','bevel','plane','high','angle','tearout','figured','steep','effective'],
    answer: 'A back bevel adds a small bevel on the flat back of a plane iron — if the primary bevel is 25° and you add a 5° back bevel, the effective cutting angle becomes 30°. Higher effective cutting angles reduce tearout in figured or interlocked grain. On bevel-up planes (low angle, block, shoulder), back bevel is the standard way to increase cutting angle. On bevel-down (bench) planes, a steeper primary bevel is easier than a back bevel. A 50°–55° effective angle handles most difficult grain.',
  },
  {
    id: 'md-honing-guides',
    topic: 'Honing guides vs freehand sharpening',
    keywords: ['honing','guide','jig','freehand','angle','consistent','beginner','Veritas','Eclipse'],
    answer: 'Honing guides (Veritas MK.II, Eclipse) hold the tool at a consistent angle across the stone, removing the skill requirement for freehand technique. They\'re excellent for beginners and for maintaining exact consistent bevel angles. Freehand sharpening is faster once mastered, more adaptable to odd-shaped tools, and requires no setup time. Start with a guide while learning; transition to freehand as you develop muscle memory for the angle. Carving tools almost always need freehand technique — guides don\'t accommodate gouges.',
  },
  {
    id: 'md-flattening-stones',
    topic: 'Flattening sharpening stones — why and how',
    keywords: ['flatten','stone','dish','hollow','nagura','lapping','diamond','flat','glass'],
    answer: 'Waterstones dish (hollow out) in the middle quickly with regular use. A dished stone creates a convex bevel on your tools — the opposite of what you want. Flatten regularly (every 3–5 sessions) by rubbing on a diamond plate, wet-dry sandpaper on a flat glass plate, or a dedicated lapping plate. Use circular or figure-8 motions and check flatness with a straightedge. A flat stone is fundamental to good sharpening results — no amount of skill compensates for a dished stone.',
  },
  {
    id: 'md-grinding-primary-bevel',
    topic: 'Grinding the primary bevel on a bench grinder',
    keywords: ['grind','primary','bevel','bench','grinder','wheel','blue','overheat','temper','cool'],
    answer: 'Use a white aluminum oxide wheel (8" × 1") at 3450 RPM with a tool rest set to the bevel angle. Move the tool smoothly side to side to keep the bevel uniform and prevent grooving the wheel. Quench in water frequently — if the steel turns blue, you\'ve overheated and destroyed the temper at that point. Keep a bowl of cool water at the grinder. The edge should produce sparks that fall toward you (not over the top of the tool) when grinding correctly. Dress the wheel often to keep it flat and cutting freely.',
  },
  {
    id: 'md-carving-gouge-sharp',
    topic: 'Sharpening carving gouges — inside and outside bevel',
    keywords: ['carving','gouge','sharpen','slipstone','inside','outside','burr','strop'],
    answer: 'Carving gouges require sharpening both the outside bevel (on a waterstone, rolling the gouge across its curve as you move forward) and removing the wire edge on the inside (with a curved slipstone or rounded strop). The outside bevel should be polished to 8000 grit; the inside just needs the burr removed with a few strokes. Sharp carving gouges cleanly slice end grain and leave a burnished, not torn, surface. Test sharpness by paring end grain — it should pare cleanly with no effort.',
  },
  {
    id: 'md-when-to-regrind',
    topic: 'When to hone vs when to regrind the bevel',
    keywords: ['regrind','hone','micro','bevel','wide','nick','chip','dull','decide'],
    answer: 'Hone (sharpen on fine stones only) when the edge is dull from normal use — the micro bevel has widened. Regrind (reshape on a coarse stone or grinder) when there\'s a chip in the edge, the bevel has become too convex from repeated honing, or the micro bevel is more than 1/8" wide. A quick test: if you can sharpen to a keen edge in under 2 minutes on a 1000 grit stone, just hone. If it takes much longer with little improvement, it\'s time to regrind the primary bevel.',
  },
  {
    id: 'md-sharpness-tests',
    topic: 'Testing sharpness — multiple methods',
    keywords: ['sharp','test','paper','hair','arm','thumb','light','reflect','end','grain'],
    answer: 'Several sharpness tests: arm hair test — a truly sharp edge shaves arm hair cleanly. Thumbnail test — drag the edge lightly across a fingernail; it should grip, not slide. Paper test — slice newspaper; a sharp edge cuts cleanly, a dull edge tears. Reflecting light test — look at the edge under a light; a sharp edge reflects nothing (invisible), a dull edge reflects a bright thin line. End grain test — pare end grain; sharp tools leave a shiny, smooth surface. For furniture tools, the end grain test is the most practical real-world indicator.',
  },
  {
    id: 'md-japanese-water-stones',
    topic: 'Japanese natural water stones vs synthetic',
    keywords: ['japanese','natural','water','stone','awasedo','nakayama','synthetic','toishi'],
    answer: 'Natural Japanese finishing stones (awasedo, nakayama) produce extremely fine edges but are expensive ($100–$1000+), variable in quality, and require careful storage to prevent cracking. Synthetic Japanese stones (King, Naniwa, Shapton) are consistent, affordable, and excellent quality — used by most professional woodworkers. Shapton Kuromaku and Naniwa Chosera are considered among the best synthetic options. Natural stones are prized mainly by high-end woodworkers, knife makers, and collectors; synthetics are the practical choice for a working shop.',
  },

  // ── WORKHOLDING & JIGS ───────────────────────────────────────────────────────
  {
    id: 'md-face-vise-setup',
    topic: 'Face vise setup and use on a workbench',
    keywords: ['face','vise','bench','front','left','right','dog','screw','clamp'],
    answer: 'The face vise is mounted on the front-left corner of the bench for right-handers (front-right for left-handers). Its jaws clamp work for planing, sawing, and chiseling. Wide vises (7"+ jaw width) support wide panels. A wooden jaw liner (hardwood laminate on the inner vise jaw) prevents marking workpieces. Many face vises have a quick-release mechanism to adjust width rapidly. Set the inner jaw face flush with the bench top — the bench top and vise top form one flat reference plane.',
  },
  {
    id: 'md-leg-vise',
    topic: 'Leg vise advantages for hand tool work',
    keywords: ['leg','vise','parallel','guide','crisscross','large','hold','traditional'],
    answer: 'A leg vise mounts on the front leg and uses a large wooden jaw that travels parallel to the bench leg — typically 24" tall or more. The parallel guide (a wooden arm or crisscross mechanism below the vise) keeps the jaw parallel to the leg as it opens. Leg vises can hold very wide or irregular work that won\'t fit in a standard face vise. They\'re the traditional European workbench vise and are making a strong comeback among hand tool workers. Building your own leg vise from a hardware kit is a satisfying first project.',
  },
  {
    id: 'md-tail-vise',
    topic: 'Tail vise and wagon vise for panel work',
    keywords: ['tail','vise','wagon','end','bench','dog','panel','planing'],
    answer: 'The tail vise (or wagon vise) is at the right end of the bench and is used with bench dogs — round or square pegs in holes along the bench top and the vise. Clamp long boards or wide panels between the bench dog in the vise and another dog further along the bench top. The work lies flat on the bench and is clamped from the side rather than from below, keeping the surface clear for planing. Tail vises are complex to build; a simpler alternative is a Moxon vise for panel flattening.',
  },
  {
    id: 'md-moxon-vise',
    topic: 'Moxon vise for dovetail and joint work',
    keywords: ['moxon','vise','portable','twin','screw','dovetail','top','clamp','low'],
    answer: 'The Moxon vise is a simple twin-screw wooden vise that clamps to the front of the workbench with holdfasts or clamps. Its high profile raises the work to a comfortable hand-sawing height — ideal for dovetail and other detailed joinery. Build one from hardwood and hardware store threaded rod in an afternoon. Sit the Moxon vise on the bench to raise work for dovetailing; remove it when bench space is needed. Many woodworkers consider the Moxon essential for comfortable, accurate hand joinery.',
  },
  {
    id: 'md-holdfast-use',
    topic: 'Holdfasts for quick clamping to the bench',
    keywords: ['holdfast','bench','hole','anvil','quick','hammer','clamp','shaft'],
    answer: 'A holdfast is a metal shaft (often L-shaped) that drops into a hole in the bench top — a smart tap with a mallet locks it fast via wedging action. Tap the side to release instantly. They\'re extremely fast for positioning and repositioning work on the bench. Holdfasts need holes exactly matched to the shaft diameter (3/4" for most Gramercy and Crucible holdfasts) and a bench top at least 3" thick for good grip. They\'re one of the most satisfying traditional shop tools to use.',
  },
  {
    id: 'md-clamp-types',
    topic: 'Clamp types for different woodworking tasks',
    keywords: ['clamp','types','parallel','pipe','bar','F','spring','band','Bessey'],
    answer: 'Parallel jaw clamps (Bessey, Jet) apply even pressure along the full jaw width — best for panel glue-ups, less racking than bar clamps. Pipe clamps use standard plumbing pipe as the beam — inexpensive and infinitely extendable. Bar clamps are lighter than pipe clamps but limited to their bar length. F-clamps (C-clamps with sliding bar) are fast and useful for clamping assemblies to the bench. Spring clamps are quick for light-duty tacking while other clamps set. Band clamps (strap clamps) wrap around irregular shapes and polygon frames.',
  },
  {
    id: 'md-crosscut-sled',
    topic: 'Building and using a crosscut sled',
    keywords: ['crosscut','sled','table','saw','square','accurate','stop','block','jig'],
    answer: 'A crosscut sled runs in the table saw miter slots on runners, carrying work past the blade with precision and support. The key: the fence must be exactly perpendicular to the blade. Calibrate by testing: cut a known-square piece of MDF in half, flip one piece, and check for any gap at the joint — any gap doubles the error. Adjust by shimming the fence. Add a stop block for repeatable lengths. A well-made crosscut sled is more accurate and safer than a miter gauge for crosscutting solid wood.',
  },
  {
    id: 'md-tenon-jig',
    topic: 'Tenon jig for table saw tenon cutting',
    keywords: ['tenon','jig','table','saw','vertical','hold','fence','shoulder','cheek'],
    answer: 'A tenon jig holds the workpiece vertically against a fence and rides along the rip fence to cut tenon cheeks. The cheek cuts run with the grain in a vertical orientation — safer and cleaner than horizontal cheek cuts with a dado stack. After cheek cuts, lay the piece flat to cut the shoulders with a crosscut sled. Commercial tenon jigs (Kreg, Woodpeckers) are robust and accurate; building your own from scrap is a common shop project. Test each tenon for fit in a test mortise before final cuts.',
  },
  {
    id: 'md-box-joint-jig',
    topic: 'Box joint jig construction and setup',
    keywords: ['box','joint','jig','key','spacing','router','table','saw','index'],
    answer: 'The box joint jig consists of a fence with a key (a small wooden or metal pin the same width as the joint fingers) attached to the miter gauge or router table fence. Cut the first slot, place it over the key, cut the next slot, and so on. Key placement relative to the blade determines finger spacing. The most common method: cut the first slot at the blade, then move the fence so the slot is exactly one finger-width from the blade (using the key). Minor adjustments correct for tight or loose fitting joints.',
  },
  {
    id: 'md-taper-jig',
    topic: 'Taper jig for cutting tapered legs',
    keywords: ['taper','jig','leg','table','saw','set','angle','shopmade','sliding'],
    answer: 'A taper jig holds stock at an angle to the saw blade for ripping a taper. Commercial taper jigs have two arms that pivot and lock at the desired angle. Shop-made taper jigs are a notched board with a stop at the end — the notch determines the taper. For a four-sided taper, taper two faces first, rotate 90°, and rest the tapered face against the jig for the second two cuts. Make a test cut in scrap to confirm the taper angle before cutting finished legs.',
  },
  {
    id: 'md-circle-cutting-jig',
    topic: 'Router circle jig for round tabletops',
    keywords: ['circle','jig','router','round','tabletop','radius','pivot','pin','trammel'],
    answer: 'A circle-cutting jig mounts to the router base with a pivot pin that sits at the center of the circle. The radius from pin to bit equals the circle radius. Drill a small hole at the center of your blank, seat the pivot pin, and rout in a clockwise direction in multiple shallow passes. A router circle jig produces perfect circles impossible to achieve any other way. Alternatively, bandsaw close to the line first and use the router jig only for the final 1/8" — this puts less load on the bit and gives a cleaner edge.',
  },
  {
    id: 'md-doweling-jig',
    topic: 'Self-centering doweling jig setup',
    keywords: ['doweling','jig','self','centering','align','drill','guide','hole','accurate'],
    answer: 'Self-centering doweling jigs have jaws that grip the stock and automatically center the drill guide on the stock thickness regardless of width — ideal for edge-to-face joints and rail-to-leg connections. Lock the jig at the correct position along the board (mark your center line), drill to depth with the appropriate bit. Repeat on the mating piece with the jig in the same position. The key: always register the jig from the same face on both pieces so holes align even if the jig isn\'t perfectly centered.',
  },
  {
    id: 'md-vacuum-clamping',
    topic: 'Vacuum clamping for router template work',
    keywords: ['vacuum','clamp','hold','template','pod','cup','pump','flat','bottom'],
    answer: 'Vacuum clamping uses atmospheric pressure (~14.7 psi) to hold flat workpieces without clamps obstructing the surface. A vacuum pump (or venturi venturi) evacuates air from a pad or pod under the workpiece. Works best on flat, non-porous material — porous wood needs a sealed face or a vacuum bag. Holding force = 14.7 psi × contact area in sq. in. A 6"×6" pad provides 529 lbs of holding force — more than sufficient for routing operations. Add a veneer or MDF face to the workpiece if it\'s porous.',
  },
  {
    id: 'md-featherboard-function',
    topic: 'Featherboard function and placement',
    keywords: ['featherboard','pressure','fence','blade','table','saw','router','spring','hold'],
    answer: 'A featherboard applies spring pressure to push the workpiece against the fence or table surface — preventing it from drifting and catching. It must be placed BEFORE the blade or bit (never at the blade or after) — a featherboard at the blade would trap the cut piece and cause kickback. Position it so the fingers flex back when the stock pushes past. Commercial featherboards clamp to the table with T-bolts; shop-made versions use a notched board clamped to the fence. Use one on the fence and optionally one on the table surface for router table work.',
  },
  {
    id: 'md-shooting-board',
    topic: 'Shooting board for accurate edges and miters',
    keywords: ['shooting','board','edge','plane','square','miter','45','accurate','thin'],
    answer: 'A shooting board is a flat platform with a fence at 90° (or 45°) to the running surface. A hand plane rides on its side along the shooting board to true up the end of a board perfectly square or at a precise 45°. Essential for accurate miter joints where gaps are unacceptable. The bench plane rides on the shooting board sole, making a shearing cut across the grain — the square fence registers the workpiece. Shooting board miters can be fit to a knife-line accuracy not possible with any power tool.',
  },
  {
    id: 'md-bench-hook',
    topic: 'Bench hook for one-handed crosscutting',
    keywords: ['bench','hook','crosscut','hand','saw','secure','one','hand','seat','stop'],
    answer: 'A bench hook is a simple shop-made device: a flat board with a cleat on the bottom that hooks over the bench front, and a cleat on top that acts as a back stop for the workpiece. Rest the work against the top cleat and saw on the near side — the bench hook keeps the work from moving. The bottom cleat keeps the hook on the bench. Make several in different sizes. The bench hook works with no clamping — just hook it over the bench edge and you\'re ready to saw.',
  },

  // ── SAFETY ───────────────────────────────────────────────────────────────────
  {
    id: 'md-kickback-mechanics',
    topic: 'Table saw kickback — mechanics and prevention',
    keywords: ['kickback','table','saw','riving','knife','anti','pawl','splitter','fence','cause'],
    answer: 'Kickback happens when a board gets pinched between the blade and the fence (or fence and riving knife) and the spinning blade launches it toward the operator at 100+ mph. Prevention: always use the riving knife (keeps the kerf open behind the blade), never stand directly behind the blade, never use the fence and miter gauge simultaneously, keep the blade height just above the stock. A stock that veers into the blade (because the fence is slightly toe-in at the back) is a kickback setup — fence must be parallel to the blade.',
  },
  {
    id: 'md-riving-knife',
    topic: 'Riving knife vs splitter — what is the difference',
    keywords: ['riving','knife','splitter','difference','follow','blade','SawStop','modern'],
    answer: 'A riving knife follows the blade as it tilts — it stays behind the blade at all bevel angles and at all blade heights. A fixed splitter is only in the correct position at a specific blade height and doesn\'t move with blade tilt. Riving knives are the modern standard on all European and newer North American table saws. If your saw has only a fixed splitter, use it anyway — it\'s far better than nothing. Never remove the riving knife or splitter for dado cuts without a dado guard.',
  },
  {
    id: 'md-push-stick-design',
    topic: 'Push stick design and when to use it',
    keywords: ['push','stick','design','narrow','rip','blade','guard','hand','safe','distance'],
    answer: 'A push stick keeps your hands away from the table saw blade for narrow rips (under 6" wide) and anytime a piece requires your hand to pass near the blade. The notch-style push stick contacts the rear edge of the board and pushes through the cut. A push block (like a Grr-Ripper) provides downward pressure and side pressure simultaneously — better control. Make several push sticks from scrap and replace them when they get nicked. Always reach for a push stick rather than your fingers when a cut gets tight.',
  },
  {
    id: 'md-router-safety-detail',
    topic: 'Router safety — bit installation and speed',
    keywords: ['router','safety','bit','collet','speed','large','starter','pin','guard'],
    answer: 'Install bits with at least 3/4" of shank in the collet — never shallow-seated. Tighten with two wrenches (not one). Unplug before changing bits. For freehand routing, secure the workpiece firmly — two hands on the router, no exceptions. Large bits (over 1.5" diameter) need speeds under 16,000 RPM. Always rout against the bit rotation (conventional direction) unless doing a final light climb cut. Wear eye protection — routers launch chips at high velocity. Ear protection is mandatory — routers are extremely loud.',
  },
  {
    id: 'md-fine-dust-health',
    topic: 'Fine wood dust health dangers',
    keywords: ['dust','fine','micron','10','lung','cancer','sensitize','health','long','term'],
    answer: 'Particles below 10 microns (invisible to the eye) penetrate deeply into lungs and are the most dangerous. Regular shop dust collectors filter down to 1–5 microns typically; cyclone separators help capture fine particles before the filter. Many wood species are carcinogenic with long-term exposure (walnut, oak, certain tropical species). Sensitization develops over time — years of exposure can lead to asthma and allergic reactions that worsen. A basic dust collector removes visible dust; fine dust requires a filter rated to 1 micron or better, plus respiratory protection.',
  },
  {
    id: 'md-respirator-types',
    topic: 'Respirator types for woodworking',
    keywords: ['respirator','N95','P100','half','face','HEPA','OV','finish','spray','dust'],
    answer: 'N95 filters particles ≥0.3 microns and blocks 95% — adequate for light sanding on non-toxic species. P100 filters 99.97% of particles including the finest wood dust and is the minimum for heavy production sanding, toxic species, and finishing operations. For spray finishing, add OV (organic vapor) cartridges to the P100 half-face respirator — the particulate filter alone doesn\'t remove vapor. Half-face respirators with P100+OV combination cartridges cover both dust and finish vapors in one unit. Disposable N95 masks are inconvenient but better than nothing.',
  },
  {
    id: 'md-spontaneous-combustion',
    topic: 'Spontaneous combustion of oily rags — the real risk',
    keywords: ['spontaneous','combustion','rag','oily','fire','danish','linseed','tung','dispose'],
    answer: 'Oily rags (linseed oil, danish oil, tung oil) can self-ignite through exothermic oxidation as the oil cures — no external flame required. A pile of oil-soaked rags can reach ignition temperature in under an hour. Every year shops burn down from this. Always: spread oil-soaked rags flat on a non-combustible surface outside to dry completely before disposal. Or submerge in water in a metal can with a lid. Never ball them up or throw them in a trash bin while still wet with oil. Water-based finishes don\'t carry this risk.',
  },
  {
    id: 'md-dust-collector-cfm',
    topic: 'Dust collector CFM requirements for shop machines',
    keywords: ['dust','collector','cfm','volume','shop','machine','table','saw','planer','require'],
    answer: 'CFM (cubic feet per minute) determines whether a dust collector can keep up with chip production. Table saw: 400–700 CFM. Jointer (8"): 400 CFM. Planer (13"): 500–800 CFM. Bandsaw: 350 CFM. Router table: 300 CFM. These are minimums — bigger is better. A 1-1/2 HP shop vac produces ~100–150 CFM — adequate for routers and sanders but not planers or table saws. A 1.5 HP dedicated dust collector provides ~600–800 CFM with proper hose sizing. Hose length and elbows reduce CFM — minimize runs and bends.',
  },
  {
    id: 'md-hearing-protection-nrr',
    topic: 'Hearing protection NRR ratings for woodworking',
    keywords: ['hearing','protection','NRR','decibel','earmuff','earplug','reduce','noise'],
    answer: 'NRR (Noise Reduction Rating) measures how many decibels a hearing protector reduces. A router runs ~100 dB; 85+ dB causes hearing damage with sustained exposure. NRR 33 earplugs reduce by ~16 dB in real use (the formula: NRR - 7) ÷ 2 for field performance). For very loud tools, double up — earplugs under earmuffs. Most woodworking requires NRR 25–33 protection. Never run a table saw, jointer, planer, or router without hearing protection — one hour a day over years causes permanent irreversible damage.',
  },
  {
    id: 'md-bandsaw-safety',
    topic: 'Bandsaw safety considerations',
    keywords: ['bandsaw','safety','guard','blade','tension','crack','weld','speed','curve'],
    answer: 'Keep the upper blade guard close to the workpiece — just above the work. Never reach around a moving blade. If the blade drifts off a cut, stop and restart rather than twisting the work to compensate (blade weld failure can happen). Slow feed on curves — forcing a turn wider than the blade TPI allows causes blade buckling. Check blade welds periodically for stress cracks at the weld point. The bandsaw is generally safer than the table saw but still demands full attention; most bandsaw injuries happen to fingers reaching near the blade to adjust work.',
  },
  {
    id: 'md-chisel-safety',
    topic: 'Chisel safety — direction and hand placement',
    keywords: ['chisel','safety','direction','hand','behind','guard','controlled','slip'],
    answer: 'Never put your non-holding hand in front of the chisel cutting direction — if it slips, the blade goes toward that hand. Clamp the work so both hands are on the chisel. Pare across a corner away from your body, not toward it. Keep chisels sharp — dull chisels require force that causes slipping. Store chisels with their edges protected (a tool roll, rack with edge guards, or individual blade covers). Never leave a chisel edge-up on the bench where it can be accidentally grasped edge-first.',
  },
  {
    id: 'md-oily-shop-rag-storage',
    topic: 'Safe storage of shop rags and cloths',
    keywords: ['rag','storage','metal','can','water','fire','safe','lid','dispose'],
    answer: 'The safest method for used finishing rags: keep a metal can with a tight-fitting lid filled with water. Drop rags into the water immediately after use — the water prevents the oxidation reaction that causes spontaneous combustion. Dispose of the can contents (now harmless, water-soaked rags) at a hazardous waste collection site or let the rags fully dry outside spread flat, then dispose in regular trash. A $25 Justrite safety can is a lifetime investment against shop fires.',
  },
  {
    id: 'md-table-saw-stance',
    topic: 'Body positioning at the table saw',
    keywords: ['stance','table','saw','position','body','kickback','line','stand','feet'],
    answer: 'Never stand directly behind the blade or in line with the blade — this is the kickback danger zone. Stand to the left of the blade line (for right-handed operators) so a kickback event fires to your right, not into your body. Keep your left arm behind your body to avoid having it in the kickback path when feeding narrow stock. Keep feet shoulder-width apart, balanced but mobile. Never stretch beyond comfortable reach — walk around for long boards rather than leaning over the blade.',
  },
  {
    id: 'md-jointer-pushblock',
    topic: 'Jointer push blocks and finger injury prevention',
    keywords: ['jointer','push','block','finger','guard','hand','clear','blade','over'],
    answer: 'The jointer outfeed section is the danger zone — fingers can reach the cutter head as the board passes. Use push blocks that straddle the fence and table to keep hands clear of the cutter head. Never back-feed (pull wood back over the cutter head). Use featherboards to maintain consistent fence pressure. Keep the guard over the non-working side of the cutter head. Jointers account for a high percentage of serious woodworking injuries — treat them with full respect and use push blocks for every pass.',
  },

  // ── PROJECT TYPES ────────────────────────────────────────────────────────────
  {
    id: 'md-cabinet-face-frame',
    topic: 'Face frame cabinet construction details',
    keywords: ['face','frame','cabinet','construction','rail','stile','overlay','inset','pocket'],
    answer: 'Face frame cabinets have a solid wood frame (stiles and rails) glued and screwed to the front of a plywood or particleboard box. The frame creates a finished front, hides the box construction, and provides a robust mounting surface for hinges and drawer slides. Stiles are the vertical frame members; rails are horizontal. Pocket screws are the fastest assembly method for face frames. Overlay doors and inset doors are both possible — inset requires the box and frame to be built to tighter tolerances.',
  },
  {
    id: 'md-frameless-cabinet',
    topic: 'Frameless (European) cabinet construction',
    keywords: ['frameless','european','32mm','box','cabinet','overlay','full','efficiency','quick'],
    answer: 'Frameless cabinets have no face frame — the door and drawer fronts overlap the box sides completely (full overlay). The box is built from 3/4" plywood or particleboard with dado-and-rabbet joints. The 32mm hole system spaces hinge holes, shelf pin holes, and drawer slide mounting holes on a 32mm grid. Frameless construction is faster, requires less wood, and provides maximum interior access. Hinges must be European cup hinges (adjustable, concealed). The interior is completely accessible with drawers open, unlike face frame cabinets.',
  },
  {
    id: 'md-cabinet-back-options',
    topic: 'Cabinet back options — dado vs rabbet vs surface mount',
    keywords: ['cabinet','back','dado','rabbet','surface','mount','1/4','plywood','square'],
    answer: 'Three main approaches for cabinet backs. Dado into the sides: strongest, keeps back flush with sides, allows the back to add racking resistance. Rabbet into the back edge of the sides: fast, back overlaps the sides slightly. Surface mount: just screw a plywood panel to the back of the assembled box — easiest but adds depth and looks less finished. For furniture-grade work, dado the back into all four sides and glue it in for maximum rigidity. For shop cabinets, surface mount is quick and adequate.',
  },
  {
    id: 'md-drawer-construction',
    topic: 'Drawer box construction — sizing and materials',
    keywords: ['drawer','box','size','clearance','height','width','sides','bottom','plywood'],
    answer: 'Size a drawer box to the opening: width = opening width minus clearance for slides (check slide specs — undermount usually need 1/2" less than opening, side mount need slide thickness × 2 less). Height = opening height minus 1/2"–3/4" for clearance and bottom thickness. Drawer bottom: 1/4" plywood in a groove cut 1/4"–3/8" from the bottom edge. Side material: 1/2" Baltic birch or hardwood is traditional; 5/8" particleboard is commercial standard. The bottom slides in dry (no glue) to allow movement, but can be pinned from below at the back.',
  },
  {
    id: 'md-drawer-dovetail-layout',
    topic: 'Laying out drawer dovetail spacing',
    keywords: ['drawer','dovetail','layout','spacing','even','pin','tail','half','pin','end'],
    answer: 'For a classic drawer front dovetail layout: begin and end with half-pins (narrower than the tails, typically the same width as your chisel). Divide the remaining space into an odd or even number of equal spaces for tails. Traditional ratios: tails about twice as wide as pins. Space tails evenly using dividers (walk them across until they divide equally). The number of tails depends on drawer width — about one per 1-1/2" is a reasonable guide. Mark all tails on one drawer front, then use it as a template for identical drawers.',
  },
  {
    id: 'md-piano-bench-construction',
    topic: 'Bench (seating) construction principles',
    keywords: ['bench','seating','seat','apron','leg','stretcher','joint','height','strength'],
    answer: 'A seat bench needs to resist significant racking forces from side loads and people leaning. Mortise-and-tenon apron-to-leg joints are the historical standard. Stretchers (rails near the floor) tie the legs together and dramatically increase resistance to racking. Seat height for dining: 17"–18". Seat depth: 14"–16". Add a wedge-tenon or drawbore peg through any exposed through tenon for maximum strength. Seat width per person: 20"–24". Check that the bench clears a dining table apron — the seat edge must be reachable without hitting the apron.',
  },
  {
    id: 'md-chair-joinery-stress',
    topic: 'Chair joinery for stress and longevity',
    keywords: ['chair','joinery','stress','load','racking','dovetail','wedge','angle','spindle'],
    answer: 'Chairs are the most structurally demanding furniture — they carry dynamic loads and rack in all directions. Mortise-and-tenon with drawbore pegs or wedged through tenons at the back posts. Round tenons (turned) in round mortises for spindles and rungs — the round tenon can\'t rack. Angled joints (where the rear legs splay back) are the hardest: mortises must be cut at compound angles to match the leg geometry. Glue every joint; chairs assembled with pocket screws alone will fail within years under normal use.',
  },
  {
    id: 'md-windsor-chair',
    topic: 'Windsor chair construction overview',
    keywords: ['windsor','chair','spindle','turned','seat','bow','rung','green','wood'],
    answer: 'Windsor chairs combine a solid slab seat (scooped with a travisher) with turned spindles, bent steam-bent bows, and turned leg-and-rung bases. Traditionally built with multiple species: white pine seat (soft for seat carving), steam-bent ash or oak for the bow, turned oak or hickory for legs. Green wood (unseasoned) spindles and rungs are turned oversize, then dried — when glued into drilled holes in the dry seat and posts, the dried wood expands with moisture and locks the joint permanently. An elegant, zero-glue joinery system.',
  },
  {
    id: 'md-tabletop-movement',
    topic: 'Allowing wood movement in tabletops',
    keywords: ['tabletop','movement','attach','clip','slot','season','expand','contract','solid'],
    answer: 'A solid wood tabletop 24" wide might move 3/8"–1/2" seasonally. The top must be attached to the apron in a way that allows this movement in width — NOT along the length (minimal movement in that direction). Figure-8 fasteners, Z-clips, wooden clips in apron slots, or bed bolt-style slotted wooden buttons all work. Never glue or rigidly screw a solid top in multiple places along the grain — it will crack at the glue joints or at the fastener holes when seasonal movement is blocked.',
  },
  {
    id: 'md-table-apron-joinery',
    topic: 'Table apron to leg joinery options',
    keywords: ['apron','leg','joinery','mortise','tenon','pocket','screw','table','corner'],
    answer: 'The strongest apron-to-leg joint for tables: mortise-and-tenon, glued and possibly pinned. The tenon extends about 2/3 through the leg, with a 1/4" gap between mating tenons at a corner for a corner block or pocket screw reinforcement. Pocket screws alone are adequate for light-use tables but fail over years under stress. Corner blocks (triangular blocks glued into the inside corner) reinforce the joint and help prevent racking. Metal corner brackets are a functional but less attractive alternative.',
  },
  {
    id: 'md-box-construction',
    topic: 'Small box construction techniques',
    keywords: ['box','lid','fit','hinge','miter','rabbet','small','jewelry','trinket'],
    answer: 'Small boxes use mitered corners (reinforced with splines or keys), finger joints, or rabbet and dado construction. Build the box as a complete unit, then cut the lid off with a thin saw blade — this ensures perfect lid alignment. For small hinges, mortise them flush for a clean line. The lid-to-box fit should be snug but open smoothly with light pressure — test the fit before applying finish. Line the box interior with felt, thin suede, or flocked material; apply this before the final assembly step if access is limited.',
  },
  {
    id: 'md-lid-fitting',
    topic: 'Fitting box and chest lids for a smooth reveal',
    keywords: ['lid','fit','reveal','even','gap','hinge','offset','overhang','chest'],
    answer: 'A well-fitted lid has even gaps all around — typically 1/16"–1/8" for a finished box. Shoot the lid to fit with a hand plane; work on the ends first, then the long edges. Hinge placement affects alignment — offset hinges (surface or mortised) position the pivot differently. Piano hinge on large lids distributes the load evenly and prevents the lid from racking. Lid supports (chain, table leaf hinges, or pneumatic supports) prevent the lid from falling flat and putting stress on the hinges.',
  },
  {
    id: 'md-bookcase-shelving',
    topic: 'Bookcase and shelving construction decisions',
    keywords: ['bookcase','shelf','fixed','adjustable','dado','pin','sag','span','load'],
    answer: 'Fixed shelves dadoed into sides are strongest and prevent racking; adjustable shelves on pins are more versatile. For span limits: 3/4" plywood sags noticeably over 36" under book loads; 3/4" solid maple lasts a bit longer. Solutions: edge banding (solid wood front edge adds rigidity), solid wood shelves, thicker stock (1" or more), or center dividers. A 5mm shelf pin in each of four holes provides about 50 lbs per shelf — adequate for most home library loads.',
  },
  {
    id: 'md-workbench-design',
    topic: 'Workbench top thickness and vise placement',
    keywords: ['workbench','top','thickness','vise','placement','dog','hole','spacing','mass'],
    answer: 'Workbench top thickness: 3"–4" for a heavy hand tool bench (mass dampens vibration), 2"–2.5" for a lighter combination bench. Vise placement: face vise at the left front corner, leg vise at the left front leg, tail vise at the right end. Dog hole spacing: every 6"–8" across the top in a line parallel to the front edge. The bench dog holes align with the tail vise dog for panel clamping. Workbench height: your palm-to-floor distance is a common guide for hand planing.',
  },
  {
    id: 'md-workbench-mass',
    topic: 'Why mass matters in a workbench',
    keywords: ['workbench','mass','heavy','vibration','walk','rattle','stable','weight'],
    answer: 'A heavy bench stays put during planing — it doesn\'t walk across the shop floor. Mass absorbs the impact of mallet blows and crosscut saws without bouncing or rattling. A laminated hardwood top (maple, beech, oak) at 4" thick weighs 150–250 lbs just for the top. Leg joinery should be mortise-and-tenon for rigidity — a wobbly bench is the bane of accurate hand tool work. If your bench moves during use, add weight (an undershelf of concrete blocks works in a pinch) or improve the leg joinery.',
  },
  {
    id: 'md-cabinet-door-fitting',
    topic: 'Fitting cabinet doors for even reveals',
    keywords: ['cabinet','door','fit','reveal','gap','plane','sand','consistent','even'],
    answer: 'Even reveals (the gap between the door edge and cabinet opening) require careful fitting. Start with the door 1/16" oversize in each dimension. Hang the door on one hinge, mark where it binds, and shim to check gap before fixing the second hinge. Plane or sand the door edges on a shooting board for final fitting — work from one edge, hang, check, adjust. Target 1/16"–3/32" reveals all around for face frame inset doors. Frameless full-overlay doors use European hinge adjustment instead of door edge trimming.',
  },
  {
    id: 'md-kitchen-cabinet-layout',
    topic: 'Kitchen cabinet standard heights and depths',
    keywords: ['kitchen','cabinet','height','depth','base','wall','upper','standard','clearance'],
    answer: 'Standard kitchen dimensions: base cabinets 34.5" tall (with 1.5" countertop = 36" finished). Base cabinet depth: 24" (23.5" box + door). Wall (upper) cabinets: 12"–13" deep, typically 30" or 42" tall, mounted at 54" from floor (18" clearance above counter). Distance from counter to bottom of upper cabinet: 18" minimum (15" in pantry areas where taller items store on counter). These are standards, not rules — adjust for the specific user\'s height and functional needs.',
  },
  {
    id: 'md-floating-shelves',
    topic: 'Floating shelf construction with hidden brackets',
    keywords: ['floating','shelf','hidden','bracket','hardware','sleeve','cleat','blind'],
    answer: 'Floating shelves appear to hover without visible support. Methods: metal cantilever brackets bolted into studs with the shelf sleeved over them (commercial system); a wall-mounted cleat with a matching routed channel in the shelf back; or heavy-duty blind shelf pins in a drilled shelf edge. Studs are critical for load capacity — only the stud-mounted bracket carries the load. For solid wood floating shelves, cut slightly short (1/8"–1/4") to allow seasonal wood movement across the width without the shelf binding against the wall.',
  },
  {
    id: 'md-entertainment-center',
    topic: 'Entertainment center design and AV equipment clearances',
    keywords: ['entertainment','center','tv','av','ventilation','cable','depth','clearance','heat'],
    answer: 'Design entertainment centers with ventilation for AV equipment — amplifiers and receivers generate significant heat. Open backs or ventilation slots in cabinet backs and tops prevent heat buildup. TV depth (if recessed): measure the TV\'s screen-to-back-of-mount depth carefully. Cable management: plan channels in vertical members from the start — adding them after construction is much harder. Component depth: 24" is standard for current AV equipment, but confirm against your specific gear before building.',
  },
  {
    id: 'md-murphy-bed',
    topic: 'Murphy (wall) bed construction basics',
    keywords: ['murphy','bed','wall','fold','piston','spring','hardware','cabinet','counterbalance'],
    answer: 'Murphy beds use counterbalance hardware (pistons or springs) to offset the weight of the mattress so the bed folds up and down effortlessly. Buy a hardware kit first and build the case to the kit\'s exact dimensions — each manufacturer specifies the case dimensions for their spring system. Mount the unit into studs or with heavy-duty lag bolts into blocking between studs — Murphy beds in use carry 300–500 lbs. Side cabinets and shelving units attached to the Murphy case stabilize the whole unit.',
  },
  {
    id: 'md-outdoor-furniture',
    topic: 'Outdoor furniture construction principles',
    keywords: ['outdoor','furniture','teak','cedar','stainless','lap','joint','drain','recess'],
    answer: 'Outdoor furniture must drain and dry quickly to prevent rot. Design with drainage: avoid horizontal surfaces that pond water (angle flat surfaces slightly), use open joints rather than fully closed dado joints that trap moisture. Use rot-resistant species (teak, ipe, western red cedar, black locust) or pressure-treated lumber. Fasten with stainless steel or hot-dipped galvanized fasteners — regular steel rusts and stains the wood. Joinery must tolerate seasonal movement more extreme than indoor furniture (40–80% RH range in many climates).',
  },
  {
    id: 'md-bed-frame-construction',
    topic: 'Bed frame construction for strength and assembly',
    keywords: ['bed','frame','rail','post','mattress','platform','slat','support','bolt'],
    answer: 'Bed frames must support 500–800 lbs of combined load. Queen and king beds need a center support leg from the mid-rail to the floor. Rail-to-post connections: bed bolts (barrel nuts), mortise-and-tenon with bed bolts, or heavy metal rail-to-post brackets. Platform beds with a slat system: slats should be 3"–4" wide hardwood, spaced 3" maximum. Cover each slat with non-slip fabric to prevent mattress sliding. Build beds to be disassemble-able for moving — drawbore pegs or bolted connections only, no permanent glue at rail-to-post.',
  },
  {
    id: 'md-toy-chest-safety',
    topic: 'Toy chest safety requirements',
    keywords: ['toy','chest','lid','support','hinge','ventilation','safety','child','finger'],
    answer: 'Toy chests present entrapment and finger-pinch hazards. Use a lid support that holds the lid open at any angle and prevents sudden drop (spring-loaded lid supports or piano hinge with a lid stay chain). Ventilation holes are required by consumer safety standards — drill 1/2" holes in the front near the top if the lid seals tightly. Rounded edges on all corners. Hinges must allow a child\'s fingers to avoid the pinch zone. Paint or finish with non-toxic, child-safe finishes — check the manufacturer\'s label specifically.',
  },
  {
    id: 'md-cutting-board-design',
    topic: 'Cutting board construction — end grain vs edge grain',
    keywords: ['cutting','board','end','edge','grain','glue','food','safe','warp','rubber','feet'],
    answer: 'End grain cutting boards expose the wood fibers\' open ends — knives slip between fibers rather than cutting across them, preserving the blade edge longer and self-healing small cuts. They\'re thick (1.5"–3") to prevent warping. Edge grain boards are thinner, lighter, and easier to build. Both need glues rated as food-safe when cured (Titebond III, food-safe epoxy). Finish with mineral oil and beeswax — never linseed oil, danish oil, or any curing finish. Rubber feet prevent slipping and lift the board for airflow.',
  },
  {
    id: 'md-speaker-cabinet',
    topic: 'Speaker cabinet construction — wood and joinery',
    keywords: ['speaker','cabinet','enclosure','MDF','bracing','joint','joint','resonance'],
    answer: 'Speaker enclosures need dense, rigid walls to minimize resonance — MDF is standard because it\'s inert acoustically. Void-free 3/4" MDF is the choice for most speaker builders. Dados and rabbets at corners are structural; glue all joints with PVA and add internal corner braces. Dadoed braces inside the enclosure at the midpoint break up internal standing waves and add rigidity. Veneered MDF gives a furniture appearance with the acoustic properties of MDF. Laminate all seams with silicone or wood filler before veneer to prevent telegraph.',
  },
];
